"use client";

import { Faq } from "@/lib/types/strapi-autogenerated";
import { Flex, Paper, Stack, Text } from "@mantine/core";
import { IconChevronDown } from "@tabler/icons-react";
import { useState } from "react";

function FAQItem({ faq }: { faq: Faq }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <Paper
      p="md"
      radius="lg"
      style={{
        background: "rgba(255, 255, 255, 0.02)",
        border: "1px solid rgba(255, 255, 255, 0.06)",
        cursor: "pointer",
      }}
      onClick={() => setIsOpen(!isOpen)}
    >
      <Flex justify="space-between" align="center" gap="md">
        <Text fw={500} style={{ color: "#f1f5f9" }}>
          {faq.title}
        </Text>
        <div
          style={{
            color: "#64748b",
            transition: "transform 0.2s ease",
            transform: isOpen ? "rotate(180deg)" : "rotate(0deg)",
            flexShrink: 0,
          }}
        >
          <IconChevronDown size={20} />
        </div>
      </Flex>
      {isOpen && (
        <Text
          mt="md"
          style={{
            color: "#94a3b8",
            lineHeight: 1.7,
            borderTop: "1px solid rgba(255, 255, 255, 0.06)",
            paddingTop: 12,
          }}
        >
          {faq.description}
        </Text>
      )}
    </Paper>
  );
}

export function Questions({
  leftColumn,
  rightColumn,
}: {
  leftColumn: Faq[];
  rightColumn: Faq[];
}) {
  return (
    <Flex gap={24} direction={{ base: "column", md: "row" }}>
      <Stack gap={16} style={{ flex: 1 }}>
        {leftColumn.map((faq) => (
          <FAQItem key={faq.documentId} faq={faq} />
        ))}
      </Stack>
      <Stack gap={16} style={{ flex: 1 }}>
        {rightColumn.map((faq) => (
          <FAQItem key={faq.documentId} faq={faq} />
        ))}
      </Stack>
    </Flex>
  );
}
