import { ActionIcon, SimpleGrid, Stack, Text, Title } from "@mantine/core";
import { IconVideo } from "@tabler/icons-react";
import { getFormatter, getTranslations } from "next-intl/server";

import { fetchProfileRecordings, getFollower } from "./actions/actions";

import { getSocialUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { generateProfileUrl } from "@/app/lib/profile-url";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { Metadata } from "next";
import { ImageVideoPreview } from "./components/image-video-preview";

interface PageProps {
  params: Promise<{
    username: string;
    type: string;
  }>;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ username: string; type: string }>;
}): Promise<Metadata> {
  const { type, username } = await params;
  const t = await getTranslations("profile");

  const follower = await getFollower({ username, type });

  if (!follower) {
    return {
      title: t("meta.notFoundTitle"),
      description: t("meta.notFoundDescription"),
    };
  }

  const platformName = type.charAt(0).toUpperCase() + type.slice(1);
  const translation = {
    nickname: follower.nickname || "",
    username: follower.username,
    platform: platformName,
  };
  const title = t("meta.title", translation);
  const description = follower.tagline || t("meta.description", translation);

  return {
    title,
    description,
    keywords: t("meta.keywords", translation).split(", "),
    openGraph: {
      title: t("meta.ogTitle", translation),
      description,
      type: "profile",
      siteName: "Live Stream Recorder",
      images: [
        `${process.env.NEXT_PUBLIC_BASE_URL}/api/og/${generateProfileUrl(
          follower,
          false,
        )}`,
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: t("meta.twitterTitle", translation),
      description,
      images: [
        `${process.env.NEXT_PUBLIC_BASE_URL}/api/og/${generateProfileUrl(
          follower,
          false,
        )}`,
      ],
    },
    alternates: {
      canonical: generateProfileUrl(follower, true),
    },
  };
}

export default async function Page({ params }: PageProps) {
  const { type, username } = await params;
  const t = await getTranslations("profile");
  const format = await getFormatter();
  const follower = await getFollower({ username, type });
  const data = await fetchProfileRecordings(type, username);
  const recordings = data?.data ?? [];
  const hasRecordings = recordings.length > 0;

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: follower.nickname || follower.username,
    alternateName: `@${follower.username}`,
    description: follower.tagline || follower.description,
    image: generateAvatarUrl(follower.avatar?.url, true),
    url: generateProfileUrl(follower, true),
    nationality: follower.country,
    sameAs: [getSocialUrl(follower)],
    mainContentOfPage: {
      "@type": "ItemList",
      itemListElement: recordings.slice(0, 5).map((video, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: `${generateProfileUrl(follower, true)}/video/${video.documentId}`,
      })),
    },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      {!hasRecordings ? (
        <EmptyState />
      ) : (
        <Stack gap="xl">
          <Stack gap="md">
            <SimpleGrid cols={{ base: 1, sm: 2 }} spacing="lg">
              {recordings?.map((rec) => (
                <Stack key={rec.documentId} gap={4}>
                  <ImageVideoPreview
                    recording={rec}
                    type={type as unknown as FollowerTypeEnum}
                  />
                  <Text size="xs">
                    {t("recorded", {
                      date: format.dateTime(new Date(rec.createdAt || ""), {
                        year: "numeric",
                        month: "short",
                        day: "numeric",
                      }),
                    })}
                  </Text>
                </Stack>
              ))}
            </SimpleGrid>
          </Stack>
        </Stack>
      )}
    </>
  );
}

async function EmptyState() {
  const t = await getTranslations("profile");

  return (
    <Stack align="center" justify="center" py={80} gap="lg">
      <ActionIcon variant="transparent" size={120} radius="xl" color="white">
        <IconVideo size={90} stroke={2} />
      </ActionIcon>
      <Stack align="center" gap={12}>
        <Title order={2} fw={600}>
          {t("emptyState.title")}
        </Title>
        <Text size="xl" c="dimmed" maw={450} ta="center">
          {t("emptyState.description")}
        </Text>
      </Stack>
    </Stack>
  );
}
