"use client";

import { useRouter } from "@/i18n/navigation";
import { Clip } from "@/lib/types/strapi-autogenerated";
import {
  AspectRatio,
  Box,
  Flex,
  Group,
  Paper,
  Stack,
  Switch,
  Text,
  Title,
  UnstyledButton,
} from "@mantine/core";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type ClipWithUrl = Clip & { signedClipUrl?: string | null };

interface Props {
  clips: ClipWithUrl[];
  currentClipId: string;
  baseUrl: string;
}

export function ClipTheater({ clips, currentClipId, baseUrl }: Props) {
  const router = useRouter();
  const [autoplay, setAutoplay] = useState(true);
  const videoRef = useRef<HTMLVideoElement>(null);
  const queueRef = useRef<HTMLDivElement>(null);

  const currentClip = useMemo(
    () => clips.find((c) => c.documentId === currentClipId),
    [clips, currentClipId],
  );

  const currentIndex = useMemo(
    () => clips.findIndex((c) => c.documentId === currentClipId),
    [clips, currentClipId],
  );

  const goTo = useCallback(
    (clipId: string) => {
      router.push(`${baseUrl}/${clipId}`, { scroll: false });
    },
    [router, baseUrl],
  );

  const handleEnded = useCallback(() => {
    if (!autoplay) return;
    const next = clips[currentIndex + 1];
    if (next?.documentId) goTo(next.documentId);
  }, [autoplay, clips, currentIndex, goTo]);

  // Auto-scroll the active queue item into view on change
  useEffect(() => {
    const active = queueRef.current?.querySelector<HTMLElement>(
      "[data-active='true']",
    );
    if (active) {
      active.scrollIntoView({ block: "nearest", behavior: "smooth" });
    }
  }, [currentClipId]);

  if (!currentClip) return null;

  return (
    <Flex
      direction={{ base: "column", md: "row" }}
      gap="md"
      align="flex-start"
      p="md"
    >
      {/* Player */}
      <Box style={{ flex: 7, width: "100%", minWidth: 0 }}>
        <Paper
          withBorder
          radius="md"
          style={{ overflow: "hidden", background: "#000" }}
        >
          <AspectRatio ratio={16 / 9}>
            {currentClip.signedClipUrl && (
              <video
                ref={videoRef}
                key={currentClip.documentId}
                src={currentClip.signedClipUrl}
                controls
                autoPlay
                playsInline
                onEnded={handleEnded}
                style={{
                  width: "100%",
                  height: "100%",
                  background: "#000",
                }}
              />
            )}
          </AspectRatio>
        </Paper>

        <Stack gap={4} mt="sm">
          <Title order={4}>{currentClip.title || "—"}</Title>
          <Text size="sm" c="dimmed">
            @{currentClip.follower?.username}
          </Text>
        </Stack>
      </Box>

      {/* Queue */}
      <Paper
        withBorder
        radius="md"
        p="sm"
        style={{
          flex: 3,
          width: "100%",
          minWidth: 0,
          maxHeight: "calc(100vh - 200px)",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Group justify="space-between" mb="xs" wrap="nowrap">
          <Stack gap={0}>
            <Title order={5}>Up next</Title>
            <Text size="xs" c="dimmed">
              {currentIndex >= 0 ? currentIndex + 1 : 1} / {clips.length}
            </Text>
          </Stack>
          <Switch
            size="xs"
            checked={autoplay}
            onChange={(e) => setAutoplay(e.currentTarget.checked)}
            label={autoplay ? "Autoplay on" : "Autoplay off"}
          />
        </Group>

        <Box
          ref={queueRef}
          style={{ flex: 1, overflowY: "auto", minHeight: 0 }}
        >
          <Stack gap="xs">
            {clips.map((clip, idx) => {
              const isActive = clip.documentId === currentClipId;
              return (
                <UnstyledButton
                  key={clip.documentId}
                  data-active={isActive ? "true" : undefined}
                  onClick={() => clip.documentId && goTo(clip.documentId)}
                  p="xs"
                  style={{
                    borderRadius: 8,
                    background: isActive
                      ? "rgba(82, 255, 148, 0.08)"
                      : "transparent",
                    border: isActive
                      ? "1px solid rgba(82, 255, 148, 0.3)"
                      : "1px solid transparent",
                  }}
                >
                  <Flex gap="sm" wrap="nowrap" align="flex-start">
                    <Text size="xs" c="dimmed" w={20} ta="right" mt={2}>
                      {idx + 1}
                    </Text>
                    <Box
                      pos="relative"
                      style={{
                        flexShrink: 0,
                        width: 100,
                        aspectRatio: "16 / 9",
                        background: "#000",
                        borderRadius: 4,
                        overflow: "hidden",
                      }}
                    >
                      {clip.signedClipUrl && (
                        <video
                          src={clip.signedClipUrl}
                          muted
                          playsInline
                          preload="metadata"
                          style={{
                            width: "100%",
                            height: "100%",
                            objectFit: "cover",
                          }}
                        />
                      )}
                    </Box>
                    <Stack gap={2} style={{ flex: 1, minWidth: 0 }}>
                      <Text
                        size="sm"
                        fw={isActive ? 600 : 500}
                        lineClamp={2}
                        style={{ lineHeight: 1.3 }}
                      >
                        {clip.title || "—"}
                      </Text>
                      {(clip.viewsCount ?? 0) > 0 && (
                        <Text size="xs" c="dimmed">
                          {clip.viewsCount} views
                        </Text>
                      )}
                    </Stack>
                  </Flex>
                </UnstyledButton>
              );
            })}
          </Stack>
        </Box>
      </Paper>
    </Flex>
  );
}
