import { getUser } from "@/app/actions/user";
import Link from "@/app/components/link";
import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum, ScopeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Badge,
  Box,
  Card,
  Divider,
  Flex,
  Group,
  Image,
  Scroller,
  Skeleton,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconWorldSearch } from "@tabler/icons-react";
import { getTranslations } from "next-intl/server";
import { Suspense } from "react";
import {
  fetchFavoriteRecordings,
  fetchLatestFollowers,
  fetchRecordingsByPlatform,
} from "./actions/fetch-recordings";
import { DiscoverSection } from "./components/discover-section";
import { FavoritesSection } from "./components/favorites-section";
import { GreetingSection } from "./components/greeting-section";
import { LatestFollowersSection } from "./components/latest-followers-section";
import { MyFeedSection } from "./components/my-feed-section";

const platformMap: Record<string, FollowerTypeEnum> = {
  TikTok: FollowerTypeEnum.Tiktok,
  Twitch: FollowerTypeEnum.Twitch,
  Kick: FollowerTypeEnum.Kick,
  YouTube: FollowerTypeEnum.Youtube,
  AfreecaTV: FollowerTypeEnum.Afreecatv,
  Pandalive: FollowerTypeEnum.Pandalive,
  Bigo: FollowerTypeEnum.Bigo,
  Buzzcast: FollowerTypeEnum.Buzzcast,
  Tango: FollowerTypeEnum.Tango,
  LiveMe: FollowerTypeEnum.Liveme,
};

export default async function Page() {
  const t = await getTranslations("protected.dashboard");

  // Start all promises without awaiting - they run in parallel
  const userPromise = getUser();
  const followersPromise = fetchLatestFollowers();
  const favoritesPromise = fetchFavoriteRecordings();

  const myFeedPromise = Promise.all(
    streamingPlatforms.map(async (platform) => {
      const type = platformMap[platform.name];
      const recordings = await fetchRecordingsByPlatform(
        ScopeEnum.Following,
        type,
      );
      return { ...platform, type, recordings };
    }),
  );

  const discoverPromise = Promise.all(
    streamingPlatforms.map(async (platform) => {
      const type = platformMap[platform.name];
      const recordings = await fetchRecordingsByPlatform(
        ScopeEnum.Discover,
        type,
      );
      return { ...platform, type, recordings };
    }),
  );

  return (
    <Stack w="100%">
      <Card radius="lg" withBorder p="0">
        <Suspense fallback={<Skeleton h={80} m="xl" radius="md" />}>
          <GreetingSection userPromise={userPromise} />
        </Suspense>

        <Divider />

        <Scroller px="md" py="md">
          <Group gap="sm" wrap="nowrap">
            {streamingPlatforms.map((platform) => {
              const isNew =
                platform.name === "Buzzcast" || platform.name === "Tango" || platform.name === "LiveMe";
              return (
                <Link
                  key={platform.name}
                  href={`/explore?type=${platformMap[platform.name]}`}
                  style={{ textDecoration: "none", flexShrink: 0 }}
                >
                  <Stack
                    align="center"
                    justify="flex-start"
                    gap={8}
                    px="lg"
                    py="md"
                    h={120}
                    style={{
                      borderRadius: "var(--mantine-radius-lg)",
                      border: `1px solid ${isNew ? "rgba(139, 92, 246, 0.4)" : "rgba(255,255,255,0.1)"}`,
                      background: isNew
                        ? "rgba(139, 92, 246, 0.08)"
                        : "rgba(255,255,255,0.03)",
                      cursor: "pointer",
                      minWidth: 100,
                    }}
                  >
                    <Image
                      src={platform.file}
                      alt={platform.name}
                      w={36}
                      h={36}
                      style={{ filter: "brightness(0) invert(1)" }}
                    />
                    <Text size="sm" fw={600} c="white">
                      {platform.name}
                    </Text>
                    {isNew ? (
                      <Badge size="xs" variant="filled" color="violet">
                        NEW
                      </Badge>
                    ) : null}
                  </Stack>
                </Link>
              );
            })}
          </Group>
        </Scroller>

        <Divider />

        <Box
          py="sm"
          px={{ base: "xs", sm: "md" }}
          style={{ background: "linear-gradient(150deg, #B4F4FF, #52DDE8)" }}
        >
          <Flex justify="space-between" align="center" w="100%">
            <Stack gap={2}>
              <Flex gap="xs" align="center">
                <IconWorldSearch size={24} color="black" />
                <Title order={1} size="lg" c="black">
                  {t("newCreators")}
                </Title>
              </Flex>
            </Stack>
          </Flex>
        </Box>
        <Divider mx={{ base: "-xs", sm: "-md" }} />

        <Suspense fallback={<Skeleton h={120} radius="md" m="md" />}>
          <LatestFollowersSection followersPromise={followersPromise} />
        </Suspense>

        <Suspense fallback={<Skeleton h={200} radius="md" m="md" />}>
          <FavoritesSection favoritesPromise={favoritesPromise} />
        </Suspense>

        <Suspense fallback={<Skeleton h={360} radius="md" m="md" />}>
          <MyFeedSection myFeedPromise={myFeedPromise} />
        </Suspense>

        <Suspense fallback={<Skeleton h={360} radius="md" m="md" />}>
          <DiscoverSection discoverPromise={discoverPromise} />
        </Suspense>
      </Card>
    </Stack>
  );
}
