"use server";

import api from "@/lib/api";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { deepMerge } from "@mantine/core";
import { buildCreatorsFilters, CreatorFilters } from "../lib/search-params";

const defaultOptions = {
  "pagination[pageSize]": 10,
  scope: ScopeEnum.Discover,
  populate: {
    avatar: { fields: ["url"] },
    recordings: {
      populate: {
        sources: {
          fields: ["*"],
          filters: { state: { $ne: "failed" } },
          populate: ["videoSmall", "videoOriginal"],
        },
      },
    },
  },
};

export async function fetchFollowers(filters: CreatorFilters, page: number) {
  const response = await api.follower.browseFollowers(
    deepMerge(defaultOptions, {
      filters: buildCreatorsFilters(filters),
      sort: filters.sort,
      hasRecordings: filters.hasRecordings,
      "pagination[page]": page,
    })
  );

  return {
    data: response.data?.data || [],
    meta: response.data?.meta,
  };
}
