"use client";

import { BattlesPage, getStreamerBattles } from "@/app/actions/analytics";
import { Battle, BattleBattleTypeEnum, BattleStatusEnum } from "@/lib/types/analytics-autogenerated";
import {
  Badge,
  Box,
  Group,
  LoadingOverlay,
  Pagination,
  Paper,
  Table,
  TableScrollContainer,
  TableTbody,
  TableTd,
  TableTh,
  TableThead,
  TableTr,
  Text,
  Title,
} from "@mantine/core";
import { useFormatter, useTranslations } from "next-intl";
import { use, useState } from "react";
import { formatCompact } from "../lib";

const LIMIT = 10;

const DATE_FORMAT = {
  year: "numeric",
  month: "short",
  day: "numeric",
  hour: "numeric",
  minute: "2-digit",
} as const;

interface BattlesListProps {
  username: string;
  battlesPromise: Promise<BattlesPage>;
}

function outcomeColor(battleWon: number) {
  if (battleWon === 1) return "green";
  if (battleWon === 0) return "gray";
  return "red";
}

export function BattlesList({ username, battlesPromise }: BattlesListProps) {
  const t = useTranslations("protected.profileInsights");
  const format = useFormatter();
  const initialData = use(battlesPromise);
  const [battles, setBattles] = useState<Battle[]>(initialData.data);
  const [total, setTotal] = useState(initialData.total);
  const [activePage, setActivePage] = useState(1);
  const [loading, setLoading] = useState(false);

  const totalPages = Math.ceil(total / LIMIT);

  const handlePageChange = async (page: number) => {
    setActivePage(page);
    setLoading(true);
    const result = await getStreamerBattles(
      username,
      LIMIT,
      (page - 1) * LIMIT,
    );
    setBattles(result.data);
    setTotal(result.total);
    setLoading(false);
  };

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #FFD4B4, #E88852)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">
        {t("battleHistory.title")}
        {total > 0 && (
          <Text span size="sm" fw={400} c="dark.3" ml={8}>
            ({total})
          </Text>
        )}
      </Title>
    </Box>
  );

  if (!battles.length && !loading) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">
            {t("battleHistory.empty")}
          </Text>
        </Box>
      </Paper>
    );
  }

  return (
    <Paper withBorder radius="md">
      <style>{`
        @keyframes livePulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.35; }
        }
      `}</style>
      {header}

      <Box style={{ position: "relative" }}>
        <LoadingOverlay
          visible={loading}
          zIndex={1}
          overlayProps={{ radius: "sm", blur: 2 }}
        />
        <TableScrollContainer minWidth={800}>
          <Table striped highlightOnHover fz="sm">
            <TableThead>
              <TableTr>
                <TableTh>{t("battleHistory.colDate")}</TableTh>
                <TableTh>{t("battleHistory.colType")}</TableTh>
                <TableTh>{t("battleHistory.colOpponents")}</TableTh>
                <TableTh>{t("battleHistory.colScore")}</TableTh>
                <TableTh>{t("battleHistory.colDiamonds")}</TableTh>
                <TableTh>{t("battleHistory.colResult")}</TableTh>
              </TableTr>
            </TableThead>
            <TableTbody>
              {battles.map((b, i) => {
                const isLive = b.status === BattleStatusEnum.Live;
                const isInterrupted = b.status === BattleStatusEnum.Interrupted;
                const battleType = b.battle_type ?? BattleBattleTypeEnum.Value1V1;
                const battleWon = b.battle_won ?? -1;
                const s1 = b.team_1_score ?? 0;
                const s2 = b.team_2_score ?? 0;
                const s3 = b.team_3_score ?? 0;
                const s4 = b.team_4_score ?? 0;
                const multiplier = b.max_multiplier ?? 0;

                // --- Opponents cell (C) ---
                // For 2v2 and 2v1, streamer_2 is a teammate — show "w/ @teammate vs @opps"
                const hasTeammate =
                  battleType === BattleBattleTypeEnum.Value2V2 ||
                  battleType === BattleBattleTypeEnum.Value2V1;

                const opponentsNode = hasTeammate ? (
                  <Text size="sm" truncate maw={200}>
                    {b.streamer_2_username && (
                      <>
                        <Text span size="xs" c="dimmed">
                          {t("battleHistory.with")}{" "}
                        </Text>
                        <Text span>@{b.streamer_2_username}</Text>
                        {"  "}
                      </>
                    )}
                    <Text span size="xs" c="dimmed">
                      {t("battleHistory.vs")}{" "}
                    </Text>
                    {[b.streamer_3_username, b.streamer_4_username]
                      .filter(Boolean)
                      .map((u, idx) => (
                        <Text span key={u}>
                          {idx > 0 ? ", " : ""}@{u}
                        </Text>
                      ))}
                  </Text>
                ) : (
                  <Text size="sm" truncate maw={160}>
                    {[
                      b.streamer_2_username,
                      b.streamer_3_username,
                      b.streamer_4_username,
                    ]
                      .filter(Boolean)
                      .map((u) => `@${u}`)
                      .join(", ") || "—"}
                  </Text>
                );

                // --- Score cell (B) ---
                let scoreNode;
                if (isLive || isInterrupted) {
                  scoreNode = (
                    <Text size="sm" c="dimmed">
                      —
                    </Text>
                  );
                } else if (
                  battleType === BattleBattleTypeEnum.Value2V2 ||
                  battleType === BattleBattleTypeEnum.Value2V1
                ) {
                  // Our team = positions 1+2, opponents = positions 3+4
                  const myTeam = s1 + s2;
                  const oppTeam =
                    battleType === BattleBattleTypeEnum.Value2V1
                      ? s3
                      : s3 + s4;
                  const myColor =
                    battleWon === 1 ? "green" : battleWon === 0 ? "dimmed" : "red";
                  const oppColor =
                    battleWon === 1 ? "red" : battleWon === 0 ? "dimmed" : "green";
                  scoreNode = (
                    <Text size="sm" fw={500}>
                      <Text span c={myColor} fw={700}>
                        {formatCompact(myTeam)}
                      </Text>{" "}
                      <Text span c="dimmed">
                        {t("battleHistory.vs")}
                      </Text>{" "}
                      <Text span c={oppColor} fw={700}>
                        {formatCompact(oppTeam)}
                      </Text>
                    </Text>
                  );
                } else if (battleType === BattleBattleTypeEnum.Value1V2) {
                  // Streamer alone vs 2 opponents
                  const myColor =
                    battleWon === 1 ? "green" : battleWon === 0 ? "dimmed" : "red";
                  const oppColor =
                    battleWon === 1 ? "red" : battleWon === 0 ? "dimmed" : "green";
                  scoreNode = (
                    <Text size="sm" fw={500}>
                      <Text span c={myColor} fw={700}>
                        {formatCompact(s1)}
                      </Text>{" "}
                      <Text span c="dimmed">
                        {t("battleHistory.vs")}
                      </Text>{" "}
                      <Text span c={oppColor} fw={700}>
                        {formatCompact(s2 + s3)}
                      </Text>
                    </Text>
                  );
                } else if (
                  battleType === BattleBattleTypeEnum.Value1V1V1 ||
                  battleType === BattleBattleTypeEnum.Value1V1V1V1
                ) {
                  // All scores shown individually
                  const allScores =
                    battleType === BattleBattleTypeEnum.Value1V1V1
                      ? [s1, s2, s3]
                      : [s1, s2, s3, s4];
                  const parts = allScores.flatMap((score, idx) => {
                    const pos = idx + 1;
                    let color: string;
                    if (battleWon === 0) color = "dimmed";
                    else if (pos === 1) color = battleWon === 1 ? "green" : "red";
                    else color = battleWon === pos ? "orange" : "dimmed";
                    const bold = pos === 1 || battleWon === pos;
                    return [
                      ...(idx > 0
                        ? [
                            <Text key={`sep-${idx}`} span c="dimmed">
                              {" "}–{" "}
                            </Text>,
                          ]
                        : []),
                      <Text key={`s-${idx}`} span c={color} fw={bold ? 700 : 400}>
                        {formatCompact(score)}
                      </Text>,
                    ];
                  });
                  scoreNode = <Text size="sm">{parts}</Text>;
                } else {
                  // 1v1 (default)
                  const myColor =
                    battleWon === 1 ? "green" : battleWon === 0 ? "dimmed" : "red";
                  const oppColor =
                    battleWon === 1 ? "red" : battleWon === 0 ? "dimmed" : "green";
                  scoreNode = (
                    <Text size="sm" fw={500}>
                      <Text span c={myColor} fw={700}>
                        {formatCompact(s1)}
                      </Text>{" "}
                      <Text span c="dimmed">
                        {t("battleHistory.vs")}
                      </Text>{" "}
                      <Text span c={oppColor} fw={700}>
                        {formatCompact(s2)}
                      </Text>
                    </Text>
                  );
                }

                return (
                  <TableTr key={b.battle_id ?? i}>
                    <TableTd>
                      <Text size="sm">
                        {b.started_at
                          ? format.dateTime(new Date(b.started_at), DATE_FORMAT)
                          : "—"}
                      </Text>
                    </TableTd>
                    <TableTd>
                      <Badge variant="outline" size="xs">
                        {b.battle_type ?? "1v1"}
                      </Badge>
                    </TableTd>
                    <TableTd>{opponentsNode}</TableTd>
                    <TableTd>{scoreNode}</TableTd>
                    <TableTd>
                      {b.gifts_during_battle != null &&
                      b.gifts_during_battle > 0 ? (
                        <Group gap={4} wrap="nowrap">
                          <Badge color="yellow" variant="light" size="sm">
                            {formatCompact(b.gifts_during_battle)}
                          </Badge>
                          {multiplier >= 2 && (
                            <Text size="xs" c="yellow.6" fw={700}>
                              ×{multiplier}
                            </Text>
                          )}
                        </Group>
                      ) : (
                        <Text size="sm" c="dimmed">
                          —
                        </Text>
                      )}
                    </TableTd>
                    <TableTd>
                      {isLive ? (
                        <Badge
                          color="red"
                          variant="filled"
                          size="sm"
                          style={{
                            animation: "livePulse 1.5s ease-in-out infinite",
                          }}
                        >
                          {t("battleHistory.live")}
                        </Badge>
                      ) : isInterrupted ? (
                        <Badge color="gray" variant="light" size="sm">
                          {t("battleHistory.interrupted")}
                        </Badge>
                      ) : (
                        <Badge
                          color={outcomeColor(battleWon)}
                          variant="light"
                          size="sm"
                        >
                          {battleWon === 1
                            ? t("battleHistory.won")
                            : battleWon === 0
                              ? t("battleHistory.draw")
                              : t("battleHistory.lost")}
                        </Badge>
                      )}
                    </TableTd>
                  </TableTr>
                );
              })}
            </TableTbody>
          </Table>
        </TableScrollContainer>
      </Box>

      {totalPages > 1 && (
        <Box p="md" style={{ display: "flex", justifyContent: "center" }}>
          <Pagination
            total={totalPages}
            value={activePage}
            onChange={handlePageChange}
            size="sm"
          />
        </Box>
      )}
    </Paper>
  );
}
