import { Follower } from "@/lib/types/strapi-autogenerated";
import { getProfileUrl } from "../(protected)/components/open-social";

export function generateProfileUrl(
  follower?: Partial<Pick<Follower, "username" | "type">>,
  fullURL: boolean = false
) {
  if (!follower) {
    return "";
  }

  return (
    (fullURL ? `https://www.livestreamrecorder.com` : ``) +
    getProfileUrl(follower)
  );
}
