import { Follower } from "@/lib/types/strapi-autogenerated";
import { getProfileUrl } from "../components/open-social";
import { CANONICAL_BASE_URL } from "./canonical";

export function generateProfileUrl(
  follower?: Partial<Pick<Follower, "username" | "type">>,
  fullURL: boolean = false,
) {
  if (!follower) {
    return "";
  }

  // The full-URL form is only ever used for SEO output (JSON-LD @id/url and
  // og:url) — navigation uses the relative form. So the absolute host must be
  // the canonical .com, never the mirror deployment's own host.
  return (fullURL ? CANONICAL_BASE_URL : ``) + getProfileUrl(follower);
}

/**
 * Profile URL prefixed with /my for use inside the logged-in app section.
 * Public pages should keep using `getProfileUrl` directly.
 */
export function getMyProfileUrl(
  follower?: Partial<Pick<Follower, "username" | "type">>,
) {
  return "/my" + getProfileUrl(follower);
}
