import { Follower } from "@/lib/types/strapi-autogenerated";
import { getProfileUrl } from "../components/open-social";

export function generateProfileUrl(
  follower?: Partial<Pick<Follower, "username" | "type">>,
  fullURL: boolean = false,
) {
  if (!follower) {
    return "";
  }

  return (
    (fullURL ? process.env.NEXT_PUBLIC_BASE_URL : ``) + getProfileUrl(follower)
  );
}
