export const streamingPlatforms = [
  {
    color: "pink.5",
    colorCss: "var(--mantine-color-pink-5)",
    name: "TikTok",
    file: "/simple/tiktok.svg",
  },
  {
    color: "violet.6",
    colorCss: "var(--mantine-color-violet-6)",
    name: "Twitch",
    file: "/simple/twitch.svg",
  },
  {
    color: "lime.5",
    colorCss: "var(--mantine-color-lime-5)",
    name: "Kick",
    file: "/simple/kick.svg",
  },
  {
    color: "red.6",
    colorCss: "var(--mantine-color-red-6)",
    name: "YouTube",
    file: "/simple/youtube.svg",
  },
  {
    color: "red.4",
    colorCss: "var(--mantine-color-red-4)",
    name: "AfreecaTV",
    file: "/simple/afreecatv.svg",
  },
  {
    color: "blue.5",
    colorCss: "var(--mantine-color-blue-5)",
    name: "Pandalive",
    file: "/simple/pandalive.svg",
  },
  {
    color: "teal.5",
    colorCss: "var(--mantine-color-teal-5)",
    name: "Bigo",
    file: "/simple/bigo.svg",
  },
  {
    color: "orange.5",
    colorCss: "var(--mantine-color-orange-5)",
    name: "Buzzcast",
    file: "/simple/buzzcast.svg",
  },
  {
    color: "yellow.5",
    colorCss: "var(--mantine-color-yellow-5)",
    name: "LiveMe",
    file: "/simple/liveme.svg",
  },
  {
    color: "pink.7",
    colorCss: "var(--mantine-color-pink-7)",
    name: "Mixch",
    file: "/simple/mixch.svg",
  },
  {
    color: "cyan.5",
    colorCss: "var(--mantine-color-cyan-5)",
    name: "Twitcast",
    file: "/simple/twitcast.svg",
  },
  {
    color: "green.5",
    colorCss: "var(--mantine-color-green-5)",
    name: "Trovo",
    file: "/simple/trovo.svg",
  },
  {
    color: "indigo.6",
    colorCss: "var(--mantine-color-indigo-6)",
    name: "Joilive",
    file: "/simple/joilive.svg",
  },
  {
    color: "grape.6",
    colorCss: "var(--mantine-color-grape-6)",
    name: "Live17",
    file: "/simple/live17.svg",
  },
  {
    color: "orange.7",
    colorCss: "var(--mantine-color-orange-7)",
    name: "Kwai",
    file: "/simple/kwai.svg",
  },
  {
    color: "lime.7",
    colorCss: "var(--mantine-color-lime-7)",
    name: "Nimotv",
    file: "/simple/nimotv.svg",
  },
  {
    color: "blue.7",
    colorCss: "var(--mantine-color-blue-7)",
    name: "Vklive",
    file: "/simple/vklive.svg",
  },
];
