"use client";

import { UsersPermissionsUser } from "@/lib/types/strapi-autogenerated";
import { createContext, useContext } from "react";

const UserContext = createContext<UsersPermissionsUser | null>(null);

export function UserProvider({
  user,
  children,
}: {
  user: UsersPermissionsUser;
  children: React.ReactNode;
}) {
  return <UserContext.Provider value={user}>{children}</UserContext.Provider>;
}

export function useUser() {
  return useContext(UserContext);
}
