import RecordingItem from "@/app/[locale]/my/components/recording-item";
import Link from "@/app/components/link";
import { Recording } from "@/lib/types/strapi-autogenerated";
import {
  Box,
  Button,
  Divider,
  Flex,
  SimpleGrid,
  Stack,
  Title,
} from "@mantine/core";
import { IconChevronRight, IconDownload } from "@tabler/icons-react";
import { getTranslations } from "next-intl/server";

interface MostDownloadedSectionProps {
  mostDownloadedPromise: Promise<Recording[]>;
}

export async function MostDownloadedSection({
  mostDownloadedPromise,
}: MostDownloadedSectionProps) {
  const t = await getTranslations("protected.dashboard");
  const mostDownloaded = await mostDownloadedPromise;

  if (!mostDownloaded.length) return null;

  return (
    <>
      <Divider />
      <Box
        id="dashboard-most-downloaded"
        style={{ background: "linear-gradient(150deg, #C7E9FF, #4A9EFF)" }}
        py="sm"
        px={{ base: "xs", sm: "md" }}
      >
        <Flex justify="space-between" align="center" w="100%">
          <Flex gap="xs" align="center">
            <IconDownload size={24} color="black" />
            <Title order={1} size="lg" c="black">
              {t("mostDownloaded")}
            </Title>
          </Flex>
          <Link href="/my/explore?sort=downloadsCount%3Adesc">
            <Button
              variant="transparent"
              color="black"
              size="compact-sm"
              rightSection={<IconChevronRight size={16} />}
            >
              {t("browseAll")}
            </Button>
          </Link>
        </Flex>
      </Box>
      <Divider />

      <Stack gap="md" p="md">
        <SimpleGrid cols={{ base: 1, sm: 2, md: 4 }} spacing="sm">
          {mostDownloaded.map((rec) => (
            <RecordingItem key={rec.documentId} recording={rec} />
          ))}
        </SimpleGrid>
      </Stack>
    </>
  );
}
