import RecordingItem from "@/app/[locale]/my/components/recording-item";
import Link from "@/app/components/link";
import { Recording } from "@/lib/types/strapi-autogenerated";
import {
  Box,
  Button,
  Divider,
  Flex,
  SimpleGrid,
  Stack,
  Title,
} from "@mantine/core";
import { IconChevronRight, IconEye } from "@tabler/icons-react";
import { getTranslations } from "next-intl/server";

interface MostViewedSectionProps {
  mostViewedPromise: Promise<Recording[]>;
}

export async function MostViewedSection({
  mostViewedPromise,
}: MostViewedSectionProps) {
  const t = await getTranslations("protected.dashboard");
  const mostViewed = await mostViewedPromise;

  if (!mostViewed.length) return null;

  return (
    <>
      <Divider />
      <Box
        id="dashboard-most-viewed"
        style={{ background: "linear-gradient(150deg, #FFD1DC, #FF6B9D)" }}
        py="sm"
        px={{ base: "xs", sm: "md" }}
      >
        <Flex justify="space-between" align="center" w="100%">
          <Flex gap="xs" align="center">
            <IconEye size={24} color="black" />
            <Title order={1} size="lg" c="black">
              {t("mostViewed")}
            </Title>
          </Flex>
          <Link href="/my/explore?sort=viewsCount%3Adesc">
            <Button
              variant="transparent"
              color="black"
              size="compact-sm"
              rightSection={<IconChevronRight size={16} />}
            >
              {t("browseAll")}
            </Button>
          </Link>
        </Flex>
      </Box>
      <Divider />

      <Stack gap="md" p="md">
        <SimpleGrid cols={{ base: 1, sm: 2, md: 4 }} spacing="sm">
          {mostViewed.map((rec) => (
            <RecordingItem key={rec.documentId} recording={rec} />
          ))}
        </SimpleGrid>
      </Stack>
    </>
  );
}
