"use client";

import Link from "@/app/components/link";
import { getMyProfileUrl } from "@/app/lib/profile-url";
import { Clip, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { Anchor, Box, Card, Stack, Text } from "@mantine/core";
import { IconPlayerPlayFilled } from "@tabler/icons-react";
import { useRef, useState } from "react";

interface Props {
  clip: Clip;
}

export function ShortCard({ clip }: Props) {
  const follower = clip.follower;
  const videoRef = useRef<HTMLVideoElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const signedUrl = (clip as Clip & { signedClipUrl?: string | null })
    .signedClipUrl;

  const handleEnter = () => {
    const v = videoRef.current;
    if (!v) return;
    v.play()
      .then(() => setIsPlaying(true))
      .catch(() => {});
  };

  const handleLeave = () => {
    const v = videoRef.current;
    if (!v) return;
    v.pause();
    v.currentTime = 0;
    setIsPlaying(false);
  };

  return (
    <Card
      radius="md"
      withBorder
      p={0}
      style={{
        overflow: "hidden",
        cursor: "pointer",
        transition: "transform 0.15s ease",
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.transform = "translateY(-2px)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.transform = "translateY(0)";
      }}
    >
      <Anchor
        component={Link}
        href={
          follower
            ? `${getMyProfileUrl(
                follower as unknown as {
                  username?: string;
                  type?: FollowerTypeEnum;
                },
              )}/clips/${clip.documentId}`
            : "#"
        }
        prefetch={false}
        underline="never"
      >
        <Box
          onMouseEnter={handleEnter}
          onMouseLeave={handleLeave}
          style={{
            width: "100%",
            aspectRatio: "9 / 16",
            background: "#000",
            position: "relative",
            overflow: "hidden",
          }}
        >
          {signedUrl && (
            <video
              ref={videoRef}
              src={signedUrl}
              muted
              loop
              playsInline
              preload="metadata"
              style={{
                width: "100%",
                height: "100%",
                objectFit: "cover",
              }}
            />
          )}

          {/* Play badge — fades out while video is playing on hover */}
          <Box
            style={{
              position: "absolute",
              top: "50%",
              left: "50%",
              transform: "translate(-50%, -50%)",
              width: 48,
              height: 48,
              borderRadius: "50%",
              background: "rgba(0, 0, 0, 0.55)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "white",
              opacity: isPlaying ? 0 : 0.9,
              transition: "opacity 0.2s ease",
              pointerEvents: "none",
            }}
          >
            <IconPlayerPlayFilled size={20} />
          </Box>

          {/* "Shorts" pill in bottom-left */}
          <Box
            style={{
              position: "absolute",
              bottom: 8,
              left: 8,
              background: "rgba(255, 82, 168, 0.95)",
              color: "white",
              fontSize: 10,
              fontWeight: 700,
              letterSpacing: 0.5,
              padding: "2px 8px",
              borderRadius: 4,
              textTransform: "uppercase",
            }}
          >
            Shorts
          </Box>

          {/* Views in bottom-right */}
          {(clip.viewsCount ?? 0) > 0 && (
            <Box
              style={{
                position: "absolute",
                bottom: 8,
                right: 8,
                background: "rgba(0, 0, 0, 0.6)",
                color: "white",
                fontSize: 11,
                padding: "2px 6px",
                borderRadius: 4,
              }}
            >
              {clip.viewsCount} views
            </Box>
          )}
        </Box>

        <Stack gap={2} p="xs">
          <Text size="sm" fw={600} lineClamp={2} style={{ lineHeight: 1.3 }}>
            {clip.title || "—"}
          </Text>
          {follower?.username && (
            <Text size="xs" c="dimmed" lineClamp={1}>
              @{follower.username}
            </Text>
          )}
        </Stack>
      </Anchor>
    </Card>
  );
}
