import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";

import { formatDuration } from "@/app/[locale]/(protected)/components/video/player-utils";
import { getProfileUrl } from "@/app/components/open-social";
import {
  FollowerTypeEnum,
  Recording,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import { Anchor } from "@mantine/core";
import { getFormatter, getTranslations } from "next-intl/server";
import Image from "next/image";

interface Props {
  recording: Recording;
  type: FollowerTypeEnum;
}

export async function ImageVideoPreview({ recording, type }: Props) {
  const t = await getTranslations("profile");
  const format = await getFormatter();
  const sources = recording.sources;
  const totalDuration =
    sources?.reduce((sum, s) => sum + (s.duration || 0), 0) || 0;

  const isRecording = sources?.some(
    (s) => s.state === SourceStateEnum.Recording,
  );

  const uri = `/video/${recording.documentId}/`;

  return (
    <div
      style={{
        aspectRatio: "16/9",
        position: "relative",
        overflow: "hidden",
        borderRadius: "var(--mantine-radius-md)",
      }}
    >
      <Anchor
        href={
          getProfileUrl(recording.follower) + `/video/${recording.documentId}`
        }
        style={{
          pointerEvents: isRecording ? "none" : "auto",
          cursor: isRecording ? "not-allowed" : "pointer",
        }}
      >
        <div
          style={{ position: "relative", width: "100%", height: "100%" }}
          suppressHydrationWarning
        >
          <Image
            alt={t("jsonLd.streamTitle", {
              nickname:
                recording.follower?.nickname ||
                recording.follower?.username ||
                "",
              date: format.dateTime(new Date(recording.createdAt || ""), {
                year: "numeric",
                month: "short",
                day: "numeric",
                hour: "numeric",
                minute: "2-digit",
              }),
            })}
            src={
              uri
                ? isRecording
                  ? uri + "screenshot.jpg"
                  : uri + "preview.jpg"
                : "/assets/placeholder/180x280/black/white?text=Recording started"
            }
            fill
            loading="lazy"
            style={{
              objectFit: "cover",
              objectPosition: "center center",
              borderRadius: "var(--mantine-radius-md)",
              ...(isRecording && {
                border: "2px solid red",
              }),
            }}
          />
        </div>
      </Anchor>
      <FollowerTypeIcon
        type={type}
        color="black"
        opacity={0.8}
        pos="absolute"
        top={10}
        right={8}
        style={{
          pointerEvents: "none",
        }}
      />
      {totalDuration > 0 && !isRecording && (
        <div
          style={{
            position: "absolute",
            bottom: 8,
            right: 8,
            backgroundColor: "rgba(0, 0, 0, 0.8)",
            color: "white",
            padding: "2px 6px",
            borderRadius: 4,
            fontSize: 12,
            fontWeight: 500,
            pointerEvents: "none",
          }}
        >
          {formatDuration(totalDuration)}
        </div>
      )}
    </div>
  );
}
