import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";

import { formatDuration } from "@/app/[locale]/(protected)/components/video/player-utils";
import { getProfileUrl, getSocialUrl } from "@/app/components/open-social";
import {
  FollowerTypeEnum,
  Recording,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import { Anchor, Badge, Box, Image } from "@mantine/core";

interface Props {
  recording: Recording;
  type: FollowerTypeEnum;
}

export function ImageVideoPreview({ recording, type }: Props) {
  const sources = recording.sources;
  const totalDuration =
    sources?.reduce((sum, s) => sum + (s.duration || 0), 0) || 0;

  const isRecording = sources?.some(
    (s) => s.state === SourceStateEnum.Recording,
  );

  const uri = sources?.length
    ? "/media" + sources[sources.length - 1].path
    : null;

  return (
    <div
      style={{
        aspectRatio: "16/9",
        position: "relative",
        overflow: "hidden",
        borderRadius: "var(--mantine-radius-md)",
      }}
    >
      <Anchor
        href={
          getProfileUrl(recording.follower) + `/video/${recording.documentId}`
        }
        style={{
          pointerEvents: isRecording ? "none" : "auto",
          cursor: isRecording ? "not-allowed" : "pointer",
        }}
      >
        <Image
          alt=""
          radius="md"
          src={
            uri
              ? isRecording
                ? uri + "screenshot.jpg"
                : uri + "preview.jpg"
              : null
          }
          loading="lazy"
          fallbackSrc="/placeholder/180x280/black/white?text=Recording started"
          w="100%"
          h="100%"
          fit="cover"
          style={{
            objectPosition: "center center",

            ...(isRecording && {
              border: "2px solid red",
              borderRadius: "var(--mantine-radius-md)",
            }),
          }}
        />
      </Anchor>
      {isRecording && (
        <Badge
          component="a"
          href={getSocialUrl(recording.follower)}
          target="_blank"
          rel="noopener noreferrer"
          pos="absolute"
          top={8}
          left={8}
          radius="sm"
          color="red"
          variant="filled"
          size="sm"
          style={{ cursor: "pointer", zIndex: 10 }}
          leftSection={
            <Box
              w={8}
              h={8}
              bg="white"
              style={{ borderRadius: "50%", animation: "pulse 1s infinite" }}
            />
          }
        >
          REC {sources && sources?.length > 1 && `#${sources.length}`}
        </Badge>
      )}
      <FollowerTypeIcon
        type={type}
        color="black"
        opacity={0.8}
        pos="absolute"
        top={10}
        right={8}
        style={{
          pointerEvents: "none",
        }}
      />
      {totalDuration > 0 && !isRecording && (
        <div
          style={{
            position: "absolute",
            bottom: 8,
            right: 8,
            backgroundColor: "rgba(0, 0, 0, 0.8)",
            color: "white",
            padding: "2px 6px",
            borderRadius: 4,
            fontSize: 12,
            fontWeight: 500,
            pointerEvents: "none",
          }}
        >
          {formatDuration(totalDuration)}
        </div>
      )}
    </div>
  );
}
