"use client";

import { Source } from "@/lib/types/strapi-autogenerated";
import "hls-video-element";
import "media-chrome";
import { useMemo, useRef } from "react";
import {
  HlsVideo,
  MediaControlBar,
  MediaController,
  MediaTimeRange,
} from "./media-chrome";
import { combinePlaylistsFromSources } from "./player-utils";

interface Props {
  sources: Source[];
  onTimeClick?: (currentTime: number) => void;
}

export function MiniPlayer({ sources, onTimeClick }: Props) {
  const videoRef = useRef<HTMLVideoElement>(null);

  const playlistDataUrl = useMemo(() => {
    if (!sources?.length) return null;
    const smallMissing = sources.some((s) => !s.videoSmall);
    const playlist = combinePlaylistsFromSources(
      sources,
      smallMissing ? "original" : "small"
    );
    if (!playlist || playlist.length < 50) return null;
    return `data:application/vnd.apple.mpegurl;charset=utf-8,${encodeURIComponent(
      playlist
    )}`;
  }, [sources]);

  const handleClick = () => {
    // hls-video element has currentTime directly on it
    const currentTime = (videoRef.current as any)?.currentTime || 0;
    onTimeClick?.(currentTime);
  };

  if (!playlistDataUrl) return null;

  return (
    <MediaController
      onClick={handleClick}
      style={{
        position: "absolute",
        inset: 0,
        background: "#000",
        borderRadius: 8,
        overflow: "hidden",
        cursor: "pointer",
      }}
    >
      <HlsVideo
        ref={videoRef}
        src={playlistDataUrl}
        slot="media"
        muted
        loop
        playsInline
        autoPlay
        style={{ width: "100%", height: "100%", objectFit: "contain" }}
      />

      <MediaControlBar
        onClick={(e: React.MouseEvent) => e.stopPropagation()}
        style={{
          position: "absolute",
          bottom: 8,
          left: 8,
          right: 8,
          background: "transparent",
        }}
      >
        <MediaTimeRange style={{ width: "100%" }} />
      </MediaControlBar>
    </MediaController>
  );
}
