"use client";

import { Recording } from "@/lib/types/strapi-autogenerated";
import "hls-video-element";
import "media-chrome";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef } from "react";
import {
  HlsVideo,
  MediaControlBar,
  MediaController,
  MediaLoadingIndicator,
  MediaMuteButton,
  MediaPlayButton,
  MediaPosterImage,
  MediaSeekForwardButton,
  MediaTimeDisplay,
  MediaTimeRange,
  MediaVolumeRange,
} from "./media-chrome";

interface VideoPlayerProps {
  recording: Recording;
  defaultMuted?: boolean;
  onMuteChange?: (muted: boolean) => void;
}

export function VideoPlayer({
  recording,
  defaultMuted = true,
  onMuteChange,
}: VideoPlayerProps) {
  const searchParams = useSearchParams();
  const startTime = Number(searchParams.get("t")) || 0;

  const controllerRef = useRef<HTMLElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Handle seek to start time
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !startTime) return;

    const handleLoaded = () => {
      video.currentTime = startTime;
    };

    video.addEventListener("loadedmetadata", handleLoaded, { once: true });

    return () => {
      video.removeEventListener("loadedmetadata", handleLoaded);
    };
  }, [startTime]);

  // Track mute changes
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onMuteChange) return;

    const handleVolumeChange = () => {
      onMuteChange(video.muted);
    };

    video.addEventListener("volumechange", handleVolumeChange);
    return () => video.removeEventListener("volumechange", handleVolumeChange);
  }, [onMuteChange]);

  const handleDoubleClick = () => {
    const controller = controllerRef.current;
    if (!controller) return;

    if (document.fullscreenElement) {
      document.exitFullscreen();
    } else {
      const el = controller as HTMLElement & {
        webkitRequestFullscreen?: () => Promise<void>;
      };
      if (el.requestFullscreen) {
        el.requestFullscreen();
      } else if (el.webkitRequestFullscreen) {
        el.webkitRequestFullscreen();
      }
    }
  };

  return (
    <>
      <MediaController
        ref={controllerRef}
        onDoubleClick={handleDoubleClick}
        style={{
          width: "100%",
          height: "100%",
          background: "#000",
        }}
      >
        <HlsVideo
          ref={videoRef}
          src={`/video/${recording.documentId}/playlist.m3u8`}
          slot="media"
          crossOrigin="anonymous"
          playsInline
          autoPlay
          muted={defaultMuted}
        >
          <track
            default
            kind="metadata"
            label="thumbnails"
            src={`/video/${recording.documentId}/thumbnails.vtt`}
          />
        </HlsVideo>

        <MediaPosterImage
          slot="poster"
          src={`/video/${recording.documentId}/screenshot.jpg`}
        />

        <MediaLoadingIndicator
          slot="centered-chrome"
          loadingdelay="0"
          style={{
            "--media-loading-indicator-transition-delay": "0ms",
          }}
        />

        <MediaControlBar>
          <MediaPlayButton />
          <MediaTimeRange />
          <MediaTimeDisplay showduration />
          <MediaSeekForwardButton seekoffset="10" />

          <div className="volume-hover-container">
            <MediaVolumeRange />
            <MediaMuteButton title="" />
          </div>
        </MediaControlBar>
      </MediaController>
    </>
  );
}
