"use client";

import { checkVideoAccess } from "@/app/actions/video-access";
import { useWatched } from "@/app/hooks/use-watched";
import { getImageUrl } from "@/app/lib/media-url";
import { configureHls } from "@/lib/configure-hls";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { Flex, Loader } from "@mantine/core";
import { useQuery } from "@tanstack/react-query";
import "hls-video-element";
import type { HlsVideoElement } from "hls-video-element";
import "media-chrome";
import "@player.style/yt";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { HlsVideo, MediaPosterImage } from "./media-chrome";

configureHls();

interface VideoPlayerProps {
  recording: Recording;
  defaultMuted?: boolean;
  onMuteChange?: (muted: boolean) => void;
  autoPlay?: boolean;
  onPlay?: () => void;
}

export function VideoPlayer({
  recording,
  defaultMuted = true,
  onMuteChange,
  autoPlay = false,
  onPlay,
}: VideoPlayerProps) {
  const searchParams = useSearchParams();
  const startTime = Number(searchParams.get("t")) || 0;

  const controllerRef = useRef<HTMLElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [initialAutoPlay] = useState(autoPlay);

  // Access check — sets the view_session cookie that playlist.m3u8
  // requires. Shared queryKey with parent pages so it dedupes.
  const { data: access, isPending: accessPending } = useQuery({
    queryKey: ["video-access", recording.documentId],
    queryFn: () => checkVideoAccess(recording.documentId!),
    enabled: !!recording.documentId,
    staleTime: 5 * 60 * 1000,
  });
  const canPlay = access?.allowed === true;

  // Destroy HLS on unmount (scroll away kills VideoPlayer via VideoSlide)
  useEffect(() => {
    const controller = controllerRef.current;
    return () => {
      if (!controller) return;
      const hlsEl = controller.querySelector(
        "hls-video",
      ) as HlsVideoElement | null;
      if (!hlsEl) return;

      hlsEl.pause();
      if (hlsEl.api) {
        hlsEl.api.stopLoad();
        hlsEl.api.detachMedia();
        hlsEl.api.destroy();
        hlsEl.api = null;
      }
    };
  }, [recording.documentId]);

  // Handle seek to start time
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !startTime) return;

    const handleLoaded = () => {
      video.currentTime = startTime;
    };

    video.addEventListener("loadedmetadata", handleLoaded, { once: true });

    return () => {
      video.removeEventListener("loadedmetadata", handleLoaded);
    };
  }, [startTime]);

  // Notify parent on first play (unlocks autoplay for subsequent videos)
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onPlay) return;

    const handlePlay = () => onPlay();
    video.addEventListener("play", handlePlay, { once: true });
    return () => video.removeEventListener("play", handlePlay);
  }, [onPlay]);

  // Mark recording as WATCHED in localStorage once it has actually been
  // playing for ~1.5s — this is what powers the WATCHED badge on
  // thumbnails. Previously it only fired on click; now scrolling through
  // a feed and watching a video also marks it.
  const { markWatched } = useWatched();
  useEffect(() => {
    const video = videoRef.current;
    const id = recording.documentId;
    if (!video || !id) return;

    let timer: ReturnType<typeof setTimeout> | null = null;
    const startTimer = () => {
      if (timer) return;
      timer = setTimeout(() => markWatched(id), 1500);
    };
    const stopTimer = () => {
      if (timer) {
        clearTimeout(timer);
        timer = null;
      }
    };

    video.addEventListener("playing", startTimer);
    video.addEventListener("pause", stopTimer);
    video.addEventListener("waiting", stopTimer);
    return () => {
      stopTimer();
      video.removeEventListener("playing", startTimer);
      video.removeEventListener("pause", stopTimer);
      video.removeEventListener("waiting", stopTimer);
    };
  }, [recording.documentId, markWatched]);

  // Swallow autoplay rejections. The browser rejects play() with
  // NotAllowedError when autoplay is blocked and AbortError when a pause()
  // races a pending play() (happens on rapid scroll). Neither is actionable.
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const tryPlay = () => {
      const p = video.play();
      if (p && typeof p.catch === "function") {
        p.catch((err: DOMException) => {
          if (err?.name === "NotAllowedError" && !video.muted) {
            // Retry muted — browsers always allow muted autoplay
            video.muted = true;
            video.play().catch(() => {});
          }
          // Otherwise silently drop (AbortError from scroll races etc.)
        });
      }
    };

    if (initialAutoPlay) {
      if (video.readyState >= 2) tryPlay();
      else video.addEventListener("loadeddata", tryPlay, { once: true });
    }

    return () => video.removeEventListener("loadeddata", tryPlay);
  }, [initialAutoPlay]);

  // Change seek offset to 10s and focus player on play
  useEffect(() => {
    const theme = controllerRef.current;
    if (!theme) return;

    const inject = () => {
      const shadow = theme.shadowRoot;
      if (!shadow) return;

      // Focus media-controller on play so arrow keys work
      const mc = shadow.querySelector("media-controller") as HTMLElement;
      const video = videoRef.current;
      if (mc && video) {
        const handlePlay = () => mc.focus();
        video.addEventListener("playing", handlePlay);
      }

      // Change seek offset from 30s to 10s
      shadow.querySelectorAll("media-seek-backward-button, media-seek-forward-button").forEach((btn) => {
        btn.setAttribute("seekoffset", "10");
      });
    };

    inject();
    const timer = setTimeout(inject, 500);
    return () => clearTimeout(timer);
  }, [recording.documentId]);

  // Track mute changes
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onMuteChange) return;

    const handleVolumeChange = () => {
      onMuteChange(video.muted);
    };

    video.addEventListener("volumechange", handleVolumeChange);
    return () => video.removeEventListener("volumechange", handleVolumeChange);
  }, [onMuteChange]);

  const handleDoubleClick = () => {
    const controller = controllerRef.current;
    if (!controller) return;

    if (document.fullscreenElement) {
      document.exitFullscreen();
    } else {
      const el = controller as HTMLElement & {
        webkitRequestFullscreen?: () => Promise<void>;
      };
      if (el.requestFullscreen) {
        el.requestFullscreen();
      } else if (el.webkitRequestFullscreen) {
        el.webkitRequestFullscreen();
      }
    }
  };

  if (accessPending) {
    return (
      <Flex w="100%" h="100%" justify="center" align="center">
        <Loader size="md" color="white" />
      </Flex>
    );
  }

  if (!canPlay) {
    // Parent components (modals, etc.) typically handle denial UI via
    // the same query key. Render nothing — don't load the playlist.
    return null;
  }

  return (
    <>
      {/* @ts-expect-error - web component */}
      <media-theme-yt
        ref={controllerRef}
        onDoubleClick={handleDoubleClick}
        style={{
          width: "100%",
          height: "100%",
        }}
      >
        <HlsVideo
          ref={videoRef}
          src={`/video/${recording.documentId}/playlist.m3u8`}
          slot="media"
          crossOrigin="anonymous"
          playsInline
          autoPlay={initialAutoPlay || undefined}
          preload={initialAutoPlay ? undefined : "none"}
          muted={defaultMuted}
        >
          {typeof window !== "undefined" &&
            window.matchMedia("(pointer: fine)").matches && (
              <track
                default
                kind="metadata"
                label="thumbnails"
                src={`/video/${recording.documentId}/thumbnails.vtt`}
              />
            )}
          <track
            default
            kind="chapters"
            src={`/video/${recording.documentId}/chapters.vtt`}
          />
        </HlsVideo>

        <MediaPosterImage
          slot="poster"
          src={getImageUrl(recording.documentId!, "screenshot.jpg", recording.sources?.at(-1))}
        />

      {/* @ts-expect-error - web component */}
      </media-theme-yt>
    </>
  );
}
