"use client";

import Link from "@/app/components/link";
import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { Button, Menu } from "@mantine/core";
import { IconChevronDown } from "@tabler/icons-react";
import { ReactNode } from "react";
import { FollowerTypeIcon } from "./follower-type-icon";

interface PlatformFilterMenuProps {
  /** Current platform type; "" / undefined = all platforms. */
  value?: string;
  /** Localized "All platforms" label (pass t("allPlatforms")). */
  allLabel: string;
  /** Live-page style: navigate via <Link href>. Receives "" for all. */
  buildHref?: (value: string) => string;
  /** Clips-page style: callback navigation (e.g. nuqs). Receives "" for all. */
  onSelect?: (value: string) => void;
}

/**
 * Shared platform dropdown (Menu + FollowerTypeIcon) used by the live page and
 * /my/clips so they stay visually identical. Supply EITHER buildHref (Link nav)
 * OR onSelect (callback nav).
 */
export function PlatformFilterMenu({
  value,
  allLabel,
  buildHref,
  onSelect,
}: PlatformFilterMenuProps) {
  const currentName = value
    ? streamingPlatforms.find((p) => p.name.toLowerCase() === value)?.name ||
      value
    : null;

  // Two explicit branches (not a spread) so Mantine's polymorphic Menu.Item
  // typing resolves: Link navigation for the live page, onClick for clips.
  const item = (v: string, label: string, icon?: ReactNode) =>
    buildHref ? (
      <Menu.Item
        key={label}
        component={Link}
        href={buildHref(v)}
        leftSection={icon}
      >
        {label}
      </Menu.Item>
    ) : (
      <Menu.Item key={label} onClick={() => onSelect?.(v)} leftSection={icon}>
        {label}
      </Menu.Item>
    );

  return (
    <Menu shadow="md">
      <Menu.Target>
        <Button variant="light" rightSection={<IconChevronDown size={16} />}>
          {currentName ?? allLabel}
        </Button>
      </Menu.Target>
      <Menu.Dropdown>
        {item("", allLabel)}
        {streamingPlatforms.map((platform) => {
          const key = platform.name.toLowerCase();
          return item(
            key,
            platform.name,
            <FollowerTypeIcon type={key as FollowerTypeEnum} size={20} />,
          );
        })}
      </Menu.Dropdown>
    </Menu>
  );
}
