"use client";

import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import {
  FollowerTypeEnum,
  Recording,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import { Anchor, Avatar, Box, Grid, Group, Stack, Text } from "@mantine/core";
import { IconDownload, IconEye } from "@tabler/icons-react";
import { useNow, useTranslations } from "next-intl";
import { useDateFormatter } from "../lib/use-date-formatter";

import Image from "next/image";
import Link from "@/app/components/link";
import { useRouter } from "next/navigation";
import { getMyProfileUrl } from "@/app/lib/profile-url";
import { ImageSpritePreview } from "./image-sprite-preview";
import { RecordingMenu } from "./recording-menu";

interface Props {
  recording: Recording;
  hideAvatar?: boolean;
}

export default function RecordingItem({ recording, hideAvatar = false }: Props) {
  const format = useDateFormatter();
  const now = useNow();
  const t = useTranslations("protected.common");
  const router = useRouter();
  const stop = (e: React.MouseEvent) => e.stopPropagation();

  const isRecording = recording.sources?.some(
    (s) =>
      s.state === SourceStateEnum.Recording ||
      s.state === SourceStateEnum.Uploading,
  );

  const dateLabel = isRecording
    ? t("recordings.liveAgo", {
        time: safeRelativeTime(format, recording.createdAt, {
          style: "narrow",
          now,
        }),
      })
    : format.dateTime(new Date(recording.createdAt || ""), {
        dateStyle: "medium",
        timeStyle: "short",
      });

  const videoHref = `${getMyProfileUrl(recording.follower)}/video/${recording.documentId}`;

  return (
    <Grid
      gap="xs"
      key={recording.documentId}
      w="100%"
      className="recording-card-hover"
      onClick={!isRecording ? () => router.push(videoHref) : undefined}
      style={{ cursor: !isRecording ? "pointer" : "default" }}
    >
      {recording.follower && (
        <Grid.Col span={12} onClick={stop}>
          <ImageSpritePreview
            username={recording.follower?.username || "unknown"}
            type={recording.follower?.type || FollowerTypeEnum.Tiktok}
            recording={recording}
          />
        </Grid.Col>
      )}
      <Grid.Col span={12}>
        <Group gap="xs" align="flex-start" justify="space-between" wrap="nowrap">
          {!hideAvatar && (
            <Anchor
              component={Link}
              prefetch={false}
              href={getMyProfileUrl(recording.follower)}
              onClick={stop}
            >
              <Avatar size={38}>
                {recording.follower?.avatar?.url && (
                  <Image
                    src={generateAvatarUrl(recording.follower?.avatar)}
                    alt={"Avatar"}
                    width={38}
                    height={38}
                  />
                )}
              </Avatar>
            </Anchor>
          )}
          <Stack gap={0} style={{ flex: 1, minWidth: 0 }}>
            {recording.title && (
              <Text fw={500} size="md" lineClamp={2} c="white">
                {recording.title}
              </Text>
            )}
            {!hideAvatar && (
              <Anchor
                component={Link}
                prefetch={false}
                href={getMyProfileUrl(recording.follower)}
                size="sm"
                truncate
                c={recording.title ? "dimmed" : undefined}
                onClick={stop}
                style={{ alignSelf: "flex-start" }}
              >
                {decodeURIComponent(recording.follower?.username || "")}
              </Anchor>
            )}
            <Group gap={6} c="dimmed">
              <Group gap={3}>
                <IconEye size={12} />
                <Text size="xs">{recording.viewsCount ?? 0}</Text>
              </Group>
              <Text size="xs">·</Text>
              <Group gap={3}>
                <IconDownload size={12} />
                <Text size="xs">{recording.downloadsCount ?? 0}</Text>
              </Group>
              <Text size="xs">·</Text>
              <Text size="xs" suppressHydrationWarning>
                {dateLabel}
              </Text>
            </Group>
          </Stack>
          {!isRecording && (
            <Box onClick={stop}>
              <RecordingMenu
                recording={recording}
                username={recording.follower?.username}
                type={recording.follower?.type}
              />
            </Box>
          )}
        </Group>
      </Grid.Col>
    </Grid>
  );
}
