export const dynamic = "force-dynamic";

import { getToken } from "@/lib/token";
import { Api } from "@/lib/types/strapi-autogenerated";
import qs from "qs";

const api = new Api({
  baseURL:
    (process.env.NEXT_PUBLIC_STRAPI_URL || "http://localhost:1337") + "/api",
  paramsSerializer: {
    serialize: (params) => qs.stringify(params, { encodeValuesOnly: true }),
  },
  securityWorker: async () => {
    const token = await getToken();
    if (token) {
      return {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      };
    }
    return {};
  },
});

api.instance.interceptors.request.use((config) => {
  console.log("REQUEST URL:", config.baseURL + ":" + config.url);
  console.log("PARAMS:", config.params);
  console.log("FULL URL:", api.instance.getUri(config));
  return config;
});

export default api;
