"use client";

import dayjs from "@/app/lib/dayjs";
import { Article } from "@/lib/types/strapi-autogenerated";
import { Flex, Paper, Stack, Text, Title } from "@mantine/core";
import {
  IconBulb,
  IconInfoCircle,
  IconNews,
  IconRocket,
  IconTools,
} from "@tabler/icons-react";
import { marked } from "marked";

const iconMap = {
  teal: IconTools,
  blue: IconInfoCircle,
  green: IconRocket,
  yellow: IconBulb,
  default: IconNews,
};

const colorMap: Record<string, { bg: string; border: string; icon: string }> = {
  teal: {
    bg: "rgba(20, 184, 166, 0.1)",
    border: "rgba(20, 184, 166, 0.2)",
    icon: "#14b8a6",
  },
  blue: {
    bg: "rgba(59, 130, 246, 0.1)",
    border: "rgba(59, 130, 246, 0.2)",
    icon: "#3b82f6",
  },
  green: {
    bg: "rgba(16, 185, 129, 0.1)",
    border: "rgba(16, 185, 129, 0.2)",
    icon: "#10b981",
  },
  yellow: {
    bg: "rgba(234, 179, 8, 0.1)",
    border: "rgba(234, 179, 8, 0.2)",
    icon: "#eab308",
  },
  default: {
    bg: "rgba(255, 255, 255, 0.02)",
    border: "rgba(255, 255, 255, 0.06)",
    icon: "#64748b",
  },
};

export function NewsList({ articles }: { articles: Article[] }) {
  return (
    <Stack gap="md">
      {articles.map((article) => {
        const colorKey = article.color || "default";
        const Icon =
          iconMap[colorKey as keyof typeof iconMap] || iconMap.default;
        const colors = colorMap[colorKey] || colorMap.default;

        return (
          <Paper
            key={article.documentId}
            p="lg"
            radius="lg"
            style={{
              background: colors.bg,
              border: `1px solid ${colors.border}`,
            }}
          >
            <Flex gap={12} align="flex-start">
              <div
                style={{
                  width: 40,
                  height: 40,
                  borderRadius: 10,
                  background: colors.border,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: colors.icon,
                  flexShrink: 0,
                }}
              >
                <Icon size={20} />
              </div>
              <div style={{ flex: 1 }}>
                <Title order={4} mb="xs" style={{ color: "#f1f5f9" }}>
                  {article.title}
                </Title>
                {article.content && (
                  <div
                    style={{
                      color: "#94a3b8",
                      lineHeight: 1.7,
                    }}
                    dangerouslySetInnerHTML={{
                      __html: marked.parse(article.content) as string,
                    }}
                  />
                )}
                <Text size="xs" mt="sm" style={{ color: "#64748b" }}>
                  {dayjs(article.createdAt).fromNow()}
                </Text>
              </div>
            </Flex>
          </Paper>
        );
      })}
    </Stack>
  );
}
