"use server";

import api from "@/lib/api";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { deepMerge } from "@mantine/core";
import { ProfileFilters } from "../lib/search-params";

const defaultOptions = {
  filters: {
    // give me all recordings that are done or recording
    sources: {
      state: {
        $in: ["done", "recording"],
      },
    },
  },
  populate: {
    sources: {
      fields: ["*"],
      filters: {
        // filter out from source
        state: {
          $ne: "failed",
        },
      },
      populate: ["videoSmall", "videoOriginal"], // we ask for original because sometime small is null while encoding for mini-player
    },
    follower: {
      fields: ["username", "type"],
      populate: {
        avatar: {
          fields: ["url"],
        },
      },
    },
  },
};

export async function getFollower({
  username,
  type,
}: {
  username: string;
  type: string;
}) {
  const response = await api.follower.getFollowers({
    filters: {
      username: decodeURIComponent(username).replace("@", ""),
      type,
    },
    populate: ["avatar"],
  });

  const follower = response.data.data?.at(0);

  if (!follower) {
    return null;
  }

  // Check if current user is following
  const user =
    await api.usersPermissionsUsersRoles.getUsersPermissionsUsersRoles({
      populate: {
        followers: {
          fields: ["id"],
          filters: {
            documentId: {
              $eq: follower.documentId,
            },
          },
        },
      },
    });

  const followers: Follower[] = (user.data as any).followers;
  const isFollowing = !!followers.find((f) => f.id === follower.id);

  return {
    ...follower,
    isFollowing,
  };
}

export async function fetchProfileRecordings(
  type: string,
  username: string,
  filters: ProfileFilters,
  page: number = 1
) {
  const response = await api.recording.browseRecordings(
    deepMerge(defaultOptions, {
      filters: {
        follower: {
          username: { $eq: decodeURIComponent(username).replace("@", "") },
          type: { $eq: type },
        },
      },
      sort: filters.sort,
      "pagination[page]": page,
      "pagination[pageSize]": 15,
    })
  );

  return {
    data: response.data?.data || [],
    meta: response.data?.meta,
  };
}
