import { getProfileUrl } from "@/app/components/open-social";
import { getImageUrl } from "@/app/lib/media-url";
import { generateProfileUrl } from "@/app/lib/profile-url";
import { generateAlternates } from "@/app/lib/seo";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Container,
  Flex,
  SimpleGrid,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconArrowLeft, IconArrowRight } from "@tabler/icons-react";
import { Metadata } from "next";
import {
  getFormatter,
  getTranslations,
  setRequestLocale,
} from "next-intl/server";
import { redirect } from "next/navigation";
import {
  fetchProfileRecordings,
  getRecordingById,
} from "../../actions/actions";
import { ImageVideoPreview } from "../../components/image-video-preview";
import { SignupCta } from "../../components/signup-cta";
import { VideoPlayer } from "../../components/video-player";
import { LinkButton } from "@/app/components/link-button";

interface PageProps {
  params: Promise<{
    locale: string;
    username: string;
    type: FollowerTypeEnum;
    id: string;
  }>;
}

export const dynamic = "force-dynamic";
export async function generateStaticParams() {
  return [];
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { locale, id, username, type } = await params;
  setRequestLocale(locale);
  const t = await getTranslations({ locale, namespace: "video" });
  const data = await getRecordingById(id);

  if (!data) {
    return {};
  }

  const format = await getFormatter();

  const platformName = type.charAt(0).toUpperCase() + type.slice(1);
  const creatorName = decodeURIComponent(data.follower?.username || "unknown");
  const recordedDate = format.dateTime(new Date(data.createdAt || ""), {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  const sources = data.sources ?? [];
  const lastSource = sources.at(-1);
  const thumbnailUrl = getImageUrl(data.documentId!, "screenshot.jpg", lastSource);

  const duration = sources.reduce(
    (acc, source) => acc + (source.duration || 0),
    0,
  );
  const durationFormatted = `${Math.floor(duration / 60)}m ${Math.round(
    duration % 60,
  )}s`;

  const translation = {
    creatorName,
    recordedDate,
    platform: platformName,
    duration: durationFormatted,
    username,
  };

  const metaTitle = data.title
    ? `${data.title} — ${creatorName}`
    : t("meta.title", translation);
  const metaDescription = data.description || t("meta.description", translation);

  return {
    title: metaTitle,
    description: metaDescription,
    keywords: t("meta.keywords", translation).split(", "),
    openGraph: {
      title: metaTitle,
      description: metaDescription,
      type: "video.other",
      url: generateProfileUrl(data.follower, true) + `/video/${id}`,
      siteName: "Live Stream Recorder",
      ...(thumbnailUrl && {
        images: [
          {
            url: thumbnailUrl,
            width: 1280,
            height: 720,
            alt: data.title || `${creatorName} stream thumbnail`,
          },
        ],
        videos: [
          {
            url: `${generateProfileUrl(data.follower, true)}/video/${id}`,
            width: 1280,
            height: 720,
            type: "text/html",
          },
        ],
      }),
    },
    twitter: {
      card: "summary_large_image",
      title: metaTitle,
      description: metaDescription,
      ...(thumbnailUrl && {
        images: [thumbnailUrl],
      }),
    },
    alternates: generateAlternates(`/${type}/${username}/video/${id}`, locale),
  };
}

export default async function VideoPage({ params }: PageProps) {
  const { locale, id, type, username } = await params;
  setRequestLocale(locale);
  const tp = await getTranslations({ locale, namespace: "profile" });
  const t = await getTranslations({ locale, namespace: "video" });
  const data = await getRecordingById(id);

  if (!data) {
    return redirect(getProfileUrl({ type, username }));
  }

  const format = await getFormatter();
  const sources = data.sources ?? [];

  const { data: recordingsData } = await fetchProfileRecordings(type, username);
  const recordings = recordingsData ?? [];
  const hasRecordings = recordings.length > 0;

  const previewUrl = getImageUrl(data.documentId!, "screenshot.jpg", sources.at(-1));

  const duration = sources.reduce(
    (acc, source) => acc + (source.duration || 0),
    0,
  );

  const creatorName = decodeURIComponent(data.follower?.username || "Unknown");
  const recordedDate = format.dateTime(new Date(data.createdAt || ""), {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;
  const profileUrl = generateProfileUrl(data.follower, true);
  const platformName = type.charAt(0).toUpperCase() + type.slice(1);
  const videoUrl = `${profileUrl}/video/${data.documentId}`;

  const videoJsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            item: {
              "@id": baseUrl,
              name: "Home",
            },
          },
          {
            "@type": "ListItem",
            position: 2,
            item: {
              "@id": `${baseUrl}/creators/${type}`,
              name: `${platformName} Creators`,
            },
          },
          {
            "@type": "ListItem",
            position: 3,
            item: {
              "@id": profileUrl,
              name: creatorName,
            },
          },
          {
            "@type": "ListItem",
            position: 4,
            item: {
              "@id": videoUrl,
              name: data.title || t("jsonLd.name", { creatorName, recordedDate }),
            },
          },
        ],
      },
      {
        "@type": "VideoObject",
        name: data.title || t("jsonLd.name", { creatorName, recordedDate }),
        description: data.description || t("jsonLd.description", { creatorName, recordedDate }),
        thumbnailUrl: getImageUrl(data.documentId!, "screenshot.jpg", sources.at(-1)),
        uploadDate: data.createdAt,
        duration: `PT${Math.floor(duration / 60)}M${Math.round(duration % 60)}S`,
        contentUrl: `${baseUrl}/video/${data.documentId}/playlist.m3u8`,
        embedUrl: videoUrl,
        publisher: {
          "@type": "Organization",
          name: "Live Stream Recorder",
          url: baseUrl,
        },
        ...(data.follower && {
          author: {
            "@type": "Person",
            name: creatorName,
            identifier: creatorName,
            alternateName: [data.follower?.nickname, `@${creatorName}`].filter(
              Boolean,
            ),
            url: profileUrl,
          },
        }),
        inLanguage: locale,
        potentialAction: {
          "@type": "WatchAction",
          target: videoUrl,
        },
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(videoJsonLd) }}
      />
      <Container size="xl">
        <Flex gap="xs" justify="center" align="center" direction="column">
          <VideoPlayer
            documentId={data.documentId!}
            previewUrl={previewUrl}
            src={`/video/${data.documentId}/playlist.m3u8`}
            thumbnailsUrl={`/video/${data.documentId}/thumbnails.vtt`}
          />

          {data.title ? (
            <Stack gap={4} align="center">
              <Title order={1} size="xl" fw={600}>
                {data.title}
              </Title>
              <Text size="sm" c="dimmed" ta="center">
                {t("watch.title", { username: creatorName, date: recordedDate })}
              </Text>
              {data.description && (
                <Text size="sm" c="dimmed" ta="center" maw={700} mt="xs">
                  {data.description}
                </Text>
              )}
            </Stack>
          ) : (
            <Title order={1} c="dimmed" size="xl" fw="400">
              {t("watch.title", { username: creatorName, date: recordedDate })}
            </Title>
          )}

          <LinkButton href={generateProfileUrl(data.follower)}
            variant="light"
            leftSection={
              locale === "ar" ? (
                <IconArrowRight size={16} />
              ) : (
                <IconArrowLeft size={16} />
              )
            }
          >
            {t("backToProfile", { username: creatorName })}
          </LinkButton>
        </Flex>
        {hasRecordings ? (
          <Stack mt={100}>
            <Title order={2} size="lg" ta="center" fw="400">
              {t("otherRecordingsBy", { username: creatorName })}
            </Title>
            <SimpleGrid cols={{ base: 1, sm: 2 }} spacing="lg">
              {recordings?.map((rec) => (
                <Stack key={rec.documentId} gap={4}>
                  <ImageVideoPreview
                    recording={rec}
                    type={type as unknown as FollowerTypeEnum}
                  />
                  {rec.title && (
                    <Text fw={600} size="sm" lineClamp={2} style={{ lineHeight: 1.3 }}>
                      {rec.title}
                    </Text>
                  )}
                  <Text size="xs" c="dimmed" suppressHydrationWarning>
                    {tp("recorded", {
                      date: format.dateTime(new Date(rec.createdAt || ""), {
                        year: "numeric",
                        month: "short",
                        day: "numeric",
                        hour: "numeric",
                        minute: "2-digit",
                      }),
                    })}
                  </Text>
                </Stack>
              ))}
              <SignupCta username={creatorName} recordings={recordings} />
            </SimpleGrid>
          </Stack>
        ) : null}
      </Container>
    </>
  );
}
