"use client";

import { resetClipCounters } from "@/app/actions/clip";
import { useUser } from "@/app/providers/user-provider";
import { Clip } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Menu, Text } from "@mantine/core";
import { modals } from "@mantine/modals";
import { notifications } from "@mantine/notifications";
import {
  IconDots,
  IconFlag,
  IconRefresh,
  IconTrash,
} from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ReportModal } from "../../components/report-modal";
import { deleteClip } from "../actions/delete-clip";

interface ClipMenuProps {
  clip: Clip;
}

export function ClipMenu({ clip }: ClipMenuProps) {
  const user = useUser();
  const t = useTranslations("protected.clips.menu");
  const router = useRouter();
  const [reportOpened, setReportOpened] = useState(false);

  const isLoggedIn = !!user?.id;
  const isAdmin =
    user?.role?.type === "admin" || user?.role?.type === "moderator";
  const isOwner = user?.id && clip.follower?.owner?.id === user.id;

  if (!isLoggedIn) return null;

  const handleDelete = () => {
    modals.openConfirmModal({
      title: t("deleteTitle"),
      children: <Text size="sm">{t("deleteConfirm")}</Text>,
      labels: { confirm: t("deleteButton"), cancel: t("cancel") },
      confirmProps: { color: "red" },
      onConfirm: async () => {
        const result = await deleteClip(clip.documentId!);
        if (result.success) {
          notifications.show({
            title: t("deleteSuccess"),
            message: "",
            color: "green",
          });
          router.refresh();
        } else {
          notifications.show({
            title: t("deleteError"),
            message: result.error || "",
            color: "red",
          });
        }
      },
    });
  };

  const handleResetCounters = () => {
    if (!clip.documentId) return;
    modals.openConfirmModal({
      title: t("resetCountersConfirm.title"),
      children: <Text size="sm">{t("resetCountersConfirm.message")}</Text>,
      labels: {
        confirm: t("resetCountersConfirm.confirm"),
        cancel: t("resetCountersConfirm.cancel"),
      },
      confirmProps: { color: "orange" },
      onConfirm: async () => {
        const result = await resetClipCounters(clip.documentId!);
        if (result.success) {
          notifications.show({
            title: t("resetCountersSuccess"),
            message: null,
            color: "green",
          });
          router.refresh();
        } else {
          notifications.show({
            title: t("resetCountersFailed"),
            message: result.error ?? null,
            color: "red",
          });
        }
      },
    });
  };

  return (
    <>
      <Menu position="bottom-end" withArrow>
        <Menu.Target>
          <ActionIcon variant="subtle" color="gray" size="sm">
            <IconDots size={16} />
          </ActionIcon>
        </Menu.Target>
        <Menu.Dropdown>
          <Menu.Item
            leftSection={<IconFlag size={16} />}
            onClick={() => setReportOpened(true)}
          >
            {t("report")}
          </Menu.Item>

          {isAdmin && (
            <Menu.Item
              color="orange"
              leftSection={<IconRefresh size={16} />}
              onClick={handleResetCounters}
            >
              {t("resetCounters")}
            </Menu.Item>
          )}

          {(isAdmin || isOwner) && (
            <Menu.Item
              color="red"
              leftSection={<IconTrash size={16} />}
              onClick={handleDelete}
            >
              {t("delete")}
            </Menu.Item>
          )}
        </Menu.Dropdown>
      </Menu>

      {clip.documentId && (
        <ReportModal
          entity="clip"
          documentId={clip.documentId}
          opened={reportOpened}
          onClose={() => setReportOpened(false)}
        />
      )}
    </>
  );
}
