"use client";

import { useUser } from "@/app/providers/user-provider";
import { Clip } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Menu, Text } from "@mantine/core";
import { modals } from "@mantine/modals";
import { notifications } from "@mantine/notifications";
import { IconDots, IconTrash } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { deleteClip } from "../actions/delete-clip";

interface ClipMenuProps {
  clip: Clip;
}

export function ClipMenu({ clip }: ClipMenuProps) {
  const user = useUser();
  const t = useTranslations("protected.clips.menu");
  const router = useRouter();

  const isAdmin =
    user?.role?.type === "admin" || user?.role?.type === "moderator";
  const isOwner = user?.id && clip.follower?.owner?.id === user.id;

  if (!isAdmin && !isOwner) return null;

  const handleDelete = () => {
    modals.openConfirmModal({
      title: t("deleteTitle"),
      children: <Text size="sm">{t("deleteConfirm")}</Text>,
      labels: { confirm: t("deleteButton"), cancel: t("cancel") },
      confirmProps: { color: "red" },
      onConfirm: async () => {
        const result = await deleteClip(clip.documentId!);
        if (result.success) {
          notifications.show({
            title: t("deleteSuccess"),
            message: "",
            color: "green",
          });
          router.refresh();
        } else {
          notifications.show({
            title: t("deleteError"),
            message: result.error || "",
            color: "red",
          });
        }
      },
    });
  };

  return (
    <Menu position="bottom-end" withArrow>
      <Menu.Target>
        <ActionIcon variant="subtle" color="gray" size="sm">
          <IconDots size={16} />
        </ActionIcon>
      </Menu.Target>
      <Menu.Dropdown>
        <Menu.Item
          color="red"
          leftSection={<IconTrash size={16} />}
          onClick={handleDelete}
        >
          {t("delete")}
        </Menu.Item>
      </Menu.Dropdown>
    </Menu>
  );
}
