"use client";

import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { Button, Menu } from "@mantine/core";
import { IconChevronDown } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { parseAsInteger, useQueryState, useQueryStates } from "nuqs";
import { FollowerTypeIcon } from "../../components/follower-type-icon";
import { clipsParsers } from "../lib/search-params";

/**
 * Platform filter for /my/clips — same icon dropdown style as the live page
 * (Menu + FollowerTypeIcon). Filters clips by the linked follower.type.
 * "" = all platforms; selecting a platform resets pagination and preserves sort.
 */
export function ClipsPlatform() {
  const t = useTranslations("protected.filters.platforms");
  const [filters, setFilters] = useQueryStates(clipsParsers);
  const [, setPage] = useQueryState("page", parseAsInteger);

  const select = (value: string) => {
    setPage(null);
    setFilters({ type: value }, { shallow: false });
  };

  const current = streamingPlatforms.find(
    (p) => p.name.toLowerCase() === filters.type,
  );

  return (
    <Menu shadow="md" width={220}>
      <Menu.Target>
        <Button
          variant="light"
          size="md"
          leftSection={
            current ? (
              <FollowerTypeIcon
                type={filters.type as FollowerTypeEnum}
                size={20}
              />
            ) : undefined
          }
          rightSection={<IconChevronDown size={16} />}
        >
          {current ? current.name : t("all")}
        </Button>
      </Menu.Target>
      <Menu.Dropdown>
        <Menu.Item onClick={() => select("")}>{t("all")}</Menu.Item>
        {streamingPlatforms.map((platform) => {
          const key = platform.name.toLowerCase();
          return (
            <Menu.Item
              key={platform.name}
              onClick={() => select(key)}
              leftSection={
                <FollowerTypeIcon type={key as FollowerTypeEnum} size={20} />
              }
            >
              {platform.name}
            </Menu.Item>
          );
        })}
      </Menu.Dropdown>
    </Menu>
  );
}
