// app/(protected)/creators/@modal/(..)[type]/[username]/[status]/[id]/page.tsx
"use client";

import { Flex, Loader, Modal } from "@mantine/core";
import { useInfiniteQuery } from "@tanstack/react-query";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useCallback } from "react";

import { VideoScrollPlayer } from "@/app/[locale]/(protected)/components/video/video-scroll-player";

import { getRecordings } from "@/app/[locale]/(protected)/my-list/actions/fetch-followers";
import { Recording } from "@/lib/types/strapi-autogenerated";

export default function CreatorRecordingModal() {
  const router = useRouter();
  const params = useParams<{
    id: string;
    username: string;
    type: string;
  }>();
  const searchParams = useSearchParams();

  const { data, fetchNextPage, hasNextPage, isFetchingNextPage, isLoading } =
    useInfiniteQuery({
      queryKey: ["recordings", params.username, params.type],
      queryFn: ({ pageParam }) =>
        getRecordings(params.username, params.type, pageParam),
      initialPageParam: 1,
      getNextPageParam: (lastPage) => {
        const { page = 1, pageCount = 0 } = lastPage.meta?.pagination ?? {};
        return page < pageCount ? page + 1 : undefined;
      },
    });

  const recordings = data?.pages.flatMap((p) => p.data) ?? [];

  const handleClose = () => {
    router.back();
  };

  const handleVisibleChange = useCallback(
    (recording: Recording) => {
      const basePath = `/${recording.follower?.type}/${recording.follower?.username}/video/${recording.documentId}`;
      const search = searchParams.toString();
      const url = search ? `${basePath}?${search}` : basePath;
      window.history.replaceState(null, "", url);
    },
    [searchParams]
  );

  const handleNotFound = () => {
    router.replace("/discover");
  };

  if (isLoading) {
    return (
      <Modal.Root opened={true} onClose={handleClose} fullScreen>
        <Modal.Content>
          <Flex h="100dvh" justify="center" align="center">
            <Loader size="lg" />
          </Flex>
        </Modal.Content>
      </Modal.Root>
    );
  }

  return (
    <Modal.Root
      opened={true}
      onClose={handleClose}
      fullScreen
      styles={{
        body: { height: "100%", padding: 0, overflow: "hidden" },
        content: { overflow: "hidden" },
      }}
    >
      <Modal.Content>
        <Modal.Body p={0} h="100%">
          <VideoScrollPlayer
            recordings={recordings}
            initialId={params.id}
            hasNextPage={hasNextPage}
            isFetchingNextPage={isFetchingNextPage}
            onFetchNextPage={fetchNextPage}
            onVisibleChange={handleVisibleChange}
            onClose={handleClose}
            onNotFound={handleNotFound}
          />
        </Modal.Body>
      </Modal.Content>
    </Modal.Root>
  );
}
