"use client";

import {
  HlsVideo,
  MediaControlBar,
  MediaController,
  MediaLoadingIndicator,
  MediaMuteButton,
  MediaPlayButton,
  MediaSeekBackwardButton,
  MediaSeekForwardButton,
  MediaTimeDisplay,
  MediaTimeRange,
  MediaVolumeRange,
} from "@/app/[locale]/(protected)/components/video/media-chrome";

import { useUser } from "@/app/providers/user-provider";
import { Recording } from "@/lib/types/strapi-autogenerated";
import {
  Box,
  Button,
  Card,
  Flex,
  Group,
  RangeSlider,
  Title,
} from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconCut, IconDownload } from "@tabler/icons-react";
import "hls-video-element";
import "media-chrome";
import { useLocale } from "next-intl";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import {
  cropDownloadVideo,
  cropExportVideo,
} from "../../../actions/edit-video";

interface Props {
  recording: Recording;
}

function formatTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0)
    return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}

export default function VideoEditor({ recording }: Props) {
  const user = useUser();
  const locale = useLocale();
  const videoRef = useRef<HTMLVideoElement>(null);
  const timeRangeRef = useRef<HTMLElement>(null);
  const timeDisplayRef = useRef<HTMLElement>(null);

  const [duration, setDuration] = useState(0);
  const [startTime, setStartTime] = useState(0);
  const [endTime, setEndTime] = useState(0);
  const [clipCurrentTime, setClipCurrentTime] = useState(0);
  const [isExporting, setIsExporting] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const clipDuration = endTime - startTime;

  // Stable refs so event listeners don't need re-registration when values change
  const startTimeRef = useRef(startTime);
  const clipDurationRef = useRef(clipDuration);
  useEffect(() => {
    startTimeRef.current = startTime;
  }, [startTime]);
  useEffect(() => {
    clipDurationRef.current = clipDuration;
  }, [clipDuration]);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const handleMetadata = () => {
      const dur = Math.floor(video.duration || 0);
      setDuration(dur);
      setEndTime(dur);
    };
    video.addEventListener("loadedmetadata", handleMetadata, { once: true });
    return () => video.removeEventListener("loadedmetadata", handleMetadata);
  }, []);

  // Always enforce clip boundaries and track clip-relative time
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const handleTimeUpdate = () => {
      if (video.currentTime < startTime) {
        video.currentTime = startTime;
        return;
      }
      if (video.currentTime >= endTime && endTime > 0) {
        video.pause();
        video.currentTime = startTime;
        setClipCurrentTime(0);
        return;
      }
      setClipCurrentTime(video.currentTime - startTime);
    };

    video.addEventListener("timeupdate", handleTimeUpdate);
    return () => video.removeEventListener("timeupdate", handleTimeUpdate);
  }, [startTime, endTime]);

  // MediaTimeRange is OUTSIDE the MediaController so the controller can never push
  // its own mediacurrenttime/mediaduration onto it. Our useLayoutEffect is the sole writer.
  // We still intercept mediaseekrequest here and translate to absolute video time.
  useEffect(() => {
    const el = timeRangeRef.current;
    if (!el) return;

    const handleSeekRequest = (e: Event) => {
      e.stopPropagation();
      e.preventDefault();
      const video = videoRef.current;

      if (!video) return;

      const seekTo = (e as CustomEvent).detail as number;
      if (!isFinite(seekTo)) return;
      const clamped = Math.max(0, Math.min(clipDurationRef.current, seekTo));
      video.currentTime = startTimeRef.current + clamped;
      // Immediately sync state so useLayoutEffect writes the new position
      // before timeupdate fires — prevents visual snap-back to old position
      setClipCurrentTime(clamped);
    };

    el.addEventListener("mediaseekrequest", handleSeekRequest);
    return () => el.removeEventListener("mediaseekrequest", handleSeekRequest);
  }, []);

  // After every render, push clip-relative values onto the detached time elements.
  // Since they're outside the MediaController, nothing races against these writes.
  useLayoutEffect(() => {
    const tr = timeRangeRef.current as HTMLElement;
    const td = timeDisplayRef.current as HTMLElement;
    if (tr) {
      tr.setAttribute("mediacurrenttime", String(clipCurrentTime));
      tr.setAttribute("mediaduration", String(clipDuration));
      tr.setAttribute("mediaseekable", `0:${clipDuration}`);
    }
    if (td) {
      td.setAttribute("mediacurrenttime", String(clipCurrentTime));
      td.setAttribute("mediaduration", String(clipDuration));
    }
  });

  // When clip range changes, seek to new startTime
  const handleRangeChangeEnd = (value: [number, number]) => {
    const video = videoRef.current;
    if (!video) return;
    video.currentTime = value[0];
    setClipCurrentTime(0);
  };

  const handleRangeChange = (value: [number, number]) => {
    setStartTime(value[0]);
    setEndTime(value[1]);
  };

  const handleExport = async () => {
    if (!user?.id || !recording.documentId || clipDuration <= 0) return;
    setIsExporting(true);
    try {
      await cropExportVideo(recording.documentId, user.id, startTime, endTime);
      notifications.show({
        title: "Export started",
        message:
          "Your clip is being processed and will be saved to your storage",
        color: "green",
      });
    } finally {
      setIsExporting(false);
    }
  };

  const handleDownload = async () => {
    if (!user?.id || !recording.documentId || clipDuration <= 0) return;
    setIsDownloading(true);
    try {
      await cropDownloadVideo(
        recording.documentId,
        user.id,
        locale,
        startTime,
        endTime,
      );
      notifications.show({
        title: "Download queued",
        message: "Your clip will be emailed to you when ready",
        color: "green",
      });
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <>
      <Box
        style={{
          width: "100%",
          height: "55vh",
          borderRadius: "var(--mantine-radius-md)",
          overflow: "hidden",
          background: "#000",
        }}
      >
        <style>{`
          media-controller:not([mediapaused]) media-play-button[slot="centered-chrome"] { display: none !important; }
          media-controller[mediapaused] media-loading-indicator[slot="centered-chrome"] { display: none !important; }
        `}</style>
        <MediaController
          style={{ width: "100%", height: "100%", background: "#000" }}
        >
          <HlsVideo
            ref={videoRef}
            src={`/video/${recording.documentId}/playlist.m3u8`}
            slot="media"
            playsInline
          >
            <track
              default
              kind="metadata"
              label="thumbnails"
              src={`/video/${recording.documentId}/thumbnails.vtt`}
            />
          </HlsVideo>
          <MediaPlayButton slot="centered-chrome" />
          <MediaLoadingIndicator slot="centered-chrome" />
          <MediaControlBar>
            <MediaPlayButton />
            <MediaSeekBackwardButton seekoffset="10" />
            <MediaSeekForwardButton seekoffset="10" />
            <MediaTimeRange ref={timeRangeRef} mediacontroller="__clip__" />
            <MediaTimeDisplay
              showduration
              ref={timeDisplayRef}
              mediacontroller="__clip__"
            />
            <div className="volume-hover-container">
              <MediaVolumeRange />
              <MediaMuteButton title="" />
            </div>
          </MediaControlBar>
        </MediaController>
      </Box>

      {/* Clip Range */}
      <Card withBorder p="md">
        <Group justify="space-between">
          <Title order={4}>Select your clip range</Title>
          {clipDuration > 0 && (
            <Title order={4}>Duration: {formatTime(clipDuration)}</Title>
          )}
        </Group>

        <RangeSlider
          my={40}
          min={0}
          max={duration || 100}
          size="xl"
          step={1}
          labelAlwaysOn
          value={[startTime, endTime]}
          onChange={handleRangeChange}
          onChangeEnd={handleRangeChangeEnd}
          disabled={duration === 0}
          label={formatTime}
        />

        <Flex gap="sm">
          <Button
            flex={1}
            size="lg"
            radius="md"
            variant="light"
            leftSection={<IconCut />}
            onClick={handleExport}
            loading={isExporting}
            disabled={clipDuration <= 0}
          >
            Export
          </Button>
          <Button
            flex={1}
            size="lg"
            radius="md"
            leftSection={<IconDownload />}
            onClick={handleDownload}
            loading={isDownloading}
            disabled={clipDuration <= 0}
          >
            Download clip
          </Button>
        </Flex>
      </Card>
    </>
  );
}
