import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ThemeIcon, ThemeIconProps } from "@mantine/core";
import {
  IconAlphabetKorean,
  IconBrandFunimation,
  IconBrandKick,
  IconBrandTiktok,
  IconBrandTwitch,
  IconBrandYoutube,
} from "@tabler/icons-react";

type FollowerTypeIcon = {
  type: FollowerTypeEnum | undefined;
} & ThemeIconProps;

export const FollowerTypeIcon = ({ type, ...props }: FollowerTypeIcon) => {
  return (
    <ThemeIcon {...props}>
      {type === FollowerTypeEnum.Tiktok && (
        <IconBrandTiktok
          color="pink"
          stroke={1.5}
          style={{ width: "90%", height: "90%" }}
        />
      )}
      {type === FollowerTypeEnum.Twitch && (
        <IconBrandTwitch
          color="purple"
          stroke={1.5}
          style={{ width: "90%", height: "90%" }}
        />
      )}
      {type === FollowerTypeEnum.Kick && (
        <IconBrandKick
          color="red"
          stroke={1.5}
          style={{ width: "90%", height: "90%" }}
        />
      )}
      {type === FollowerTypeEnum.Youtube && (
        <IconBrandYoutube
          color="red"
          stroke={1.5}
          style={{ width: "90%", height: "90%" }}
        />
      )}
      {type === FollowerTypeEnum.Afreecatv && (
        <IconAlphabetKorean
          color="blue"
          stroke={1.5}
          style={{ width: "90%", height: "90%" }}
        />
      )}
      {type === FollowerTypeEnum.Pandalive && (
        <IconBrandFunimation
          color="blue"
          stroke={1.5}
          style={{ width: "90%", height: "90%" }}
        />
      )}
    </ThemeIcon>
  );
};
