import { Follower, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Tooltip } from "@mantine/core";
import { IconWindowMaximize } from "@tabler/icons-react";

export const SOCIAL_URL_PATTERNS: Record<
  FollowerTypeEnum,
  (username: string) => string
> = {
  [FollowerTypeEnum.Tiktok]: (username) =>
    `https://www.tiktok.com/@${decodeURIComponent(username).replace(
      /^@/,
      ""
    )}/video`,
  [FollowerTypeEnum.Twitch]: (username) => `https://www.twitch.tv/${username}`,
};

export const URL_PATTERNS: Record<
  FollowerTypeEnum,
  (username: string) => string
> = {
  [FollowerTypeEnum.Tiktok]: (username) => `/tiktok/@${username}`,
  [FollowerTypeEnum.Twitch]: (username) => `/twitch/${username}`,
};

export const getSocialUrl = (username: string, type: FollowerTypeEnum) => {
  const patternFn = SOCIAL_URL_PATTERNS[type];
  return patternFn ? patternFn(username) : "/404";
};

export const getProfileUrl = (username: string, type: FollowerTypeEnum) => {
  const patternFn = URL_PATTERNS[type];
  return patternFn ? patternFn(username) : "/404";
};

export default function OpenSocial({ follower }: { follower: Follower }) {
  const href = SOCIAL_URL_PATTERNS[follower.type](follower.username);

  return (
    <Tooltip label={`Go to ${follower.type}`}>
      <ActionIcon<"a"> size="lg" href={href} target="_blank">
        <IconWindowMaximize size={24} />
      </ActionIcon>
    </Tooltip>
  );
}
