import publicApi from "@/lib/public-api";
import { getBucket, getS3, proxySignedUrl } from "@/lib/s3";
import { Source } from "@/lib/types/strapi-autogenerated";
import type { S3Client } from "@aws-sdk/client-s3";
import { GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { unstable_cache } from "next/cache";
import { NextRequest } from "next/server";

const fetchSourcePlaylists = unstable_cache(
  async (documentId: string, quality: "high" | "low" = "high") => {
    const response = await publicApi.source.getSources({
      filters: {
        recording: { documentId },
        state: { $eq: "done" },
      },
      sort: "createdAt:asc",
      fields: ["path", "createdAt", "bucket"],
    } as any);

    const sources = response.data.data ?? [];
    if (!sources.length) return null;

    const s3Client = getS3();
    const bucket = getBucket(process.env.MEDIA_BUCKET!, sources[0].bucket);
    const sourcesWithPlaylists = await fetchPlaylistsFromS3(
      s3Client,
      bucket,
      sources,
      quality,
    );

    return {
      sourcesWithPlaylists,
      bucket: sources[0].bucket,
    };
  },
  ["playlist-sources"],
  { revalidate: 3600 },
);

// Combined + signed playlist is the same bytes for every user. Cache it
// globally for 3h. Signed URLs expire in 4h so they stay valid across the
// cache lifetime.
const buildSignedPlaylist = unstable_cache(
  async (documentId: string, quality: "high" | "low") => {
    const cached = await fetchSourcePlaylists(documentId, quality);
    if (!cached) return null;

    const s3Client = getS3();
    const bucket = getBucket(process.env.MEDIA_BUCKET!, cached.bucket);
    return combinePlaylistsWithSignedUrls(
      s3Client,
      bucket,
      cached.sourcesWithPlaylists,
    );
  },
  ["playlist-signed"],
  { revalidate: 10800 }, // 3h
);

export type SourceWithPlaylist = Source & { playlist?: string | null };

const PUBLIC_PREVIEW_SECONDS = 60;

/**
 * Hard-truncate an HLS playlist to the first N seconds of segments.
 * Iterates lines, sums #EXTINF durations, drops everything past the cap,
 * appends a single #EXT-X-ENDLIST so the player stops naturally.
 */
function truncatePlaylist(playlist: string, maxSec: number): string {
  const lines = playlist.split("\n");
  const out: string[] = [];
  let total = 0;

  for (const line of lines) {
    // Drop the existing ENDLIST — we'll always add our own at the end
    if (line.startsWith("#EXT-X-ENDLIST")) continue;

    if (line.startsWith("#EXTINF:")) {
      const dur = parseFloat(line.match(/#EXTINF:([\d.]+)/)?.[1] || "0");
      if (total + dur > maxSec) break; // cap reached, stop processing
      total += dur;
    }
    out.push(line);
  }
  out.push("#EXT-X-ENDLIST");
  return out.join("\n");
}

const CACHE_HEADERS = {
  "Content-Type": "application/vnd.apple.mpegurl",
  "Cache-Control":
    "public, max-age=600, s-maxage=3600, stale-while-revalidate=86400",
};

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ documentId: string }> },
) {
  const { documentId } = await params;

  // Public playlist — no auth, no quality switching, hard-truncated to a
  // PUBLIC_PREVIEW_SECONDS preview, fully cacheable at CF edge.
  // Full personalised version lives at /my/video/[documentId]/playlist.m3u8.
  const playlist = await buildSignedPlaylist(documentId, "high");
  if (!playlist) return new Response("Not found", { status: 404 });

  return new Response(truncatePlaylist(playlist, PUBLIC_PREVIEW_SECONDS), {
    headers: CACHE_HEADERS,
  });
}

async function fetchFromS3(
  s3Client: S3Client,
  bucket: string,
  key: string,
): Promise<string | null> {
  const abortController = new AbortController();

  try {
    const command = new GetObjectCommand({
      Bucket: bucket,
      Key: key,
    });
    const response = await s3Client.send(command, {
      abortSignal: abortController.signal,
    });

    if (!response.Body) {
      abortController.abort();
      return null;
    }

    return await response.Body.transformToString();
  } catch (error) {
    abortController.abort();

    if (
      (error as any).Code !== "NoSuchKey" &&
      (error as any).name !== "NoSuchKey"
    ) {
      console.error("Error fetching playlist from S3", { key }, error);
    }

    return null;
  }
}

async function fetchPlaylistsFromS3(
  s3Client: S3Client,
  bucket: string,
  sources: Source[],
  quality: "high" | "low",
): Promise<SourceWithPlaylist[]> {
  const filename = quality === "low" ? "playlist_low.m3u8" : "playlist.m3u8";

  const playlists = await Promise.all(
    sources.map((source) =>
      source.path
        ? fetchFromS3(
            s3Client,
            bucket,
            `${source.path.substring(1)}${filename}`,
          )
        : Promise.resolve(null),
    ),
  );

  return sources.map((source, i) => ({
    ...source,
    playlist: playlists[i],
  }));
}

async function combinePlaylistsWithSignedUrls(
  s3Client: S3Client,
  bucket: string,
  sources: SourceWithPlaylist[],
): Promise<string> {
  if (!sources || sources.length === 0) return "";

  const toSign: { mapKey: string; s3Key: string }[] = [];
  const seen = new Set<string>();

  for (const source of sources) {
    if (!source.playlist || !source.path) continue;
    const lines = source.playlist.split("\n");
    for (const line of lines) {
      const mapMatch = line.match(/URI="([^"]+)"/);
      if (mapMatch) {
        const filename = mapMatch[1];
        const mapKey = `${source.path}${filename}`;
        if (!seen.has(mapKey)) {
          seen.add(mapKey);
          toSign.push({
            mapKey,
            s3Key: `${source.path.substring(1)}${filename}`,
          });
        }
      }
      if (line.includes(".mp4") && !line.startsWith("#")) {
        const segMatch = line.trim().match(/(\S+\.mp4)/);
        if (segMatch) {
          const filename = segMatch[1];
          const mapKey = `${source.path}${filename}`;
          if (!seen.has(mapKey)) {
            seen.add(mapKey);
            toSign.push({
              mapKey,
              s3Key: `${source.path.substring(1)}${filename}`,
            });
          }
        }
      }
    }
  }

  const signedEntries = await Promise.all(
    toSign.map(async ({ mapKey, s3Key }) => {
      const command = new GetObjectCommand({ Bucket: bucket, Key: s3Key });
      const url = await getSignedUrl(s3Client, command, { expiresIn: 14400 });
      return [mapKey, proxySignedUrl(url)] as const;
    }),
  );
  const urlMap = new Map(signedEntries);

  let combined = "#EXTM3U\n#EXT-X-VERSION:7\n";
  let maxDuration = 0;
  let isFirst = true;

  for (const source of sources) {
    const playlist = source.playlist;
    if (!playlist) continue;

    const lines = playlist.split("\n");

    for (const line of lines) {
      if (line.startsWith("#EXTM3U")) continue;
      if (line.startsWith("#EXT-X-VERSION")) continue;
      if (line.startsWith("#EXT-X-MEDIA-SEQUENCE")) continue;
      if (line.startsWith("#EXT-X-ENDLIST")) continue;

      if (line.startsWith("#EXT-X-TARGETDURATION")) {
        const dur = parseInt(line.split(":")[1]);
        if (dur > maxDuration) maxDuration = dur;
        continue;
      }

      if (line.startsWith("#EXT-X-MAP")) {
        if (!isFirst) {
          combined += "#EXT-X-DISCONTINUITY\n";
        }
        isFirst = false;
        combined +=
          line.replace(
            /URI="([^"]+)"/,
            (_, filename) =>
              `URI="${urlMap.get(`${source.path}${filename}`) || filename}"`,
          ) + "\n";
        continue;
      }

      if (line.includes(".mp4")) {
        combined +=
          line.replace(
            /(\S+\.mp4)/g,
            (filename) => urlMap.get(`${source.path}${filename}`) || filename,
          ) + "\n";
      } else if (line.trim()) {
        combined += line + "\n";
      }
    }
  }

  combined = combined.replace(
    "#EXT-X-VERSION:7\n",
    `#EXT-X-VERSION:7\n#EXT-X-TARGETDURATION:${maxDuration || 12}\n`,
  );

  combined += "#EXT-X-ENDLIST\n";
  return combined;
}
