"use client";

import { getImageUrl } from "@/app/lib/media-url";
import { Recording } from "@/lib/types/strapi-autogenerated";
import {
  ActionIcon,
  Badge,
  Box,
  Group,
  Image,
  Stack,
  Text,
  UnstyledButton,
} from "@mantine/core";
import { IconX } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useEffect, useRef } from "react";

interface Props {
  recordings: Recording[];
  currentId: string | undefined;
  onSelect: (documentId: string) => void;
  onRemove: (documentId: string) => void;
}

export function WatchLaterQueue({
  recordings,
  currentId,
  onSelect,
  onRemove,
}: Props) {
  const t = useTranslations("protected.watchLater.queue");
  const activeRef = useRef<HTMLButtonElement | null>(null);

  // Scroll the currently-playing item into view when it changes
  useEffect(() => {
    if (activeRef.current) {
      activeRef.current.scrollIntoView({ block: "nearest", behavior: "smooth" });
    }
  }, [currentId]);

  return (
    <Stack gap="xs">
      {recordings.map((rec, idx) => {
        const isActive = rec.documentId === currentId;
        const thumb = getImageUrl(
          rec.documentId!,
          "screenshot.jpg",
          rec.sources?.at(-1),
        );

        return (
          <UnstyledButton
            key={rec.documentId}
            ref={isActive ? activeRef : undefined}
            onClick={() => onSelect(rec.documentId!)}
            p="xs"
            style={{
              borderRadius: 8,
              background: isActive
                ? "rgba(82, 255, 148, 0.08)"
                : "transparent",
              border: isActive
                ? "1px solid rgba(82, 255, 148, 0.3)"
                : "1px solid transparent",
              transition: "background 0.15s",
            }}
            onMouseEnter={(e) => {
              if (!isActive) {
                (e.currentTarget as HTMLElement).style.background =
                  "rgba(255, 255, 255, 0.04)";
              }
            }}
            onMouseLeave={(e) => {
              if (!isActive) {
                (e.currentTarget as HTMLElement).style.background =
                  "transparent";
              }
            }}
          >
            <Group gap="sm" wrap="nowrap" align="flex-start">
              <Text size="xs" c="dimmed" w={20} ta="right" mt={2}>
                {idx + 1}
              </Text>

              <Box
                pos="relative"
                style={{ flexShrink: 0, width: 120, aspectRatio: "16/9" }}
              >
                <Image
                  src={thumb}
                  alt={rec.follower?.nickname ?? rec.follower?.username ?? ""}
                  w="100%"
                  h="100%"
                  radius={4}
                  fit="cover"
                  fallbackSrc="/placeholder-thumb.png"
                />
                {isActive && (
                  <Badge
                    size="xs"
                    color="green"
                    pos="absolute"
                    top={4}
                    left={4}
                    style={{ textTransform: "none" }}
                  >
                    {t("nowPlaying")}
                  </Badge>
                )}
              </Box>

              <Stack gap={2} style={{ flex: 1, minWidth: 0 }}>
                <Text
                  size="sm"
                  fw={isActive ? 600 : 500}
                  lineClamp={2}
                  style={{ lineHeight: 1.3 }}
                >
                  {rec.follower?.nickname ?? rec.follower?.username ?? "—"}
                </Text>
                <Text size="xs" c="dimmed" lineClamp={1}>
                  @{rec.follower?.username}
                </Text>
              </Stack>

              <ActionIcon
                variant="subtle"
                color="gray"
                size="sm"
                aria-label={t("remove")}
                onClick={(e) => {
                  e.stopPropagation();
                  onRemove(rec.documentId!);
                }}
              >
                <IconX size={14} />
              </ActionIcon>
            </Group>
          </UnstyledButton>
        );
      })}
    </Stack>
  );
}
