// components/infinite-followers.tsx
"use client";

import { getFollowers } from "@/app/actions/followers";
import {
  BrowseFollowersResponse,
  ScopeEnum,
  type FollowerWithMeta,
} from "@/lib/types/strapi-autogenerated";
import {
  Avatar,
  Box,
  Grid,
  Group,
  Image,
  Loader,
  Select,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { useIntersection } from "@mantine/hooks";
import { useEffect, useState, useTransition } from "react";
import FollowButton from "../dashboard/follow-button";
import UnfollowButton from "../dashboard/unfollow-button";

const SORT_OPTIONS = [
  { value: "username:asc", label: "Username A-Z" },
  { value: "username:desc", label: "Username Z-A" },
  { value: "createdAt:desc", label: "Newest first" },
  { value: "createdAt:asc", label: "Oldest first" },
];

interface Props {
  initialData: FollowerWithMeta[];
  initialPagination: BrowseFollowersResponse["meta"];
  initialSort?: string;
}

export default function InfiniteFollowers({
  initialData,
  initialPagination,
  initialSort,
}: Props) {
  const [data, setData] = useState(initialData);
  const [page, setPage] = useState(initialPagination?.pagination?.page ?? 1);
  const [hasMore, setHasMore] = useState(
    page < (initialPagination?.pagination?.pageCount ?? 1)
  );
  const [sort, setSort] = useState(initialSort);
  const [isPending, startTransition] = useTransition();

  const { ref, entry } = useIntersection({
    threshold: 0.5,
  });

  const handleSortChange = (value: string | null) => {
    if (!value) return;

    setSort(value);
    startTransition(async () => {
      const result = await getFollowers(ScopeEnum.Discover, 1, value);
      setData(result.data);
      setPage(1);
      setHasMore(1 < (result.meta?.pagination?.pageCount ?? 1));
    });
  };

  const handleFollowed = (id: number) => {
    setData((prev) => prev.filter((f) => f.id !== id));
  };

  useEffect(() => {
    if (entry?.isIntersecting && hasMore && !isPending) {
      startTransition(async () => {
        const nextPage = page + 1;
        const result = await getFollowers(ScopeEnum.Discover, nextPage, sort);

        setData((prev) => {
          const existingIds = new Set(prev.map((f) => f.id));
          const newItems = result.data.filter((f) => !existingIds.has(f.id));
          return [...prev, ...newItems];
        });
        setPage(nextPage);
        setHasMore(nextPage < (result.meta?.pagination?.pageCount ?? 1));
      });
    }
  }, [entry?.isIntersecting, hasMore, isPending, page, sort]);

  return (
    <Stack gap="sm">
      <Group justify="flex-end">
        <Select
          key={sort}
          size="sm"
          w={180}
          value={sort}
          onChange={handleSortChange}
          data={SORT_OPTIONS}
          disabled={isPending}
        />
      </Group>
      <Stack gap="xl">
        {data.map((f) => (
          <Box key={f.documentId} w="100%">
            <Grid>
              <Grid.Col span="content">
                <Avatar
                  size="lg"
                  src={
                    f.recordings?.at(0)?.sources?.at(0)?.path
                      ? process.env.NEXT_PUBLIC_S3_URL! +
                        f.recordings?.at(0)?.sources?.at(0)?.path +
                        "preview.jpg"
                      : null
                  }
                  styles={{
                    image: {
                      transform: "scale(2)",
                      objectFit: "cover",
                    },
                  }}
                />
              </Grid.Col>
              <Grid.Col span="auto">
                <Title order={2} size="md">
                  {f.username}
                </Title>
                <Text>{f.totalRecordings} recordings</Text>
              </Grid.Col>
              <Grid.Col span={2} style={{ textAlign: "right" }}>
                {f.isFollowing ? (
                  <UnfollowButton id={f.id!} />
                ) : (
                  <FollowButton
                    username={f.username!}
                    type={f.type}
                    onSuccess={() => handleFollowed(f.id!)}
                  />
                )}
              </Grid.Col>
            </Grid>
            <Box style={{ overflow: "hidden" }} mt="sm">
              <Group gap="sm" wrap="nowrap">
                {f.recordings?.slice(0, 7).map((rec) => {
                  const path = rec.sources?.length
                    ? process.env.NEXT_PUBLIC_S3_URL! +
                      rec.sources[0].path +
                      "preview.jpg"
                    : null;

                  return (
                    <Image
                      key={rec.documentId}
                      alt={f.username || "unknown"}
                      radius="md"
                      src={path}
                      w={160}
                      h={284}
                      loading="lazy"
                      fallbackSrc="https://placehold.co/600x400?text=Placeholder"
                      style={{
                        objectFit: "cover",
                        objectPosition: "center center",
                        flexShrink: 0,
                      }}
                    />
                  );
                })}
              </Group>
            </Box>
          </Box>
        ))}
      </Stack>
      {/* Sentinel element */}
      <div ref={ref} style={{ height: 1 }} />

      {isPending && <Loader size="sm" style={{ alignSelf: "center" }} />}

      {!hasMore && data.length > 0 && (
        <p style={{ textAlign: "center", color: "gray" }}>No more to load</p>
      )}
    </Stack>
  );
}
