import { Follower, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Button, Tooltip } from "@mantine/core";
import { IconWindowMaximize } from "@tabler/icons-react";

type UrlPattern = (username: string) => string;

export const SOCIAL_URL_PATTERNS: Partial<
  Record<FollowerTypeEnum, UrlPattern>
> = {
  [FollowerTypeEnum.Tiktok]: (username) =>
    `https://www.tiktok.com/@${decodeURIComponent(username).replace(
      /^@/,
      "",
    )}/live`,
  [FollowerTypeEnum.Twitch]: (username) => `https://www.twitch.tv/${username}`,
  [FollowerTypeEnum.Kick]: (username) => `https://www.kick.com/${username}`,
  [FollowerTypeEnum.Youtube]: (username) =>
    `https://www.youtube.com/@${username}/live`,
  [FollowerTypeEnum.Afreecatv]: (username) =>
    `https://play.afreecatv.com/${username}`,
  [FollowerTypeEnum.Pandalive]: (username) =>
    `https://www.pandalive.co.kr/play/${username}`,
  [FollowerTypeEnum.Bigo]: (username) => `https://www.bigo.tv/${username}`,
  [FollowerTypeEnum.Liveme]: (username) =>
    `https://www.liveme.com/u/${username}`,
  [FollowerTypeEnum.Mixch]: (username) => `https://mixch.tv/u/${username}`,
  [FollowerTypeEnum.Twitcast]: (username) =>
    `https://twitcasting.tv/${username}`,
  [FollowerTypeEnum.Trovo]: (username) => `https://trovo.live/s/${username}`,
  [FollowerTypeEnum.Joilive]: (username) =>
    `https://www.joilive.net/user/index.html?s=${username}`,
  [FollowerTypeEnum.Live17]: (username) =>
    `https://17.live/en-US/profile/r/${username}`,
  [FollowerTypeEnum.Kwai]: (username) => `https://www.kwai.com/@${username}`,
  [FollowerTypeEnum.Nimotv]: (username) =>
    `https://www.nimo.tv/live/${username}`,
  [FollowerTypeEnum.Vklive]: (username) => `https://live.vkvideo.ru/${username}`,
  [FollowerTypeEnum.Chzzk]: (username) => `https://chzzk.naver.com/${username}`,
  [FollowerTypeEnum.Younow]: (username) => `https://www.younow.com/${username}`,
  [FollowerTypeEnum.Clapper]: (username) => `https://clapperapp.com/${username}`,
};

export const URL_PATTERNS: Partial<Record<FollowerTypeEnum, UrlPattern>> = {
  [FollowerTypeEnum.Tiktok]: (username) =>
    `/tiktok/@${username.replace(/^(%40|@)/, "")}`,
  [FollowerTypeEnum.Twitch]: (username) => `/twitch/${username}`,
  [FollowerTypeEnum.Kick]: (username) => `/kick/${username}`,
  [FollowerTypeEnum.Youtube]: (username) =>
    `/youtube/@${username.replace(/^(%40|@)/, "")}`,
  [FollowerTypeEnum.Afreecatv]: (username) => `/afreecatv/${username}`,
  [FollowerTypeEnum.Pandalive]: (username) => `/pandalive/${username}`,
  [FollowerTypeEnum.Bigo]: (username) => `/bigo/${username}`,
  [FollowerTypeEnum.Liveme]: (username) => `/liveme/${username}`,
  [FollowerTypeEnum.Mixch]: (username) => `/mixch/${username}`,
  [FollowerTypeEnum.Twitcast]: (username) => `/twitcast/${username}`,
  [FollowerTypeEnum.Trovo]: (username) => `/trovo/${username}`,
  [FollowerTypeEnum.Joilive]: (username) => `/joilive/${username}`,
  [FollowerTypeEnum.Live17]: (username) => `/live17/${username}`,
  [FollowerTypeEnum.Kwai]: (username) => `/kwai/${username}`,
  [FollowerTypeEnum.Nimotv]: (username) => `/nimotv/${username}`,
  [FollowerTypeEnum.Vklive]: (username) => `/vklive/${username}`,
  [FollowerTypeEnum.Chzzk]: (username) => `/chzzk/${username}`,
  [FollowerTypeEnum.Younow]: (username) => `/younow/${username}`,
  [FollowerTypeEnum.Clapper]: (username) => `/clapper/${username}`,
};

export const getSocialUrl = (
  follower?: Partial<Pick<Follower, "username" | "type">>,
) => {
  const patternFn =
    SOCIAL_URL_PATTERNS[follower?.type || FollowerTypeEnum.Tiktok];
  return patternFn ? patternFn(follower?.username || "unknown") : "/404";
};

export const getProfileUrl = (
  follower?: Partial<Pick<Follower, "username" | "type">>,
) => {
  const patternFn = URL_PATTERNS[follower?.type || FollowerTypeEnum.Tiktok];
  return patternFn ? patternFn(follower?.username || "unknown") : "/404";
};

export default function OpenSocial({
  follower,
  showLabel,
}: {
  follower: Follower;
  showLabel?: boolean;
}) {
  const href = SOCIAL_URL_PATTERNS[follower.type]?.(follower.username);
  const label = `Go to ${follower.type}`;

  if (showLabel) {
    return (
      <Button
        component="a"
        size="sm"
        radius="xl"
        leftSection={<IconWindowMaximize size={18} />}
        href={href}
        target="_blank"
      >
        {label}
      </Button>
    );
  }

  return (
    <Tooltip label={label}>
      <ActionIcon component="a" size="lg" href={href} target="_blank">
        <IconWindowMaximize size={24} />
      </ActionIcon>
    </Tooltip>
  );
}
