"use cache";

import publicApi from "@/lib/public-api";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { cacheLife } from "next/cache";

export async function getFollowerFilters(type?: FollowerTypeEnum) {
  cacheLife({ stale: 300, revalidate: 1800, expire: 3600 });

  const { data: filtersData } = await publicApi.follower.getFollowerFilters(
    type ? { type } : { type: undefined },
  );

  return {
    countryCodes: (filtersData.countryCodes ?? [])
      .filter((c) => c.value !== "-")
      .map((c) => ({
        value: c.value || "",
        label: `${c.value} (${c.count})`,
      })),
  };
}

export async function getCreators(type: string, page: number) {
  cacheLife({ stale: 300, revalidate: 1800, expire: 3600 });

  const {
    data: { data: followers, meta },
  } = await publicApi.follower.getFollowers({
    ...(type === "all" ? {} : { filters: { type } }),
    "pagination[pageSize]": 20,
    "pagination[page]": page,
    sort: "createdAt:desc",
    populate: { avatar: true },
  });

  return { followers: followers ?? [], meta };
}

export async function getCreatorsByCountry(
  type: string,
  countryCode: string,
  page: number,
) {
  cacheLife({ stale: 300, revalidate: 1800, expire: 3600 });

  const hasPlatform = type !== "all";

  const {
    data: { data: followers, meta },
  } = await publicApi.follower.getFollowers({
    filters: {
      ...(hasPlatform ? { type } : {}),
      countryCode,
    },
    "pagination[pageSize]": 20,
    "pagination[page]": page,
    sort: "createdAt:desc",
    populate: { avatar: true },
  });

  return { followers: followers ?? [], meta };
}
