"use client";

import { ScheduleDay } from "@/lib/types/analytics-autogenerated";
import { Box, Group, Paper, Stack, Text, Title } from "@mantine/core";
import { IconClock } from "@tabler/icons-react";
import { useFormatter, useTranslations } from "next-intl";
import { use } from "react";

const DAY_KEYS = [
  { key: 1, t: "mon" },
  { key: 2, t: "tue" },
  { key: 3, t: "wed" },
  { key: 4, t: "thu" },
  { key: 5, t: "fri" },
  { key: 6, t: "sat" },
  { key: 7, t: "sun" },
] as const;

interface ScheduleChartProps {
  schedulePromise: Promise<ScheduleDay[]>;
}

export function ScheduleChart({ schedulePromise }: ScheduleChartProps) {
  const t = useTranslations("protected.profileInsights");
  const format = useFormatter();
  const schedule = use(schedulePromise);

  function formatHour(h: number): string {
    const d = new Date(2000, 0, 1, h, 0, 0);
    return format.dateTime(d, { hour: "numeric" });
  }

  const data = DAY_KEYS.map((d) => {
    const found = schedule.find((s) => s.day_of_week === d.key);
    return {
      key: d.key,
      label: t(`schedule.${d.t}`),
      streams: found?.stream_count ?? 0,
      startHour: found?.typical_start_hour ?? null,
      endHour: found?.typical_end_hour ?? null,
    };
  });

  return (
    <Paper withBorder radius="md">
      <Box
        style={{
          background: "linear-gradient(150deg, #D4B4FF, #9452E8)",
          borderTopLeftRadius: 8,
          borderTopRightRadius: 8,
        }}
        p="md"
      >
        <Title order={5} c="black">
          {t("schedule.title")}
        </Title>
      </Box>
      <Stack gap={0}>
        {data.map((d, i) => (
          <Group
            key={d.key}
            justify="space-between"
            wrap="nowrap"
            px="md"
            py={8}
            style={{
              opacity: d.streams === 0 ? 0.35 : 1,
              borderBottom:
                i < data.length - 1
                  ? "1px solid var(--mantine-color-default-border)"
                  : undefined,
            }}
          >
            <Text size="sm" fw={700} w={32} style={{ flexShrink: 0 }}>
              {d.label}
            </Text>
            {d.startHour !== null && d.endHour !== null ? (
              <Group gap={4} wrap="nowrap" style={{ flex: 1 }}>
                <IconClock size={12} opacity={0.5} />
                <Text size="xs" c="dimmed">
                  {formatHour(d.startHour)} – {formatHour(d.endHour)}
                </Text>
              </Group>
            ) : (
              <Text size="xs" c="dimmed" style={{ flex: 1 }}>
                —
              </Text>
            )}
            <Text size="xs" c="dimmed" w={28} ta="right" style={{ flexShrink: 0 }}>
              {d.streams > 0 ? `${d.streams}×` : ""}
            </Text>
          </Group>
        ))}
      </Stack>
    </Paper>
  );
}
