"use client";

import { Source, SourceStateEnum } from "@/lib/types/strapi-autogenerated";
import { Anchor, Image } from "@mantine/core";
import Link from "next/link";

import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { MiniPlayer } from "../../[platform]/[username]/live/[id]/_components/mini-player";
import { formatDuration } from "../../[platform]/[username]/live/[id]/_components/player-utils";

interface Props {
  sources?: Source[] | null;
  href: string;
  w: number;
  h: number;
  alt?: string;
  radius?: string;
}

export function ImageVideoPreview({
  sources,
  href,
  w,
  h,
  alt = "",
  radius = "md",
}: Props) {
  const [showVideo, setShowVideo] = useState(false);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);
  const router = useRouter();

  const totalDuration =
    sources?.reduce((sum, s) => sum + (s.duration || 0), 0) || 0;

  const recording = sources?.some((s) => s.state === SourceStateEnum.Recording);

  const src = sources?.length
    ? process.env.NEXT_PUBLIC_S3_URL! +
      sources[sources.length - 1].path +
      "preview.jpg"
    : null;

  const handleMouseEnter = () => {
    if (!sources || sources.length === 0 || recording) return;
    timeoutRef.current = setTimeout(() => {
      setShowVideo(true);
    }, 300);
  };

  const handleMouseLeave = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      timeoutRef.current = null;
    }
    setShowVideo(false);
  };

  const handleDoubleClick = (evt: React.MouseEvent<HTMLDivElement>) => {
    if (evt.target instanceof HTMLVideoElement) {
      router.push(href);
    }
  };

  return (
    <div
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      style={{
        position: "relative",
        width: w,
        height: h,
      }}
    >
      <Anchor component={Link} href={href}>
        <Image
          alt={alt}
          radius={radius}
          src={recording ? null : src}
          w={w}
          h={h}
          loading="lazy"
          fallbackSrc="https://placehold.co/180x280/black/white?text=Recording..."
          style={{
            objectFit: "cover",
            objectPosition: "center center",
            display: showVideo ? "none" : "block",
            ...(recording && { border: "2px solid #ff0040" }),
          }}
        />
      </Anchor>

      {showVideo && sources && (
        <div
          onClick={handleDoubleClick}
          onDoubleClick={handleDoubleClick}
          style={{ cursor: "pointer" }}
        >
          <MiniPlayer sources={sources} width={w} height={h} />
        </div>
      )}

      {totalDuration > 0 && (
        <div
          style={{
            position: "absolute",
            bottom: 10,
            right: 8,
            backgroundColor: "rgba(0, 0, 0, 0.8)",
            color: "white",
            padding: "2px 6px",
            borderRadius: 4,
            fontSize: 12,
            fontWeight: 500,
            pointerEvents: "none",
          }}
        >
          {formatDuration(totalDuration)}
        </div>
      )}
    </div>
  );
}
