"use client";

import { Source } from "@/lib/types/strapi-autogenerated";
import { Anchor, Image } from "@mantine/core";
import Link from "next/link";

import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { MiniPlayer } from "../../[platform]/[username]/live/[id]/_components/mini-player";

interface Props {
  sources?: Source[] | null;
  href: string;
  src: string | null;
  w: number;
  h: number;
  alt?: string;
  radius?: string;
}

export function ImageVideoPreview({
  sources,
  href,
  src,
  w,
  h,
  alt = "",
  radius = "md",
}: Props) {
  const [showVideo, setShowVideo] = useState(false);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);
  const router = useRouter();

  const handleMouseEnter = () => {
    if (!sources || sources.length === 0) return;
    timeoutRef.current = setTimeout(() => {
      setShowVideo(true);
    }, 300);
  };

  const handleMouseLeave = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      timeoutRef.current = null;
    }
    setShowVideo(false);
  };

  const handleDoubleClick = (evt: React.MouseEvent<HTMLDivElement>) => {
    if (evt.target instanceof HTMLVideoElement) {
      router.push(href);
    }
  };

  return (
    <div
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      style={{ position: "relative", width: w, height: h }}
    >
      <Anchor component={Link} href={href}>
        <Image
          alt={alt}
          radius={radius}
          src={src}
          w={w}
          h={h}
          loading="lazy"
          fallbackSrc="https://placehold.co/600x400?text=Placeholder"
          style={{
            objectFit: "cover",
            objectPosition: "center center",
            display: showVideo ? "none" : "block",
          }}
        />
      </Anchor>

      {showVideo && sources && (
        <div
          onClick={handleDoubleClick}
          onDoubleClick={handleDoubleClick}
          style={{ cursor: "pointer" }}
        >
          <MiniPlayer sources={sources} width={w} height={h} />
        </div>
      )}
    </div>
  );
}
