"use server";

import { removeToken, setToken } from "@/lib/token";
import { Api } from "@/lib/types/strapi-autogenerated";
import { redirect } from "next/navigation";

const api = new Api({
  baseURL: (process.env.STRAPI_URL || "http://localhost:1337") + "/api",
});

export async function login(prevState: any, formData: FormData) {
  const identifier = formData.get("email") as string;
  const password = formData.get("password") as string;

  try {
    const { data } = await api.usersPermissionsAuth.localCreate({
      identifier,
      password,
    });
    await setToken(data.jwt!);
  } catch (err: any) {
    return { error: err.response?.data?.error?.message || "Login failed" };
  }

  redirect("/following");
}

export async function register(prevState: any, formData: FormData) {
  const username = formData.get("username") as string;
  const email = formData.get("email") as string;
  const password = formData.get("password") as string;

  try {
    const { data } = await api.usersPermissionsAuth.localRegisterCreate({
      username,
      email,
      password,
    });
    await setToken(data.jwt!);
  } catch (err: any) {
    return {
      error: err.response?.data?.error?.message || "Registration failed",
    };
  }

  redirect("/following");
}

export async function logout() {
  await removeToken();
  redirect("/login");
}
