"use server";

import {
  ClipWithUrls,
  enrichClipWithUrls,
  getSignedClipDownloadUrl,
} from "@/app/lib/clip-url.server";
import { getUser } from "@/app/actions/user";
import publicApi from "@/lib/public-api";
import { Clip } from "@/lib/types/strapi-autogenerated";
import { getLocale } from "next-intl/server";

let cachedTotal: { value: number; timestamp: number } | null = null;
const CACHE_TTL = 5 * 60 * 1000;

async function getTotalClips() {
  const now = Date.now();

  if (cachedTotal && now - cachedTotal.timestamp < CACHE_TTL) {
    return cachedTotal.value;
  }

  const {
    data: { meta },
  } = await publicApi.clip.getClips({
    "pagination[limit]": 1,
    "pagination[withCount]": true,
  });

  cachedTotal = { value: meta?.pagination?.total || 0, timestamp: now };
  return cachedTotal.value;
}

export async function getRandomClip(): Promise<ClipWithUrls<Clip> | null> {
  const locale = await getLocale();
  const total = await getTotalClips();
  if (total === 0) return null;

  const randomOffset = Math.floor(Math.random() * total);

  const {
    data: { data },
  } = await publicApi.clip.getClips({
    populate: {
      follower: {
        populate: { avatar: true },
      },
    },
    "pagination[limit]": 1,
    "pagination[start]": randomOffset,
    locale,
  });

  if (!data) return null;

  const clip = data[0];
  if (!clip) return null;

  return enrichClipWithUrls(clip);
}

export async function getRandomClips(
  count: number,
): Promise<ClipWithUrls<Clip>[]> {
  const clips = await Promise.all(
    Array.from({ length: count }, () => getRandomClip()),
  );
  return clips.filter((c): c is ClipWithUrls<Clip> => c !== null);
}

export async function getClipDownloadUrlAction(documentId: string) {
  // Premium gate enforced server-side; UI gate is just UX.
  const user = await getUser();
  const roleType = (user?.data as { role?: { type?: string } } | undefined)
    ?.role?.type;
  if (
    roleType !== "premium" &&
    roleType !== "champion" &&
    roleType !== "admin"
  ) {
    return null;
  }

  const {
    data: { data },
  } = await publicApi.clip.getClips({
    filters: { documentId: { $eq: documentId } },
    "pagination[limit]": 1,
  });
  const clip = data?.[0];
  if (!clip) return null;
  return getSignedClipDownloadUrl(clip);
}

export async function getClipById(
  documentId: string,
): Promise<ClipWithUrls<Clip> | null> {
  const locale = await getLocale();
  const {
    data: { data },
  } = await publicApi.clip.getClips({
    filters: {
      documentId: { $eq: documentId },
    },
    populate: {
      follower: {
        populate: { avatar: true },
      },
    },
    "pagination[limit]": 1,
    locale,
  });

  if (!data) return null;
  const clip = data[0];
  if (!clip) return null;
  return enrichClipWithUrls(clip);
}
