"use server";

import publicApi from "@/lib/public-api";
import { Clip, Follower } from "@/lib/types/strapi-autogenerated";

let cachedTotal: { value: number; timestamp: number } | null = null;
const CACHE_TTL = 5 * 60 * 1000;

async function getTotalClips() {
  const now = Date.now();

  if (cachedTotal && now - cachedTotal.timestamp < CACHE_TTL) {
    return cachedTotal.value;
  }

  const {
    data: { meta },
  } = await publicApi.clip.getClips({
    "pagination[limit]": 1,
  });

  cachedTotal = { value: meta?.pagination?.total || 0, timestamp: now };
  return cachedTotal.value;
}

export async function getRandomClip(): Promise<
  (Clip & { follower: Follower | null }) | null
> {
  const total = await getTotalClips();
  if (total === 0) return null;

  const randomOffset = Math.floor(Math.random() * total);

  const {
    data: { data, meta },
  } = await publicApi.clip.getClips({
    populate: {
      follower: {
        populate: { avatar: true },
      },
    },
    "pagination[limit]": 1,
    "pagination[start]": randomOffset,
  });

  if (!data) {
    return null;
  }

  const clip = data[0];
  if (!clip) {
    return null;
  }

  return clip as any;
}

export async function getRandomClips(count: number) {
  const clips = await Promise.all(
    Array.from({ length: count }, () => getRandomClip()),
  );
  return clips.filter(
    (c): c is Clip & { follower: Follower | null } => c !== null,
  );
}
