"use server";

import {
  FollowRequestBody,
  FollowRequestBodyTypeEnum,
  ScopeEnum,
} from "@/lib/types/strapi-autogenerated";
import { revalidatePath } from "next/cache";
import api from "../api";

export type FollowersState = {
  scope: ScopeEnum | "all";
  data: Awaited<ReturnType<typeof api.follower.getFollowers>>["data"];
};

export async function getFollowersData(scope: ScopeEnum | "all") {
  const response = await api.follower.getFollowers({
    scope: scope === "all" ? undefined : scope,
    populate: "*",
  });
  return response.data?.data || [];
}

export async function follow(prevState: any, formData: FormData) {
  const username = formData.get("username") as string;
  const type = formData.get("type") as FollowRequestBodyTypeEnum;

  try {
    await api.follower.followCreate({
      username,
      slug: username.toLowerCase(),
      type,
    });
    revalidatePath("/dashboard");
    return { success: true };
  } catch (err: any) {
    return { error: err.response?.data?.error?.message || "Failed to follow" };
  }
}

export async function followUser(data: FollowRequestBody) {
  try {
    await api.follower.followCreate(data);
    revalidatePath("/dashboard");
    return { success: true };
  } catch (err: any) {
    return { error: err.response?.data?.error?.message || "Failed to follow" };
  }
}

export async function unfollow(id: number) {
  try {
    await api.follower.unfollowDelete({ id });
    revalidatePath("/dashboard");
    return { success: true };
  } catch (err: any) {
    return {
      error: err.response?.data?.error?.message || "Failed to unfollow",
    };
  }
}
