"use server";

import api from "@/lib/api";
import publicApi from "@/lib/public-api";
import {
  FollowerTypeEnum,
  FollowRequestBody,
} from "@/lib/types/strapi-autogenerated";
import { revalidatePath } from "next/cache";

export async function follow(username: string, type: FollowerTypeEnum) {
  try {
    await api.follower.followCreate({
      username,
      type,
    });

    return { success: true, username, type };
  } catch (err: any) {
    return { error: err.response?.data?.error?.message || "Failed to follow" };
  }
}

export async function followUser(data: FollowRequestBody) {
  try {
    await api.follower.followCreate(data);
    revalidatePath("/following");
    revalidatePath(`/${data.type}/${data.username}`);

    return { success: true };
  } catch (err: any) {
    return { error: err.response?.data?.error?.message || "Failed to follow" };
  }
}

export async function unfollow(data: FollowRequestBody) {
  try {
    await api.follower.unfollowCreate(data);
    revalidatePath("/following");
    revalidatePath(`/${data.type}/${data.username}`);

    return { success: true };
  } catch (err: any) {
    return {
      error: err.response?.data?.error?.message || "Failed to unfollow",
    };
  }
}

export async function updateFollower(documentId: string, data: any) {
  await api.follower.putFollowersId({ id: documentId }, { data });
}

export async function getFollowerFilters(type?: FollowerTypeEnum) {
  const { data: filtersData } = await publicApi.follower.getFollowerFilters(
    type ? { type } : { type: undefined },
  );

  return {
    genders: (filtersData.genders ?? [])
      .filter((g) => g.value)
      .map((g) => ({
        value: g.value || "",
        label: `${g.value} (${g.count})`,
      })),
    countryCodes: (filtersData.countryCodes ?? [])
      .filter((c) => c.value !== "-")
      .map((c) => ({
        value: c.value || "",
        label: `${c.value} (${c.count})`,
      })),
    types: (filtersData.types ?? []).map((l) => ({
      value: l.value || "",
      label: `${l.value} (${l.count})`,
    })),
    languageCodes: (filtersData.languageCodes ?? []).map((l) => ({
      value: l.value || "",
      label: `${l.value} (${l.count})`,
    })),
  };
}
