"use server";

import { SortOptions } from "@/lib/types/filtering";
import {
  FollowerTypeEnum,
  FollowRequestBody,
  ScopeEnum,
} from "@/lib/types/strapi-autogenerated";
import { revalidatePath } from "next/cache";
import api from "../../lib/api";

export async function follow(prevState: any, formData: FormData) {
  const username = formData.get("username") as string;
  const type = formData.get("type") as FollowerTypeEnum;

  try {
    await api.follower.followCreate({
      username,
      type,
    });

    revalidatePath("/following");

    return { success: true, username, type };
  } catch (err: any) {
    return { error: err.response?.data?.error?.message || "Failed to follow" };
  }
}

export async function followUser(data: FollowRequestBody) {
  try {
    await api.follower.followCreate(data);
    revalidatePath("/following");

    return { success: true };
  } catch (err: any) {
    return { error: err.response?.data?.error?.message || "Failed to follow" };
  }
}

export async function unfollow(documentId: string) {
  try {
    await api.follower.unfollowDelete({ documentId });
    revalidatePath("/following");

    return { success: true };
  } catch (err: any) {
    return {
      error: err.response?.data?.error?.message || "Failed to unfollow",
    };
  }
}

export async function getFollowers({
  scope,
  page,
  sort = SortOptions.createdAtAsc,
  hasRecordings,
}: {
  scope: ScopeEnum;
  page: number;
  sort: SortOptions;
  hasRecordings?: boolean;
}) {
  const response = await api.follower.browseFollowers({
    scope,
    hasRecordings,
    "pagination[page]": page,
    "pagination[pageSize]": 10,
    populate: {
      avatar: {
        fields: ["url"],
      },
      recordings: {
        populate: {
          sources: {
            fields: ["*"],
            filters: {
              state: { $ne: "failed" },
            },
            populate: ["videoSmall", "videoOriginal"], // we ask for original because sometime small is null while encoding for mini-player
          },
        },
      },
    },

    sort,
  });

  return {
    data: response.data?.data || [],
    meta: response.data?.meta,
  };
}
