"use server";

import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import api from "../api";

export type RecordingsState = {
  scope: ScopeEnum | "all";
  data: Awaited<ReturnType<typeof api.recording.getRecordings>>["data"];
};

export async function getRecordings(
  _prevState: RecordingsState | null,
  formData: FormData
): Promise<RecordingsState> {
  const scope = formData.get("scope") as ScopeEnum | "all";

  const response = await api.recording.getRecordings({
    scope: scope === "all" ? undefined : scope,
    populate: "*",
  });

  return {
    scope,
    data: response.data,
  };
}
