services:
  glances:
    image: "nicolargo/glances:latest"
    environment:
      - GLANCES_OPT=-w
      - GLANCES_USERNAME=admin
      - GLANCES_PASSWORD=your_password_here
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
    pid: host
    ports:
      - "61208:61208"
    healthcheck:
      test:
        - CMD-SHELL
        - "curl -f http://127.0.0.1:61208/ || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
