services:
  init-configs:
    image: "alpine:latest"
    restart: "no"
    volumes:
      - "config_data:/config"
    command: "sh -c '\ncat > /config/process-exporter.yml << \"EOF\"\nprocess_names:\n  - name: \"ffmpeg:screenshot\"\n    comm:\n      - ffmpeg\n    cmdline:\n      - \"screenshot.jpg\"\n\n  - name: \"ffmpeg:thumbnails\"\n    comm:\n      - ffmpeg\n    cmdline:\n      - \"thumbnails.jpg\"\n\n  - name: \"ffmpeg:thumb\"\n    comm:\n      - ffmpeg\n    cmdline:\n      - \"thumb_\"\n\n  - name: \"ffmpeg:preview\"\n    comm:\n      - ffmpeg\n    cmdline:\n      - \"preview.jpg\"\n\n  - name: \"ffmpeg:video_small\"\n    comm:\n      - ffmpeg\n    cmdline:\n      - \"video_small.mp4\"\n\n  - name: \"ffmpeg:video\"\n    comm:\n      - ffmpeg\n    cmdline:\n      - \"video.mp4\"\n\n  - name: \"ffmpeg:other\"\n    comm:\n      - ffmpeg\n\n  - name: \"node\"\n    comm:\n      - node\n\n  - name: \"python\"\n    comm:\n      - python\n      - python3\n\n  - name: \"curl\"\n    comm:\n      - curl\n\n  - name: \"streamlink\"\n    comm:\n      - streamlink\nEOF\n'\n"
  node-exporter:
    image: "prom/node-exporter:latest"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
  process-exporter:
    image: "ncabatoff/process-exporter:latest"
    command:
      - "--procfs=/host/proc"
      - "-config.path=/config/process-exporter.yml"
    volumes:
      - "/proc:/host/proc:ro"
      - "config_data:/config:ro"
    ports:
      - "9256:9256"
    privileged: true
    restart: unless-stopped
    depends_on:
      init-configs:
        condition: service_completed_successfully
volumes:
  config_data: null
