services:
  warp-proxy:
    image: "caomingjun/warp:latest"
    restart: always
    ports:
      - "1080:1080"
    environment:
      - "GOST_ARGS=-L 0.0.0.0:1080 -F 127.0.0.1:40000"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - "warp-data:/var/lib/cloudflare-warp"
    healthcheck:
      test:
        - CMD
        - sh
        - "-c"
        - "warp-cli --accept-tos mode proxy && curl --proxy socks5://127.0.0.1:40000 --connect-timeout 5 -s https://httpbin.org/ip > /dev/null || exit 1"
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s
