"use client";

import { Flex, Loader, Modal } from "@mantine/core";
import { useInfiniteQuery } from "@tanstack/react-query";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useQueryStates } from "nuqs";
import { useCallback, useMemo } from "react";

import { VideoScrollPlayer } from "@/app/[locale]/(protected)/components/video/video-scroll-player";
import { fetchProfileRecordings } from "@/app/[locale]/(protected)/protected/[type]/[username]/actions/actions";
import { profileParsers } from "@/app/[locale]/(protected)/protected/[type]/[username]/lib/search-params";
import { Recording } from "@/lib/types/strapi-autogenerated";

export default function ProfileRecordingModal() {
  const router = useRouter();
  const params = useParams<{
    id: string;
    username: string;
    type: string;
  }>();

  const searchParams = useSearchParams();
  const [filters] = useQueryStates(profileParsers);

  const { data, fetchNextPage, hasNextPage, isFetchingNextPage, isLoading } =
    useInfiniteQuery({
      queryKey: ["profile-recordings", params.type, params.username, filters],
      queryFn: ({ pageParam }) =>
        fetchProfileRecordings(
          params.type,
          params.username,
          filters,
          pageParam
        ),
      initialPageParam: 1,
      getNextPageParam: (lastPage) => {
        const { page = 1, pageCount = 0 } = lastPage.meta?.pagination ?? {};
        return page < pageCount ? page + 1 : undefined;
      },
    });

  const recordings = useMemo(
    () => data?.pages.flatMap((p) => p.data) ?? [],
    [data]
  );

  const handleClose = () => {
    router.back();
  };

  const handleVisibleChange = useCallback(
    (recording: Recording) => {
      const basePath = `/${params.type}/${decodeURIComponent(
        params.username
      )}/video/${recording.documentId}`;
      const search = searchParams.toString();
      const url = search ? `${basePath}?${search}` : basePath;
      window.history.replaceState(null, "", url);
    },
    [params.type, params.username, searchParams]
  );

  const handleNotFound = () => {
    router.replace(`/${params.type}/${decodeURIComponent(params.username)}`);
  };

  if (isLoading) {
    return (
      <Modal.Root opened={true} onClose={handleClose} fullScreen>
        <Modal.Content>
          <Flex h="100dvh" justify="center" align="center">
            <Loader size="lg" />
          </Flex>
        </Modal.Content>
      </Modal.Root>
    );
  }

  return (
    <Modal.Root
      opened={true}
      onClose={handleClose}
      fullScreen
      styles={{
        body: { height: "100%", padding: 0, overflow: "hidden" },
        content: { overflow: "hidden" },
      }}
    >
      <Modal.Content>
        <Modal.Body p={0} h="100%">
          <VideoScrollPlayer
            recordings={recordings}
            initialId={params.id}
            hasNextPage={hasNextPage}
            isFetchingNextPage={isFetchingNextPage}
            onFetchNextPage={fetchNextPage}
            onVisibleChange={handleVisibleChange}
            onClose={handleClose}
            onNotFound={handleNotFound}
            showCloseButton={true}
            height="100dvh"
          />
        </Modal.Body>
      </Modal.Content>
    </Modal.Root>
  );
}
