import InfiniteFollowers from "@/app/(protected)/_components/infinite-followers";
import api from "@/lib/api";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";

export default async function FollowingsPage() {
  const response = await api.follower.browseFollowers({
    scope: ScopeEnum.Discover,
    hasRecordings: true,
    populate: {
      recordings: {
        populate: {
          sources: {
            fields: ["id", "documentId", "path", "duration"],
          },
        },
      },
    },
    "pagination[page]": 1,
    "pagination[pageSize]": 10,
    sort: "username:asc",
  });

  const data = response.data?.data || [];
  const meta = response.data?.meta;

  return (
    <section>
      {data.length === 0 ? (
        <p>No more accounts to discover.</p>
      ) : (
        <InfiniteFollowers
          title="Discover"
          initialData={data}
          initialPagination={meta}
          initialSort="username:asc"
        />
      )}
    </section>
  );
}
