import { combinePlaylistsFromSources } from "@/app/(protected)/components/video/player-utils";
import publicApi from "@/lib/public-api";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { NextRequest } from "next/server";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ documentId: string }> }
) {
  const { documentId } = await params;

  const response = await publicApi.recording.getRecordingsId({
    id: documentId,
    populate: {
      sources: {
        fields: ["*"],
        filters: {
          state: {
            $eq: "done",
          },
        },
        populate: ["videoSmall", "videoOriginal"], // we ask for original because sometime small is null while encoding for mini-player
      },
    },
  });

  if (!response?.data.data) {
    return new Response("Not found", { status: 404 });
  }

  const recording = response.data.data as unknown as Recording;

  const playlist = combinePlaylistsFromSources(
    recording.sources || [],
    "original"
  );

  return new Response(playlist, {
    headers: {
      "Content-Type": "application/vnd.apple.mpegurl",
    },
  });
}
