"use client";

import { DownloadUpgradeModal } from "@/app/[locale]/(protected)/components/download-upgrade-modal";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { useUser } from "@/app/providers/user-provider";
import { Clip, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import {
  ActionIcon,
  Anchor,
  Avatar,
  Card,
  Flex,
  Group,
  Stack,
  Text,
  Tooltip,
} from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { IconDownload } from "@tabler/icons-react";
import { useFormatter } from "next-intl";
import Image from "next/image";
import Link from "next/link";
import { ClipMenu } from "./clip-menu";
import { ClipPreview } from "./clip-preview";

interface ClipCardProps {
  clip: Clip;
  locale: string;
}

export function ClipCard({ clip, locale }: ClipCardProps) {
  const follower = clip.follower;
  const format = useFormatter();
  const user = useUser();
  const isPremium = user?.role?.type !== "authenticated";
  const [upgradeOpened, { open: openUpgrade, close: closeUpgrade }] =
    useDisclosure(false);

  const handleDownload = () => {
    if (!isPremium) {
      openUpgrade();
      return;
    }
    const link = document.createElement("a");
    link.href = `/clip/${clip.documentId}/clip.mp4?download`;
    link.download = `${clip.title || "clip"}.mp4`;
    link.click();
  };

  return (
    <>
    <DownloadUpgradeModal opened={upgradeOpened} onClose={closeUpgrade} />
    <Card radius="md" withBorder>
      <Stack gap="xs">
        <Flex justify="space-between" align="center">
          <Text fw="bold" fz="sm" lineClamp={1}>
            {clip.title}
          </Text>
          <Tooltip label="Download">
            <ActionIcon variant="filled" onClick={handleDownload}>
              <IconDownload size={18} />
            </ActionIcon>
          </Tooltip>
        </Flex>

        <ClipPreview clip={clip} type={clip.follower?.type} locale={locale} />

        <Flex justify="space-between" align="center">
          <Group gap="xs">
            {follower && (
              <Anchor
                component={Link}
                href={getProfileUrl(follower as unknown as { username?: string; type?: FollowerTypeEnum })}
                prefetch={false}
              >
                <Avatar size="sm">
                  {follower.avatar?.url && (
                    <Image
                      src={generateAvatarUrl(follower.avatar?.url)}
                      alt=""
                      width={28}
                      height={28}
                      unoptimized
                    />
                  )}
                </Avatar>
              </Anchor>
            )}
            <Stack gap={0}>
              {follower && (
                <Anchor
                  component={Link}
                  href={getProfileUrl(follower as unknown as { username?: string; type?: FollowerTypeEnum })}
                  prefetch={false}
                  size="xs"
                >
                  @{follower.username}
                </Anchor>
              )}
              {clip.createdAt && (
                <Text size="xs" c="dimmed">
                  {format.dateTime(new Date(clip.createdAt), {
                    dateStyle: "medium",
                    timeStyle: "short",
                  })}
                </Text>
              )}
            </Stack>
          </Group>
          <ClipMenu clip={clip} />
        </Flex>
      </Stack>
    </Card>
    </>
  );
}
