import publicApi from "@/lib/public-api";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";

const s3 = new S3Client({
  region: "fsn1",
  endpoint: "https://fsn1.your-objectstorage.com",
  credentials: {
    accessKeyId: process.env.S3_ACCESS_KEY!,
    secretAccessKey: process.env.S3_SECRET_KEY!,
  },
});

export async function GET(
  request: Request,
  { params }: { params: Promise<{ documentId: string }> },
) {
  const { documentId } = await params;

  const { data } = await publicApi.recording.getRecordingsId({
    id: documentId,
    populate: {
      sources: {
        fields: ["path"],
        filters: {
          state: {
            $ne: "failed",
          },
        },
      },
    },
  });

  if (!data.data) {
    return new Response("Not found", { status: 404 });
  }

  const recording = data.data as unknown as Recording;

  const path = recording.sources?.at(-1)?.path;
  if (!path) {
    return new Response("Not found", { status: 404 });
  }

  const abortController = new AbortController();

  try {
    const command = new GetObjectCommand({
      Bucket: process.env.MEDIA_BUCKET!,
      Key: decodeURIComponent(`${path.substring(1)}screenshot.jpg`),
    });
    const response = await s3.send(command, {
      abortSignal: abortController.signal,
    });

    return new Response(response.Body as ReadableStream, {
      headers: {
        "Content-Type": response.ContentType || "application/octet-stream",
        "Cache-Control": "public, max-age=31536000",
      },
    });
  } catch (error: any) {
    abortController.abort();

    if (error.Code === "NoSuchKey" || error.name === "NoSuchKey") {
      return new Response("Not found", { status: 404 });
    }

    console.error("Error fetching screenshot:", error);
    return new Response("Error", { status: 500 });
  }
}
