import api from "@/app/api";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import FollowButton from "../follow-button";
import UnfollowButton from "../unfollow-button";

export default async function FollowingsPage() {
  const response = await api.follower.browseFollowers({
    scope: ScopeEnum.Following,
  });

  const data = response.data?.data || [];

  return (
    <section>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 16,
        }}
      >
        <h2>Followers ({data.length})</h2>
      </div>

      {data.length === 0 ? (
        <p>You are not following anyone yet.</p>
      ) : (
        <ul style={{ listStyle: "none", padding: 0 }}>
          {data.map((f) => (
            <li
              key={f.id}
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                marginBottom: 8,
              }}
            >
              <div>
                <strong>{f.username}</strong>
                <br />
                <small>{f.totalRecordings} recordings</small>
                {f.recordings?.length}
              </div>
              {f.isFollowing ? (
                <UnfollowButton id={f.id!} />
              ) : (
                <FollowButton username={f.username!} type={f.type} />
              )}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
