"use server";

import {
  fetchCachedRecordings,
  RecordingScope,
} from "@/app/actions/recordings";
import api from "@/lib/api";
import { FollowerTypeEnum, ScopeEnum } from "@/lib/types/strapi-autogenerated";

export async function fetchRecordingsByPlatform(
  scope: ScopeEnum,
  platform: FollowerTypeEnum,
) {
  const result = await fetchCachedRecordings({
    scope: scope as unknown as RecordingScope,
    filters: {
      follower: {
        type: { $eq: platform },
      },
    },
    sort: "updatedAt:desc",
    page: 1,
    pageSize: 4,
  });
  return result.data || [];
}

export async function fetchFavoriteRecordings() {
  const result = await fetchCachedRecordings({
    scope: "favorites" as RecordingScope,
    filters: {},
    sort: "updatedAt:desc",
    page: 1,
    pageSize: 4,
  });
  return result.data || [];
}

export async function fetchLatestFollowers() {
  const response = await api.follower.browseFollowers({
    sort: "createdAt:desc",
    hasRecordings: false,
    "pagination[page]": 1,
    "pagination[pageSize]": 20,
  });

  return (response.data?.data || []).filter((f) => f.avatar?.url).slice(0, 10);
}
