"use server";

import api from "@/lib/api";
import publicApi from "@/lib/public-api";
import {
  Follower,
  FollowerTypeEnum,
  ScopeEnum,
} from "@/lib/types/strapi-autogenerated";
import { cache } from "react";

const basePopulate = {
  sources: {
    fields: ["*"],
    filters: {
      state: {
        $eq: "done",
      },
    },
  },
  follower: {
    fields: ["username", "type"],
    populate: {
      avatar: {
        fields: ["url"],
      },
    },
  },
};

export const getUserFollowerIds = cache(async () => {
  const { data } =
    await api.usersPermissionsUsersRoles.getUsersPermissionsUsersRoles({
      populate: {
        followers: {
          fields: ["id"],
        },
      },
    });

  return (data as any)?.followers?.map((f: Follower) => f.id) || [0];
});

export async function fetchRecordingsByPlatform(
  scope: ScopeEnum,
  platform: FollowerTypeEnum,
) {
  const followerIds = await getUserFollowerIds();
  const response = await publicApi.recording.getRecordings({
    filters: {
      sources: {
        state: {
          $eq: ["done"],
        },
      },
      follower: {
        id:
          scope === ScopeEnum.Following
            ? { $in: followerIds }
            : { $notIn: followerIds },
        type: { $eq: platform },
      },
    },
    populate: basePopulate,
    sort: "updatedAt:desc",
    "pagination[page]": 1,
    "pagination[pageSize]": 4,
  });

  return response.data?.data || [];
}

export async function fetchLatestFollowers() {
  const response = await publicApi.follower.getFollowers({
    sort: "createdAt:desc",
    "pagination[page]": 1,
    "pagination[pageSize]": 6,
    populate: ["avatar"],
  });

  return response.data?.data || [];
}
