import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getProfileUrl } from "@/app/components/open-social";

import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Anchor, Avatar, Flex, Stack, Text } from "@mantine/core";
import Image from "next/image";
import styles from "./creators-slider.module.css";

export function CreatorsSlider({
  followers,
}: {
  followers: Follower[] | undefined;
}) {
  if (!followers?.length) return null;

  // Duplicate for seamless loop
  const duplicatedFollowers = followers;

  return (
    <div style={{ overflowX: "clip" }}>
      <div className={styles.sliderContainer}>
        <div className={styles.sliderTrack}>
          {duplicatedFollowers.map((creator, index) => (
            <Anchor
              key={`${creator.id}-${index}`}
              href={getProfileUrl(creator)}
              underline="never"
              className={styles.slide}
            >
              <Flex
                style={{
                  cursor: "pointer",
                  textAlign: "center",
                  width: "160px",
                }}
              >
                <Stack align="center" gap={12}>
                  <div style={{ position: "relative" }}>
                    <Avatar size={72} radius="xl">
                      <Image
                        src={generateAvatarUrl(creator.avatar?.url)}
                        alt={`${creator.username} avatar`}
                        width={72}
                        height={72}
                        quality={75}
                      />
                    </Avatar>
                    {creator.type && (
                      <FollowerTypeIcon
                        pos="absolute"
                        color="transparent"
                        type={creator.type}
                        top="50%"
                        left="50%"
                        size={40}
                        opacity={0.5}
                        style={{ transform: "translate(-50%, -50%)" }}
                      />
                    )}
                  </div>
                  <div>
                    <Text fw={600} size="sm" style={{ color: "#f1f5f9" }}>
                      {creator.nickname || "unknown"}
                    </Text>
                    <Text size="xs" style={{ color: "#64748b" }}>
                      @{creator.username}
                    </Text>
                  </div>
                  <div style={{ minHeight: 24 }}>
                    {creator.countryCode && (
                      <CountryFlag
                        countryCode={creator.countryCode}
                        size={20}
                      />
                    )}
                  </div>
                </Stack>
              </Flex>
            </Anchor>
          ))}
        </div>
      </div>
    </div>
  );
}
