import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getProfileUrl } from "@/app/components/open-social";

import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { Follower } from "@/lib/types/strapi-autogenerated";
import {
  Anchor,
  Avatar,
  Box,
  Card,
  Flex,
  Group,
  Stack,
  Text,
} from "@mantine/core";
import Image from "next/image";

export function CreatorsSimpleGrid({
  followers,
}: {
  followers: Follower[] | undefined;
}) {
  return (
    <Flex gap={20} wrap="wrap">
      {followers?.map((creator) => {
        const avatarUrl = creator.avatar?.url
          ? generateAvatarUrl(creator.avatar.url)
          : null;

        return (
          <div
            key={creator.id}
            style={{
              flex: "0 1 calc(16.666% - 17px)",
              minWidth: "180px",
              maxWidth: "220px",
            }}
          >
            <Anchor href={getProfileUrl(creator)} underline="never">
              <Card
                padding={0}
                radius="lg"
                style={{
                  background: "rgba(255, 255, 255, 0.03)",
                  border: "1px solid rgba(255, 255, 255, 0.08)",
                  cursor: "pointer",
                  overflow: "hidden",
                }}
              >
                <Box
                  h={80}
                  style={{
                    backgroundImage: avatarUrl
                      ? `url(${avatarUrl})`
                      : "linear-gradient(135deg, #1a1b1e, #2c2e33)",
                    backgroundSize: "cover",
                    backgroundPosition: "top",
                    filter: "brightness(0.6)",
                  }}
                />

                <Stack align="center" mt={-40} gap="sm" pb="md" px="md">
                  <Avatar
                    size={72}
                    radius="xl"
                    style={{
                      border: "3px solid var(--mantine-color-dark-7)",
                    }}
                  >
                    {avatarUrl && (
                      <Image
                        src={avatarUrl}
                        alt={creator.username || ""}
                        width={72}
                        height={72}
                      />
                    )}
                  </Avatar>

                  <Stack gap={2} align="center" w="100%">
                    <Group gap={4} align="center" wrap="nowrap">
                      <Text fw={700} size="sm" c="white" lineClamp={1}>
                        {creator.nickname || creator.username}
                      </Text>
                      {creator.type && (
                        <FollowerTypeIcon
                          type={creator.type}
                          color="transparent"
                          size={16}
                          style={{ flexShrink: 0 }}
                        />
                      )}
                    </Group>
                    <Text size="xs" c="dimmed" ta="center" lineClamp={1}>
                      @{creator.username}
                    </Text>
                  </Stack>

                  <Group gap="xs" align="center">
                    {creator.countryCode && (
                      <CountryFlag countryCode={creator.countryCode} size={16} />
                    )}
                    {creator.createdAt && (
                      <Text size="xs" c="dimmed">
                        {new Date(creator.createdAt).toLocaleDateString(undefined, { month: "short", year: "numeric" })}
                      </Text>
                    )}
                  </Group>
                </Stack>
              </Card>
            </Anchor>
          </div>
        );
      })}
    </Flex>
  );
}
