import { AiRequest } from "@/lib/types/strapi-autogenerated";

export function deriveRequestState(
  aiRequest: AiRequest,
  isAdmin: boolean,
): string {
  // Calculate expected total tasks based on selected options
  // Base: 2 (video workflow) + 2 per feature
  // For non-admins, exclude profile tasks from the count
  const expectedTotal =
    2 +
    (aiRequest.generateClips ? 2 : 0) +
    (aiRequest.generateMemes ? 2 : 0) +
    (aiRequest.generateProfile && isAdmin ? 2 : 0);

  const tasks = aiRequest.ai_tasks || [];

  // Filter tasks for counting based on admin status
  const visibleTasks = isAdmin
    ? tasks
    : tasks.filter((t) => !t.type?.startsWith("profile::"));

  const completedTasks = visibleTasks.filter(
    (t) => t.state === "completed",
  ).length;
  const failedTasks = visibleTasks.filter((t) => t.state === "failed").length;
  const processingTasks = visibleTasks.filter(
    (t) => t.state === "processing",
  ).length;

  return failedTasks > 0
    ? "failed"
    : completedTasks >= expectedTotal
      ? "completed"
      : processingTasks > 0 || completedTasks > 0
        ? "processing"
        : "pending";
}

export function getVisibleTaskCounts(aiRequest: AiRequest, isAdmin: boolean) {
  const expectedTotal =
    2 +
    (aiRequest.generateClips ? 2 : 0) +
    (aiRequest.generateMemes ? 2 : 0) +
    (aiRequest.generateProfile && isAdmin ? 2 : 0);

  const tasks = aiRequest.ai_tasks || [];
  const visibleTasks = isAdmin
    ? tasks
    : tasks.filter((t) => !t.type?.startsWith("profile::"));

  const completedTasks = visibleTasks.filter(
    (t) => t.state === "completed",
  ).length;

  return { expectedTotal, completedTasks };
}
