"use client";

import dayjs from "@/app/lib/dayjs";
import { Article } from "@/lib/types/strapi-autogenerated";
import { Alert, Stack, Text } from "@mantine/core";
import {
  IconBulb,
  IconInfoCircle,
  IconNews,
  IconRocket,
  IconTools,
} from "@tabler/icons-react";
import { marked } from "marked";

const icons = {
  teal: IconTools,
  blue: IconInfoCircle,
  green: IconRocket,
  yellow: IconBulb,
  default: IconNews,
};

export function NewsList({ articles }: { articles: Article[] }) {
  return (
    <Stack gap="md">
      {articles.map((article) => {
        const Icon =
          icons[article.color as keyof typeof icons] || icons.default;

        return (
          <Alert
            key={article.documentId}
            icon={<Icon size={24} />}
            title={article.title}
            color={article.color || "teal"}
            pb="lg"
            pt="lg"
            radius="md"
          >
            {article.content && (
              <div
                dangerouslySetInnerHTML={{
                  __html: marked.parse(article.content) as string,
                }}
              />
            )}
            <Text size="xs" c="dimmed" mt="sm">
              {dayjs(article.createdAt).fromNow()}
            </Text>
          </Alert>
        );
      })}
    </Stack>
  );
}
