"use client";

import {
  blockFollowerAndPurge,
  follow,
  updateFollower,
} from "@/app/actions/followers";
import { Can, Role } from "@/app/providers/ability-provider";
import { Follower, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Button, Menu, Text } from "@mantine/core";
import { modals } from "@mantine/modals";
import { notifications } from "@mantine/notifications";
import {
  IconBan,
  IconCheck,
  IconLock,
  IconLockOpen2,
  IconPlayerPause,
  IconPlayerPlay,
  IconTransformPoint,
  IconTrash,
} from "@tabler/icons-react";
import { useState, useTransition } from "react";

export function AdminMenu({ follower, showLabel }: { follower: Follower; showLabel?: boolean }) {
  const [isPending, startTransition] = useTransition();
  const [paused, setPaused] = useState(follower.pause || false);

  const [protect, setProtect] = useState(follower.protected || false);

  const handlePaused = () => {
    const nextPaused = !paused;
    setPaused(nextPaused);

    startTransition(async () => {
      await updateFollower(follower.documentId!, {
        pause: nextPaused,
      });
    });
  };

  const handleDelete = () => {};

  const handleCheck = () => {
    startTransition(async () => {
      await follow(follower.username!, follower.type as FollowerTypeEnum);
    });
  };

  const handleProtected = () => {
    const nextProtected = !protect;
    setProtect(nextProtected);

    startTransition(async () => {
      await updateFollower(follower.documentId!, {
        protected: nextProtected,
      });
    });
  };

  const handleBlock = () => {
    modals.openConfirmModal({
      title: `Block ${follower.username}`,
      children: (
        <Text size="sm">
          This sets the creator as <strong>blocked</strong> and permanently
          deletes all their recordings and source files. This cannot be undone.
          Continue?
        </Text>
      ),
      labels: { confirm: "Block & purge", cancel: "Cancel" },
      confirmProps: { color: "red" },
      onConfirm: () => {
        startTransition(async () => {
          const result = await blockFollowerAndPurge(follower.documentId!);
          if (result.success) {
            notifications.show({
              title: `Blocked. Deleted ${result.deletedRecordings ?? 0} recording(s), ${result.deletedSources ?? 0} source(s), ${result.deletedClips ?? 0} clip(s).`,
              message: null,
              color: "red",
            });
          } else {
            notifications.show({
              title: "Failed to block creator",
              message: result.error ?? null,
              color: "red",
            });
          }
        });
      },
    });
  };

  return (
    <Role is={["admin", "moderator"]}>
      <Menu width={200} shadow="md" position="bottom-start">
        <Menu.Target>
          {showLabel ? (
            <Button size="sm" radius="xl" color="yellow" leftSection={<IconTransformPoint size={18} />}>
              Admin
            </Button>
          ) : (
            <ActionIcon size="lg" color="yellow">
              <IconTransformPoint />
            </ActionIcon>
          )}
        </Menu.Target>

        <Menu.Dropdown>
          <Can I="update" a="Follower">
            <Menu.Item
              leftSection={paused ? <IconPlayerPlay /> : <IconPlayerPause />}
              onClick={handlePaused}
            >
              {paused ? "Resume download" : "Pause download"}
            </Menu.Item>
          </Can>
          <Can I="update" a="Follower">
            <Menu.Item
              leftSection={protect ? <IconLock /> : <IconLockOpen2 />}
              onClick={handleProtected}
            >
              {protect ? "Unlock" : "Lock"}
            </Menu.Item>
          </Can>
          <Can I="update" a="Follower">
            <Menu.Item leftSection={<IconCheck />} onClick={handleCheck}>
              Check
            </Menu.Item>
          </Can>
          <Can I="delete" a="Follower">
            <Menu.Item leftSection={<IconTrash />} onClick={handleDelete}>
              Delete
            </Menu.Item>
          </Can>
          <Role is={["admin"]}>
            <Menu.Divider />
            <Menu.Item
              color="red"
              leftSection={<IconBan />}
              onClick={handleBlock}
              disabled={isPending || !!follower.blocked}
            >
              {follower.blocked ? "Already blocked" : "Block & purge"}
            </Menu.Item>
          </Role>
        </Menu.Dropdown>
      </Menu>
    </Role>
  );
}
