"use client";

import { ImageSpritePreview } from "@/app/[locale]/my/components/image-sprite-preview";
import { RecordingMenu } from "@/app/[locale]/my/components/recording-menu";
import {
  FollowerTypeEnum,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import { Group, Loader, SimpleGrid, Stack, Text } from "@mantine/core";
import { useIntersection } from "@mantine/hooks";
import { IconDownload, IconEye } from "@tabler/icons-react";
import { useInfiniteQuery } from "@tanstack/react-query";
import { useParams } from "next/navigation";
import { useQueryStates } from "nuqs";
import { useEffect } from "react";
import { useDateFormatter } from "../../../lib/use-date-formatter";

import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { useNow, useTranslations } from "next-intl";
import { fetchProfileRecordings } from "../actions/actions";
import { profileParsers } from "../lib/search-params";

export default function ProfileRecordings() {
  const t = useTranslations("protected.common");
  const format = useDateFormatter();
  const now = useNow();
  const params = useParams<{ type: FollowerTypeEnum; username: string }>();
  const [filters] = useQueryStates(profileParsers);

  const { data, fetchNextPage, hasNextPage, isFetchingNextPage, isLoading } =
    useInfiniteQuery({
      queryKey: ["profile-recordings", params.type, params.username, filters],
      queryFn: ({ pageParam }) =>
        fetchProfileRecordings(
          params.type,
          params.username,
          filters,
          pageParam,
        ),
      initialPageParam: 1,
      getNextPageParam: (lastPage) => {
        const { page = 1, pageSize } = lastPage.meta?.pagination ?? {};
        return lastPage.data.length === pageSize ? page + 1 : undefined;
      },
    });

  const { ref, entry } = useIntersection({ threshold: 0.5 });

  useEffect(() => {
    // Guard: only fetch next page when no video modal is open.
    // When a video modal opens (intercepted route), Mantine Modal adds
    // overflow:hidden to body causing a layout shift that re-fires the
    // intersection observer. Using window.location instead of usePathname
    // to avoid subscribing to URL changes (which causes re-renders).
    const isOnPage = !window.location.pathname.includes("/video/");
    if (entry?.isIntersecting && hasNextPage && !isFetchingNextPage && isOnPage) {
      fetchNextPage();
    }
  }, [entry?.isIntersecting, hasNextPage, isFetchingNextPage, fetchNextPage]);

  const recordings = data?.pages.flatMap((p) => p.data) ?? [];

  if (isLoading) {
    return (
      <Stack align="center" py="xl">
        <Loader size="lg" />
      </Stack>
    );
  }

  return (
    <Stack gap="md">
      <SimpleGrid cols={{ base: 1, sm: 2, md: 3, xl: 4 }} spacing="lg">
        {recordings.map((rec) => {
          const isRecording = rec.sources?.some(
            (s) =>
              s.state === SourceStateEnum.Recording ||
              s.state === SourceStateEnum.Uploading,
          );

          return (
            <Stack key={rec.documentId} gap={4}>
              <ImageSpritePreview
                recording={rec}
                username={params.username}
                type={params.type}
              />

              <Group justify="space-between" align="center" wrap="nowrap">
                <Stack gap={0} style={{ minWidth: 0 }}>
                  <Text size="sm" suppressHydrationWarning>
                    {isRecording
                      ? t("recordings.liveAgo", {
                          time: safeRelativeTime(format, rec.createdAt, {
                            style: "narrow",
                            now,
                          }),
                        })
                      : format.dateTime(new Date(rec.createdAt || ""), {
                          dateStyle: "medium",
                          timeStyle: "short",
                        })}
                  </Text>
                  <Group gap={8} c="dimmed" wrap="nowrap">
                    <Group gap={3} wrap="nowrap">
                      <IconEye size={12} />
                      <Text size="xs">{rec.viewsCount ?? 0}</Text>
                    </Group>
                    <Group gap={3} wrap="nowrap">
                      <IconDownload size={12} />
                      <Text size="xs">{rec.downloadsCount ?? 0}</Text>
                    </Group>
                  </Group>
                </Stack>
                {!isRecording ? (
                  <RecordingMenu
                    recording={rec}
                    username={params.username}
                    type={params.type}
                  />
                ) : null}
              </Group>
            </Stack>
          );
        })}
      </SimpleGrid>

      {hasNextPage && !isFetchingNextPage && (
        <div ref={ref} style={{ height: 20 }} />
      )}
      {isFetchingNextPage && (
        <Loader size="sm" style={{ alignSelf: "center" }} />
      )}
      {!hasNextPage && recordings.length > 0 && (
        <Text ta="center" c="dimmed" size="sm" suppressHydrationWarning>
          {t("recordings.noRecordings")}
        </Text>
      )}
    </Stack>
  );
}
