"use client";

import { ClipPreview } from "@/app/[locale]/(protected)/my-clips/components/clip-preview";
import { Clip } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Card, Flex, Stack, Text, Tooltip } from "@mantine/core";
import { IconDownload } from "@tabler/icons-react";

interface ProfileClipCardProps {
  clip: Clip;
  locale: string;
}

export function ProfileClipCard({ clip, locale }: ProfileClipCardProps) {
  const handleDownload = () => {
    const link = document.createElement("a");
    link.href = `/clip/${clip.documentId}/clip.mp4?download`;
    link.download = `${clip.title || "clip"}.mp4`;
    link.click();
  };

  return (
    <Card radius="md" withBorder>
      <Stack gap="xs">
        <Flex justify="space-between" align="center">
          <Text fw="bold" fz="xs" lineClamp={1}>
            {clip.title}
          </Text>
          <Tooltip label="Download">
            <ActionIcon variant="filled" color="green" onClick={handleDownload}>
              <IconDownload size={18} />
            </ActionIcon>
          </Tooltip>
        </Flex>

        <ClipPreview clip={clip} type={clip.follower?.type} locale={locale} />
      </Stack>
    </Card>
  );
}
