import publicApi from "@/lib/public-api";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";

const s3 = new S3Client({
  region: "fsn1",
  endpoint: "https://fsn1.your-objectstorage.com",
  credentials: {
    accessKeyId: process.env.S3_ACCESS_KEY!,
    secretAccessKey: process.env.S3_SECRET_KEY!,
  },
});

export async function GET(
  request: Request,
  { params }: { params: Promise<{ documentId: string }> },
) {
  const { documentId } = await params;

  const { data } = await publicApi.recording.getRecordingsId({
    id: documentId,
    populate: {
      sources: {
        fields: ["path"],
        filters: {
          state: {
            $eq: "done",
          },
        },
      },
    },
  });

  if (!data.data) {
    return new Response("Not found", { status: 404 });
  }

  const recording = data.data as unknown as Recording;

  const path = recording.sources?.at(0)?.path;
  if (!path) {
    return new Response("Not found", { status: 404 });
  }

  const command = new GetObjectCommand({
    Bucket: process.env.MEDIA_BUCKET!,
    Key: `${path.substring(1)}preview.jpg`, // substring(1) just remove the start "/"
  });
  const response = await s3.send(command);

  return new Response(response.Body as ReadableStream, {
    headers: {
      "Content-Type": response.ContentType || "application/octet-stream",
      "Cache-Control": "public, max-age=31536000",
    },
  });
}
