"use client";

import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import {
  MediaControlBar,
  MediaController,
  MediaFullscreenButton,
  MediaMuteButton,
  MediaPlayButton,
  MediaPosterImage,
  MediaTimeRange,
  MediaVolumeRange,
} from "@/app/[locale]/(protected)/components/video/media-chrome";
import {
  Clip,
  ClipTypeEnum,
  FollowerTypeEnum,
} from "@/lib/types/strapi-autogenerated";
import { Box } from "@mantine/core";
import { useEffect, useRef } from "react";

import "hls-video-element";
import "media-chrome";

const activeVideos = new Set<() => void>();

interface Props {
  clip: Clip;
  type?: ClipTypeEnum;
  locale: string;
}

export function ClipPreview({ clip, type, locale }: Props) {
  const controllerRef = useRef<HTMLElement>(null);
  const previewUrl = `/clip/${clip.documentId}/thumbnail.jpg`;
  const src = `/clip/${clip.documentId}/clip.mp4`;
  const subtitlesUrl = `/clip/${clip.documentId}/subtitles.vtt?locale=${locale}`;

  useEffect(() => {
    const controller = controllerRef.current;
    if (!controller) return;

    const media = controller.querySelector(
      "video, hls-video",
    ) as HTMLVideoElement;
    if (!media) return;

    const pause = () => media.pause();
    activeVideos.add(pause);

    const handlePlay = () => {
      activeVideos.forEach((p) => {
        if (p !== pause) p();
      });
    };

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (!entry.isIntersecting) {
          media.pause();
        }
      },
      { threshold: 0.5 },
    );

    media.addEventListener("play", handlePlay);
    observer.observe(controller);

    return () => {
      activeVideos.delete(pause);
      media.removeEventListener("play", handlePlay);
      observer.disconnect();
    };
  }, []);

  return (
    <div style={{ position: "relative", overflow: "hidden" }}>
      <MediaController
        ref={controllerRef}
        style={{
          width: "100%",
          height: "clamp(200px, 40vh, 400px)",
        }}
      >
        <video
          src={src}
          slot="media"
          crossOrigin="anonymous"
          playsInline
          preload="metadata"
        >
          <track
            kind="subtitles"
            src={subtitlesUrl}
            srcLang={locale}
            label={locale === "en" ? "English" : "Subtitles"}
            default
          />
        </video>

        <MediaPosterImage slot="poster" src={previewUrl} />
        <MediaPlayButton slot="centered-chrome" />

        <MediaControlBar>
          <MediaTimeRange />
          <Box className="volume-hover-container">
            <MediaVolumeRange />
            <MediaMuteButton />
          </Box>
          <MediaFullscreenButton />
        </MediaControlBar>
      </MediaController>

      {type && (
        <FollowerTypeIcon
          type={type as unknown as FollowerTypeEnum}
          color="black"
          opacity={0.8}
          pos="absolute"
          top={20}
          right={18}
          style={{ pointerEvents: "none" }}
        />
      )}
    </div>
  );
}
