// No "use client" needed
import { Clip } from "@/lib/types/strapi-autogenerated";
import { ScrollArea } from "@mantine/core";

export function ClipSlider({ clips }: { clips: Clip[] }) {
  return (
    <ScrollArea type="never" scrollbarSize={0} mt="xl">
      <div
        style={{
          display: "flex",
          gap: "16px",
          justifyContent: "center",
          minWidth: "max-content",
        }}
      >
        {clips.map((clip) => (
          <video
            key={clip.documentId}
            poster={`/clip/${clip.documentId}/thumbnail.jpg`}
            preload="metadata"
            autoPlay
            muted
            loop
            playsInline
            height={300}
            style={{
              flexShrink: 0,
              pointerEvents: "none",
              borderRadius: "8px",
            }}
          >
            <source
              src={`/clip/${clip.documentId}/preview.mp4`}
              type="video/mp4"
            />
          </video>
        ))}
      </div>
    </ScrollArea>
  );
}
