import { generateProfileUrl } from "@/app/lib/profile-url";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Button,
  Container,
  Flex,
  SimpleGrid,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconArrowLeft, IconArrowRight } from "@tabler/icons-react";
import { Metadata } from "next";
import { getFormatter, getLocale, getTranslations } from "next-intl/server";
import { headers } from "next/headers";
import {
  fetchProfileRecordings,
  getRecordingById,
} from "../../actions/actions";
import { ImageVideoPreview } from "../../components/image-video-preview";
import { VideoPlayer } from "../../components/video-player";

interface PageProps {
  params: Promise<{
    username: string;
    type: string;
    id: string;
  }>;
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const t = await getTranslations("video");
  const { id, username, type } = await params;
  const data = await getRecordingById(id);
  const format = await getFormatter();

  const platformName = type.charAt(0).toUpperCase() + type.slice(1);
  const creatorName =
    data.follower?.nickname || data.follower?.username || username;
  const recordedDate = format.dateTime(new Date(data.createdAt || ""), {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  const sources = data.sources ?? [];
  const thumbnailUrl = `${process.env.NEXT_PUBLIC_BASE_URL}/video/${data.documentId}/screenshot.jpg`;

  const duration = sources.reduce(
    (acc, source) => acc + (source.duration || 0),
    0,
  );
  const durationFormatted = `${Math.floor(duration / 60)}m ${Math.round(
    duration % 60,
  )}s`;

  const translation = {
    creatorName,
    recordedDate,
    platform: platformName,
    duration: durationFormatted,
    username,
  };

  return {
    title: t("meta.title", translation),
    description: t("meta.description", translation),
    keywords: t("meta.keywords", translation).split(", "),
    openGraph: {
      title: t("meta.title", translation),
      description: t("meta.description", translation),
      type: "video.other",
      url: generateProfileUrl(data.follower, true) + `/video/${id}`,
      siteName: "Live Stream Recorder",
      ...(thumbnailUrl && {
        images: [
          {
            url: thumbnailUrl,
            width: 1280,
            height: 720,
            alt: `${creatorName} stream thumbnail`,
          },
        ],
        videos: [
          {
            url: `${generateProfileUrl(data.follower, true)}/video/${id}`,
            width: 1280,
            height: 720,
            type: "text/html",
          },
        ],
      }),
    },
    twitter: {
      card: "summary_large_image",
      title: t("meta.title", translation),
      description: t("meta.description", translation),
      ...(thumbnailUrl && {
        images: [thumbnailUrl],
      }),
    },
    alternates: {
      canonical: generateProfileUrl(data.follower, true) + `/video/${id}`,
    },
  };
}

export default async function VideoPage({ params }: PageProps) {
  const headersList = await headers();
  const userAgent = headersList.get("user-agent") || "";

  const { id, type, username } = await params;
  const locale = await getLocale();
  const tp = await getTranslations("profile");
  const t = await getTranslations("video");
  const data = await getRecordingById(id);
  const format = await getFormatter();
  const sources = data.sources ?? [];

  const { data: recordingsData } = await fetchProfileRecordings(type, username);
  const recordings = recordingsData ?? [];
  const hasRecordings = recordings.length > 0;

  const previewUrl = `/video/${data.documentId}/screenshot.jpg`;

  const duration = sources.reduce(
    (acc, source) => acc + (source.duration || 0),
    0,
  );

  const creatorName =
    data.follower?.nickname || data.follower?.username || "Unknown";
  const recordedDate = format.dateTime(new Date(data.createdAt || ""), {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  const videoJsonLd = {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: t("jsonLd.name", { creatorName, recordedDate }),
    description: t("jsonLd.description", { creatorName, recordedDate }),
    thumbnailUrl: `${
      process.env.NEXT_PUBLIC_BASE_URL
    }/video/${data.documentId}/screenshot.jpg`,
    uploadDate: data.createdAt,
    duration: `PT${Math.floor(duration / 60)}M${Math.round(duration % 60)}S`,
    contentUrl: `${
      process.env.NEXT_PUBLIC_BASE_URL
    }/video/${data.documentId}/playlist.m3u8`,
    embedUrl: `${generateProfileUrl(data.follower, true)}/video/${
      data.documentId
    }`,
    publisher: {
      "@type": "Organization",
      name: "Live Stream Recorder",
      url: process.env.NEXT_PUBLIC_BASE_URL,
    },
    ...(data.follower && {
      author: {
        "@type": "Person",
        name: creatorName,
        url: generateProfileUrl(data.follower, true),
      },
    }),
    inLanguage: locale,
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(videoJsonLd) }}
      />
      <Container size="lg">
        <Flex gap="xs" justify="center" align="center" direction="column">
          <VideoPlayer
            previewUrl={previewUrl}
            documentId={id}
            userAgent={userAgent}
          />

          <Title order={1} c="dimmed" size="xl" fw="400">
            {t("jsonLd.name", { creatorName, recordedDate })}
          </Title>

          <Button
            component="a"
            href={generateProfileUrl(data.follower)}
            variant="light"
            leftSection={
              locale === "ar" ? (
                <IconArrowRight size={16} />
              ) : (
                <IconArrowLeft size={16} />
              )
            }
          >
            {t("backToProfile", { username: creatorName })}
          </Button>
        </Flex>
        {hasRecordings ? (
          <Stack mt={100}>
            <Title order={2} size="lg" ta="center" fw="400">
              {t("otherRecordingsBy", { username: creatorName })}
            </Title>
            <SimpleGrid cols={{ base: 1, sm: 2 }} spacing="lg">
              {recordings?.map((rec) => (
                <Stack key={rec.documentId} gap={4}>
                  <ImageVideoPreview
                    recording={rec}
                    type={type as unknown as FollowerTypeEnum}
                  />
                  <Text size="xs" suppressHydrationWarning>
                    {tp("recorded", {
                      date: format.dateTime(new Date(rec.createdAt || ""), {
                        year: "numeric",
                        month: "short",
                        day: "numeric",
                        hour: "numeric",
                        minute: "2-digit",
                      }),
                    })}
                  </Text>
                </Stack>
              ))}
            </SimpleGrid>
          </Stack>
        ) : null}
      </Container>
    </>
  );
}
