import { ImageSpritePreview } from "@/app/[locale]/(protected)/components/image-sprite-preview";
import { RecordingMenu } from "@/app/[locale]/(protected)/components/recording-menu";
import { FollowerTypeEnum, Recording } from "@/lib/types/strapi-autogenerated";
import {
  Box,
  Button,
  Divider,
  Flex,
  Group,
  Image,
  SimpleGrid,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconBrandSafari, IconChevronRight } from "@tabler/icons-react";
import { getFormatter, getTranslations } from "next-intl/server";
import Link from "next/link";

interface PlatformWithRecordings {
  name: string;
  file: string;
  color: string;
  colorCss: string;
  type: FollowerTypeEnum;
  recordings: Recording[];
}

interface DiscoverSectionProps {
  discoverPromise: Promise<PlatformWithRecordings[]>;
}

export async function DiscoverSection({
  discoverPromise,
}: DiscoverSectionProps) {
  const t = await getTranslations("protected.dashboard");
  const format = await getFormatter();
  const platformDataRaw = await discoverPromise;

  const platformData = platformDataRaw.filter(
    (platform) => platform.recordings.length > 0,
  );

  if (platformData.length === 0) {
    return null;
  }

  return (
    <>
      <Divider />
      <Box
        style={{
          background: "linear-gradient(150deg, #FFCCCD , #F8888A)",
        }}
        py="sm"
        px={{ base: "xs", sm: "md" }}
      >
        <Flex justify="space-between" align="center" w="100%">
          <Stack gap={2}>
            <Flex gap="xs" align="center">
              <IconBrandSafari size={24} color="black" />
              <Title order={1} size="lg" c="black">
                {t("discoverSection")}
              </Title>
            </Flex>
          </Stack>
        </Flex>
      </Box>
      <Divider />

      {platformData.map((platform) => (
        <Stack key={platform.name} gap="md" p="md">
          <Flex justify="space-between" align="center">
            <Flex gap="xs" align="center">
              <Image
                src={platform.file}
                alt={platform.name}
                w={24}
                h={24}
                style={{ filter: "brightness(0) invert(1)" }}
              />
              <Title order={2} size="h4">
                {platform.name}
              </Title>
            </Flex>
            <Link href={`/explore?type=${platform.type}`}>
              <Button
                variant="outline"
                color="gray"
                size="sm"
                rightSection={<IconChevronRight size={16} />}
              >
                {t("browseAll")}
              </Button>
            </Link>
          </Flex>

          <SimpleGrid cols={{ base: 2, sm: 2, md: 4 }} spacing="md">
            {platform.recordings.map((rec) => (
              <Stack key={rec.documentId} gap="4">
                <Box
                  pos="relative"
                  style={{ opacity: rec.hidden ? 0.5 : 1 }}
                >
                  <ImageSpritePreview
                    recording={rec}
                    username={rec.follower?.username || ""}
                    type={platform.type}
                  />
                </Box>

                <Group justify="space-between" align="center">
                  <Text size="xs" suppressHydrationWarning>
                    {format.dateTime(new Date(rec.createdAt || ""), {
                      dateStyle: "medium",
                      timeStyle: "short",
                    })}
                  </Text>
                  {rec.follower && (
                    <RecordingMenu
                      recording={rec}
                      username={rec.follower.username}
                      type={rec.follower.type}
                    />
                  )}
                </Group>
              </Stack>
            ))}
          </SimpleGrid>
        </Stack>
      ))}
    </>
  );
}
