import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { FollowerWithMeta } from "@/lib/types/strapi-autogenerated";
import {
  Anchor,
  Avatar,
  Box,
  Card,
  Group,
  Scroller,
  Stack,
  Text,
} from "@mantine/core";
import { IconVideo } from "@tabler/icons-react";
import { getFormatter } from "next-intl/server";
import NextImage from "next/image";

interface LatestFollowersSectionProps {
  followersPromise: Promise<FollowerWithMeta[]>;
}

export async function LatestFollowersSection({
  followersPromise,
}: LatestFollowersSectionProps) {
  const latestFollowers = await followersPromise;
  const format = await getFormatter();

  return (
    <Scroller p="md">
      <Group gap="sm" wrap="nowrap">
        {latestFollowers.map((follower) => {
          const avatarUrl = follower.avatar?.url
            ? generateAvatarUrl(follower.avatar.url)
            : null;

          return (
            <Anchor
              key={follower.documentId}
              href={getProfileUrl(follower)}
              underline="never"
              style={{ flexShrink: 0 }}
            >
              <Card
                w={200}
                padding={0}
                radius="lg"
                style={{
                  background: "rgba(255, 255, 255, 0.03)",
                  border: "1px solid rgba(255, 255, 255, 0.08)",
                  cursor: "pointer",
                  overflow: "hidden",
                }}
              >
                {/* Top half — avatar as banner */}
                <Box
                  h={80}
                  style={{
                    backgroundImage: avatarUrl
                      ? `url(${avatarUrl})`
                      : "linear-gradient(135deg, #1a1b1e, #2c2e33)",
                    backgroundSize: "cover",
                    backgroundPosition: "top",
                    filter: "brightness(0.6)",
                  }}
                />

                {/* Avatar overlapping the banner */}
                <Stack align="center" mt={-40} gap="sm" pb="md" px="md">
                  <Avatar
                    size={72}
                    radius="xl"
                    style={{
                      border: "3px solid var(--mantine-color-dark-7)",
                    }}
                  >
                    {avatarUrl && (
                      <NextImage
                        src={avatarUrl}
                        alt={follower.username || ""}
                        width={72}
                        height={72}
                      />
                    )}
                  </Avatar>

                  <Stack gap={2} align="center" w="100%">
                    <Group gap={4} align="center" wrap="nowrap">
                      <Text fw={700} size="sm" c="white" lineClamp={1}>
                        {follower.nickname || follower.username}
                      </Text>
                      <FollowerTypeIcon
                        type={follower.type}
                        color="transparent"
                        size={16}
                        style={{ flexShrink: 0 }}
                      />
                    </Group>
                    <Text size="xs" c="dimmed" ta="center" lineClamp={1}>
                      @{follower.username}
                    </Text>
                  </Stack>

                  <Group gap="xs" align="center">
                    <IconVideo size={14} color="var(--mantine-color-dimmed)" />
                    <Text size="xs" c="dimmed">
                      {follower.totalRecordings || 0} videos
                    </Text>
                  </Group>

                  {follower.createdAt && (
                    <Text size="xs" c="dimmed">
                      Added {format.relativeTime(new Date(follower.createdAt))}
                    </Text>
                  )}
                </Stack>
              </Card>
            </Anchor>
          );
        })}
      </Group>
    </Scroller>
  );
}
