import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Anchor, Avatar, Card, Flex, Stack, Text } from "@mantine/core";
import NextImage from "next/image";

interface LatestFollowersSectionProps {
  followersPromise: Promise<Follower[]>;
}

export async function LatestFollowersSection({
  followersPromise,
}: LatestFollowersSectionProps) {
  const latestFollowers = await followersPromise;

  return (
    <Flex gap={20} wrap="wrap" p="md">
      {latestFollowers.map((follower) => (
        <div
          key={follower.documentId}
          style={{
            flex: "1 1 calc(16.666% - 17px)",
            minWidth: "140px",
            maxWidth: "180px",
          }}
        >
          <Anchor href={getProfileUrl(follower)} underline="never">
            <Card
              padding={16}
              style={{
                background: "rgba(255, 255, 255, 0.02)",
                border: "1px solid rgba(255, 255, 255, 0.06)",
                borderRadius: "16px",
                cursor: "pointer",
                textAlign: "center",
              }}
            >
              <Stack align="center" gap={8}>
                <div style={{ position: "relative" }}>
                  <Avatar size={64} radius="xl">
                    <NextImage
                      src={generateAvatarUrl(follower.avatar?.url)}
                      alt={follower.username}
                      width={64}
                      height={64}
                      quality={75}
                    />
                  </Avatar>
                  <FollowerTypeIcon
                    pos="absolute"
                    color="transparent"
                    type={follower.type}
                    top="50%"
                    left="50%"
                    size={32}
                    opacity={0.8}
                    style={{ transform: "translate(-50%, -50%)" }}
                  />
                </div>
                <div>
                  <Text fw={600} size="sm" style={{ color: "#f1f5f9" }}>
                    {follower.nickname || follower.username}
                  </Text>
                  <Text size="xs" style={{ color: "#64748b" }}>
                    @{follower.username}
                  </Text>
                </div>
              </Stack>
            </Card>
          </Anchor>
        </div>
      ))}
    </Flex>
  );
}
