import { getRecordings } from "@/app/actions/recordings";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import InfiniteRecordings from "../_components/infinity-recordings";

export default async function FollowingsPage() {
  const response = await getRecordings(ScopeEnum.Following, 1);

  const data = response.data || [];
  const meta = response.meta;

  return (
    <section>
      {data.length === 0 ? (
        <p>No recording found yet!</p>
      ) : (
        <InfiniteRecordings
          initialData={data}
          initialPagination={meta}
          initialSort="createdAt:asc"
        />
      )}
    </section>
  );
}
