import { getRecordings } from "@/app/actions/recordings";

import { SortOptions } from "@/lib/types/filtering";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import InfiniteRecordings from "./_components/infinity-recordings";

export default async function FollowingsPage() {
  const response = await getRecordings({
    scope: ScopeEnum.Following,
    page: 1,
    sort: SortOptions.createdAtDesc,
  });

  const data = response.data || [];
  const meta = response.meta;

  return (
    <section>
      {data.length === 0 ? (
        <p>No recording found yet!</p>
      ) : (
        <InfiniteRecordings
          initialData={data}
          initialPagination={meta}
          initialSort={SortOptions.createdAtDesc}
        />
      )}
    </section>
  );
}
