// components/infinite-followers.tsx
"use client";

import {
  FollowerWithMeta,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import {
  Accordion,
  AccordionControlProps,
  Anchor,
  Avatar,
  Box,
  Center,
  Flex,
  Group,
  Image,
  Loader,
  Pagination,
  SimpleGrid,
  Stack,
  Text,
  useMatches,
} from "@mantine/core";
import Link from "next/link";

import { ImageVideoPreview } from "@/app/[locale]/(protected)/components/image-video-preview";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { IconCalendarPlus, IconVideo } from "@tabler/icons-react";
import { useQuery } from "@tanstack/react-query";
import { useFormatter, useNow, useTranslations } from "next-intl";
import { useState } from "react";
import OpenSocial, { getProfileUrl } from "../../../../components/open-social";
import { CountryFlag } from "../../components/country-flag";
import FollowButton from "../../components/follow-button";
import { FollowerTypeIcon } from "../../components/follower-type-icon";
import UnfollowButton from "../../components/unfollow-button";
import { getRecordings } from "../actions/fetch-followers";

interface Props {
  follower: FollowerWithMeta;
  isOpen: boolean;
}

export default function FollowerItem({ follower, isOpen }: Props) {
  const [page, setPage] = useState(1);
  const t = useTranslations("protected.common");
  const now = useNow({ updateInterval: 1000 * 30 });
  const format = useFormatter();
  const isMobile = useMatches({
    base: true,
    sm: false,
  });

  const { data, isLoading } = useQuery({
    queryKey: ["recordings", follower.username, follower.type, page],
    queryFn: () => getRecordings(follower.username, follower.type, page),
    enabled: isOpen,
    staleTime: 1000 * 60 * 5,
  });

  const recordings = data?.data ?? [];
  const totalPages = data?.meta?.pagination?.pageCount ?? 1;

  return (
    <Accordion.Item key={follower.documentId} value={follower.username}>
      <AccordionControl follower={follower}>
        <Group>
          <Box pos="relative" visibleFrom="sm">
            <Avatar size="lg">
              <Image
                src={generateAvatarUrl(follower.avatar?.url)}
                alt={"Avatar"}
                width={60}
                height={60}
              />
            </Avatar>

            {follower.type && (
              <FollowerTypeIcon
                pos="absolute"
                color="transparent"
                type={follower.type}
                top="50%"
                left="50%"
                size={50}
                opacity={0.5}
                style={{ transform: "translate(-50%, -50%)" }}
              />
            )}
          </Box>

          <Stack gap={2}>
            <Group gap="xs">
              <Box pos="relative" hiddenFrom="sm">
                <Avatar
                  size="md"
                  src={generateAvatarUrl(follower.avatar?.url)}
                  styles={{
                    image: {
                      transform: "scale(2)",
                      objectFit: "cover",
                    },
                  }}
                />

                {follower.type && (
                  <FollowerTypeIcon
                    pos="absolute"
                    color="transparent"
                    type={follower.type}
                    top="50%"
                    left="50%"
                    size={25}
                    style={{ transform: "translate(-50%, -50%)" }}
                  />
                )}
              </Box>

              <Anchor component={Link} href={getProfileUrl(follower)} size="md">
                <Text size="lg" truncate maw={isMobile ? 100 : 200} fw="bold">
                  {follower.username}
                </Text>
              </Anchor>
              {follower.country ? (
                <CountryFlag
                  country={follower.country}
                  countryCode={follower?.countryCode}
                />
              ) : null}
            </Group>

            <Group gap="xs">
              <Group gap={4}>
                <IconCalendarPlus size={14} />
                <Text size="sm" c="dimmed" suppressHydrationWarning>
                  {t("followers.addedAgo", {
                    time: format.relativeTime(
                      new Date(follower.createdAt || ""),
                      { now },
                    ),
                  })}
                </Text>
              </Group>
              <Group gap={4}>
                <IconVideo size={14} />
                <Text size="sm" c="dimmed" suppressHydrationWarning>
                  {t("recordings.videoCount", {
                    count: follower.totalRecordings!,
                  })}
                </Text>
              </Group>
            </Group>
          </Stack>
        </Group>
      </AccordionControl>
      <Accordion.Panel>
        {isLoading ? (
          <Stack align="center" py="xl">
            <Loader size="sm" />
          </Stack>
        ) : recordings.length > 0 ? (
          <Stack mt="lg" gap="lg">
            <SimpleGrid cols={{ sm: 2, md: 3, xl: 4 }} spacing="lg">
              {recordings.map((rec) => {
                const isRecording = rec.sources?.some(
                  (s) => s.state === SourceStateEnum.Recording,
                );

                return (
                  <Stack key={rec.documentId} gap="4">
                    <ImageVideoPreview
                      recording={rec}
                      username={follower.username}
                      type={follower.type}
                    />

                    <Text size="xs" suppressHydrationWarning>
                      {isRecording
                        ? t("recordings.liveAgo", {
                            time: format.relativeTime(
                              new Date(rec.createdAt || ""),
                              {
                                style: "narrow",
                                now,
                              },
                            ),
                          })
                        : t("recordings.recordedAgo", {
                            time: format.relativeTime(
                              new Date(rec.createdAt || ""),
                              { now },
                            ),
                          })}
                    </Text>
                  </Stack>
                );
              })}
            </SimpleGrid>

            {totalPages > 1 && (
              <Pagination
                value={page}
                onChange={setPage}
                total={totalPages}
                siblings={1}
                style={{ alignSelf: "center" }}
              />
            )}
          </Stack>
        ) : (
          <Box
            mt="lg"
            pos="relative"
            w={160}
            h={284}
            style={{
              overflow: "hidden",
              borderRadius: "var(--mantine-radius-md)",
            }}
          >
            <Image
              alt="no videos"
              radius="md"
              src="/assets/placeholder/180x280/1a1b1e/909296?text=No videos yet"
              w={160}
              h={284}
              loading="lazy"
              style={{ objectFit: "cover", opacity: 0.8 }}
            />
          </Box>
        )}
      </Accordion.Panel>
    </Accordion.Item>
  );
}

function AccordionControl({
  follower,
  ...props
}: AccordionControlProps & { follower: FollowerWithMeta }) {
  const isMobile = useMatches({
    base: true,
    sm: false,
  });
  return (
    <Center>
      <Accordion.Control {...props} />
      <Flex gap="xs" align="center" mx="md">
        {isMobile ? null : <OpenSocial follower={follower} />}

        {follower.isFollowing ? (
          <>
            <UnfollowButton username={follower.username} type={follower.type} />
          </>
        ) : (
          <FollowButton username={follower.username} type={follower.type} />
        )}
      </Flex>
    </Center>
  );
}
