"use client";
import { Faq } from "@/lib/types/strapi-autogenerated";
import { Accordion, SimpleGrid, Text } from "@mantine/core";

export function Questions({
  leftColumn,
  rightColumn,
}: {
  leftColumn: Faq[];
  rightColumn: Faq[];
}) {
  return (
    <SimpleGrid cols={{ base: 1, md: 2 }} spacing="lg">
      <Accordion variant="separated">
        {leftColumn.map((faq) => (
          <Accordion.Item key={faq.documentId} value={faq.documentId!}>
            <Accordion.Control>{faq.title}</Accordion.Control>
            <Accordion.Panel>
              <Text c="dimmed">{faq.description}</Text>
            </Accordion.Panel>
          </Accordion.Item>
        ))}
      </Accordion>

      <Accordion variant="separated">
        {rightColumn.map((faq) => (
          <Accordion.Item key={faq.documentId} value={faq.documentId!}>
            <Accordion.Control>{faq.title}</Accordion.Control>
            <Accordion.Panel>
              <Text c="dimmed">{faq.description}</Text>
            </Accordion.Panel>
          </Accordion.Item>
        ))}
      </Accordion>
    </SimpleGrid>
  );
}
