"use client";
import dayjs from "@/app/lib/dayjs";
import { ChangeLog } from "@/lib/types/strapi-autogenerated";
import {
  Badge,
  Divider,
  Group,
  Paper,
  Text,
  ThemeIcon,
  Timeline,
} from "@mantine/core";
import {
  IconCalendar,
  IconGitBranch,
  IconRocket,
  IconSparkles,
} from "@tabler/icons-react";
import { marked } from "marked";

function getVersionColor(version: string): string {
  if (version.startsWith("0.")) return "blue";
  if (version.startsWith("1.")) return "teal";
  if (version.startsWith("2.")) return "violet";
  return "gray";
}

const icons = [IconRocket, IconSparkles, IconGitBranch];

export function ChangeLogTimeline({ changelogs }: { changelogs: ChangeLog[] }) {
  return (
    <Timeline active={changelogs.length} bulletSize={40} lineWidth={2}>
      {changelogs.map((entry, index) => {
        const Icon = icons[index % icons.length];
        const color = getVersionColor(entry?.version || "0.0.0");

        return (
          <Timeline.Item
            key={entry.id}
            bullet={
              <ThemeIcon
                size={40}
                radius="xl"
                variant="gradient"
                gradient={{
                  from: color,
                  to: color === "blue" ? "cyan" : color,
                  deg: 135,
                }}
              >
                <Icon size={20} stroke={1.5} />
              </ThemeIcon>
            }
          >
            <Paper p="lg" radius="md" withBorder bg="dark">
              <Group justify="space-between" mb="sm" wrap="nowrap">
                <Badge
                  size="lg"
                  variant="light"
                  color={color}
                  radius="sm"
                  ff="monospace"
                >
                  v{entry.version}
                </Badge>
                <Group gap="xs" c="dimmed">
                  <IconCalendar size={14} />
                  <Text
                    size="sm"
                    title={dayjs(entry.createdAt).format("MMMM D, YYYY")}
                  >
                    {dayjs(entry.createdAt).fromNow()}
                  </Text>
                </Group>
              </Group>

              <Divider my="sm" />

              {entry.body ? (
                <div
                  dangerouslySetInnerHTML={{
                    __html: marked.parse(entry.body) as string,
                  }}
                />
              ) : (
                <Text size="sm" c="dimmed" fs="italic">
                  No description provided for this release.
                </Text>
              )}

              <Text size="xs" c="dimmed" mt="md">
                Published {dayjs(entry.publishedAt).format("MMMM D, YYYY")}
              </Text>
            </Paper>
          </Timeline.Item>
        );
      })}
    </Timeline>
  );
}
