// components/infinite-followers.tsx
"use client";

import dayjs from "@/app/lib/dayjs";
import {
  FollowerWithMeta,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import {
  Anchor,
  Avatar,
  Box,
  Card,
  Flex,
  Grid,
  Group,
  Image,
  SimpleGrid,
  Stack,
  Text,
  useMatches,
} from "@mantine/core";
import Link from "next/link";

import { ImageVideoPreview } from "@/app/[locale]/(protected)/components/image-video-preview";
import OpenSocial, { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { IconCalendarPlus, IconVideo } from "@tabler/icons-react";
import { CountryFlag } from "../../components/country-flag";
import FollowButton from "../../components/follow-button";
import UnfollowButton from "../../components/unfollow-button";

interface Props {
  follower: FollowerWithMeta;
}

export default function FollowerItem({ follower }: Props) {
  const cardPadding = useMatches({
    base: "sm",
    sm: "md",
    md: "lg",
  });

  const mawTruncate = useMatches({
    base: 200,
    md: 120,
  });

  return (
    <Grid.Col key={follower.documentId} span={12}>
      <Card shadow="sm" padding={cardPadding} radius="md" h="100%" withBorder>
        <Flex justify="space-between">
          <Group>
            <Anchor component={Link} href={getProfileUrl(follower)}>
              <Avatar
                size="lg"
                src={generateAvatarUrl(follower.avatar?.url)}
                styles={{
                  image: {
                    transform: "scale(2)",
                    objectFit: "cover",
                  },
                }}
              />
            </Anchor>

            <Stack gap={2}>
              <Group gap="xs">
                <Anchor
                  component={Link}
                  href={getProfileUrl(follower)}
                  size="md"
                >
                  <Text size="lg" truncate maw={mawTruncate} fw="bold">
                    {follower.username}
                  </Text>
                </Anchor>
                {follower.country ? (
                  <CountryFlag
                    country={follower.country}
                    countryCode={follower?.countryCode}
                  />
                ) : null}
              </Group>

              <Group gap="xs">
                <Group gap={4}>
                  <IconCalendarPlus size={14} />
                  <Text size="sm" c="dimmed">
                    Added {dayjs(follower.createdAt).fromNow()}
                  </Text>
                </Group>
                <Group gap={4}>
                  <IconVideo size={14} />
                  <Text size="sm" c="dimmed">
                    {follower.totalRecordings}{" "}
                    {follower.totalRecordings === 1 ? "video" : "videos"}
                  </Text>
                </Group>
              </Group>
            </Stack>
          </Group>

          <Flex gap="xs" justify="right" align="center">
            <OpenSocial follower={follower} />

            {follower.isFollowing ? (
              <>
                <UnfollowButton
                  username={follower.username}
                  type={follower.type}
                  //onSuccess={() => handleFollowed(follower.id!)}
                />
              </>
            ) : (
              <FollowButton
                username={follower.username}
                type={follower.type}
                //onSuccess={() => handleFollowed(follower.id!)}
              />
            )}
          </Flex>
        </Flex>
        {follower.recordings && follower.recordings?.length > 0 ? (
          <Box mt="lg">
            <SimpleGrid cols={{ base: 1, sm: 2, md: 3, xl: 4 }} spacing="lg">
              {follower.recordings?.map((rec, index) => {
                const isRecording = rec.sources?.some(
                  (s) => s.state === SourceStateEnum.Recording
                );

                return (
                  <Stack
                    key={rec.documentId}
                    gap="4"
                    visibleFrom={getVisibleFrom(index)}
                  >
                    <ImageVideoPreview
                      recording={rec}
                      username={follower.username}
                      type={follower.type}
                    />

                    <div>
                      <Text size="xs">
                        {isRecording
                          ? `recording for ${dayjs(rec.createdAt).fromNow(
                              true
                            )}`
                          : `recorded ${dayjs(rec.createdAt).fromNow()}`}
                      </Text>
                    </div>
                  </Stack>
                );
              })}
            </SimpleGrid>
          </Box>
        ) : (
          <Box
            mt="lg"
            pos="relative"
            w={160}
            h={284}
            style={{
              overflow: "hidden",
              borderRadius: "var(--mantine-radius-md)",
            }}
          >
            <Image
              alt="no videos"
              radius="md"
              src="https://placehold.co/180x280/1a1b1e/909296?text=No videos yet"
              w={160}
              h={284}
              loading="lazy"
              style={{ objectFit: "cover", opacity: 0.8 }}
            />
          </Box>
        )}
      </Card>
    </Grid.Col>
  );
}

const getVisibleFrom = (index: number): "sm" | "md" | "xl" | undefined => {
  if (index === 0) return undefined; // Always visible
  if (index === 1) return "sm"; // 2+ columns
  if (index === 2) return "md"; // 3+ columns
  return "xl"; // 4+ columns
};
