"use client";

import { Announcement } from "@/lib/types/strapi-autogenerated";
import { CloseButton, Flex, Text } from "@mantine/core";
import { useLocalStorage, useMounted } from "@mantine/hooks";
import { IconSpeakerphone } from "@tabler/icons-react";

interface AnnouncementBannerProps {
  announcement: Announcement | null;
}

export function AnnouncementBanner({ announcement }: AnnouncementBannerProps) {
  const mounted = useMounted();
  const [dismissedId, setDismissedId] = useLocalStorage({
    key: "dismissed-announcement",
    defaultValue: "",
  });

  if (!mounted || !announcement || dismissedId === announcement.documentId) return null;

  const colors: Record<string, string> = {
    info: "linear-gradient(150deg, #3b82f6, #2563eb)",
    warning: "linear-gradient(150deg, #f59e0b, #f97316)",
    important: "linear-gradient(150deg, #dc2626, #ef4444)",
  };

  const bg = colors[(announcement as any).type] || colors.info;

  return (
    <Flex
      align="center"
      justify="center"
      gap="xs"
      px="md"
      py={8}
      mb="sm"
      style={{
        background: bg,
        borderRadius: 8,
      }}
    >
      <IconSpeakerphone size={18} color="white" style={{ flexShrink: 0 }} />
      <Text c="white" fw={600} size="sm" style={{ flex: 1 }}>
        {announcement.message}
      </Text>
      <CloseButton
        c="white"
        size="sm"
        onClick={() => setDismissedId(announcement.documentId!)}
        style={{ flexShrink: 0 }}
      />
    </Flex>
  );
}
