"use client";

import { downgradeToFree } from "@/app/actions/downgrade";
import { trackEvent } from "@/app/lib/analytics";
import { useUser } from "@/app/providers/user-provider";
import { SubscriptionStatusEnum } from "@/lib/types/strapi-autogenerated";
import {
  Box,
  Button,
  Divider,
  List,
  Modal,
  Stack,
  Text,
  ThemeIcon,
  Title,
  useMatches,
} from "@mantine/core";
import {
  IconAlertTriangle,
  IconCrown,
  IconX,
} from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { usePathname, useRouter } from "next/navigation";
import { useTransition } from "react";

export function ExpiredSubscriptionModal() {
  const user = useUser();
  const router = useRouter();
  const pathname = usePathname();
  const [isPending, startTransition] = useTransition();
  const t = useTranslations("protected.common.expired");

  const isExpired =
    user?.role?.type === "premium" &&
    user?.subscriptionStatus === SubscriptionStatusEnum.Expired;

  const isOnPremiumPage = pathname.includes("/premium");
  const opened = isExpired && !isOnPremiumPage;

  if (!isExpired) return null;

  const isMobile = useMatches({ base: true, sm: false });

  const handleUpgrade = () => {
    trackEvent("expired_modal_upgrade");
    router.push("/premium");
  };

  const handleDowngrade = () => {
    trackEvent("expired_modal_downgrade");
    startTransition(async () => {
      const result = await downgradeToFree();
      if (result.success) {
        window.location.href = "/dashboard";
      }
    });
  };

  return (
    <Modal
      opened={opened}
      onClose={() => router.push("/premium")}
      padding={0}
      withCloseButton={false}
      radius="lg"
      size="lg"
      centered
      closeOnClickOutside={false}
      closeOnEscape={false}
      styles={{
        content: {
          border: "1px solid rgba(239, 68, 68, 0.45)",
        },
      }}
    >
      <Box
        p={isMobile ? "md" : "xl"}
        style={{
          background: "linear-gradient(135deg, #dc2626 0%, #ef4444 100%)",
          borderRadius:
            "var(--mantine-radius-lg) var(--mantine-radius-lg) 0 0",
        }}
      >
        <Stack align="center" gap="xs">
          <IconAlertTriangle size={44} color="#fbbf24" />
          <Title
            order={2}
            c="white"
            ta="center"
            size={isMobile ? "h4" : "h3"}
          >
            {t("title")}
          </Title>
          <Text c="rgba(255,255,255,0.85)" ta="center" size="sm">
            {t("subtitle")}
          </Text>
        </Stack>
      </Box>

      <Stack gap="md" p="lg">
        <Button
          onClick={handleUpgrade}
          fullWidth
          size={isMobile ? "md" : "lg"}
          radius="md"
          leftSection={<IconCrown size={18} color="#fbbf24" />}
          style={{
            background: "linear-gradient(135deg, #6366f1 0%, #a855f7 100%)",
          }}
        >
          {t("renewButton")}
        </Button>

        <Divider label={t("or")} labelPosition="center" color="dimmed" />

        <Stack gap="xs">
          <Text fw={600} size="sm" c="dimmed">
            {t("loseTitle")}
          </Text>
          <List
            spacing={4}
            size="sm"
            icon={
              <ThemeIcon color="red" size={20} radius="xl" variant="light">
                <IconX size={12} />
              </ThemeIcon>
            }
          >
            <List.Item>{t("loseCreators")}</List.Item>
            <List.Item>{t("loseFavorites")}</List.Item>
            <List.Item>{t("loseClips")}</List.Item>
            <List.Item>{t("losePremium")}</List.Item>
          </List>
        </Stack>

        <Button
          onClick={handleDowngrade}
          loading={isPending}
          fullWidth
          size="compact-md"
          radius="md"
          variant="subtle"
          color="gray"
        >
          {t("downgradeButton")}
        </Button>
      </Stack>
    </Modal>
  );
}
