"use client";

import { followUser } from "@/app/actions/followers";
import { useInvalidateRecordings } from "@/app/hooks/use-invalidate-recordings";
import { FollowRequestBody } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Button, Tooltip } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { notifications } from "@mantine/notifications";
import { IconCheck, IconUsersPlus } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useTransition } from "react";
import { CreatorUpgradeModal } from "./creator-upgrade-modal";

export default function FollowButton({
  username,
  type,
  onSuccess,
  showLabel,
}: FollowRequestBody & { onSuccess?: () => void; showLabel?: boolean }) {
  const [isPending, startTransition] = useTransition();
  const t = useTranslations("protected.common");
  const invalidateRecordings = useInvalidateRecordings();
  const [upgradeOpened, { open: openUpgrade, close: closeUpgrade }] =
    useDisclosure(false);

  const handleClick = () => {
    startTransition(async () => {
      const result = await followUser({ username, type });

      if (result.success) {
        invalidateRecordings();
        notifications.show({
          title: t("follow.successTitle"),
          message: t("follow.successMessage", { username }),
          color: "green",
          icon: <IconCheck size={16} />,
        });
        onSuccess?.();
      }

      if (result.error) {
        if (result.error === "MAX_3_FOLLOWERS") {
          openUpgrade();
        } else if (result.error === "MAX_50_FOLLOWERS") {
          notifications.show({
            title: t("follow.errorTitle"),
            message: t("followers.max50Message"),
            color: "red",
          });
        } else if (result.error === "MAX_100_FOLLOWERS") {
          notifications.show({
            title: t("follow.errorTitle"),
            message: t("followers.max100Message"),
            color: "red",
          });
        } else {
          notifications.show({
            title: t("follow.errorTitle"),
            message: result.error,
            color: "red",
          });
        }
      }
    });
  };

  return (
    <>
      <CreatorUpgradeModal opened={upgradeOpened} onClose={closeUpgrade} />

      {showLabel ? (
        <Button
          size="sm"
          radius="xl"
          leftSection={<IconUsersPlus size={18} />}
          onClick={handleClick}
          loading={isPending}
        >
          {t("follow.tooltip")}
        </Button>
      ) : (
        <Tooltip label={t("follow.tooltip")}>
          <ActionIcon
            size="lg"
            color="red"
            onClick={handleClick}
            loading={isPending}
          >
            <IconUsersPlus />
          </ActionIcon>
        </Tooltip>
      )}
    </>
  );
}
