"use client";

import { followUser } from "@/app/actions/followers";
import { FollowRequestBody } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Tooltip } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconCheck, IconUsersPlus } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useTransition } from "react";

export default function FollowButton({
  username,
  type,
  onSuccess,
}: FollowRequestBody & { onSuccess?: () => void }) {
  const [isPending, startTransition] = useTransition();
  const t = useTranslations("protected.common");

  const handleClick = () => {
    startTransition(async () => {
      const result = await followUser({ username, type });

      if (result.success) {
        notifications.show({
          title: t("follow.successTitle"),
          message: t("follow.successMessage", { username }),
          color: "green",
          icon: <IconCheck size={16} />,
        });

        onSuccess?.();
      }

      if (result.error) {
        notifications.show({
          title: t("follow.errorTitle"),
          message: result.error,
          color: "red",
        });
      }
    });
  };

  return (
    <Tooltip label={t("follow.tooltip")}>
      <ActionIcon
        size="lg"
        color="red"
        onClick={handleClick}
        loading={isPending}
      >
        <IconUsersPlus />
      </ActionIcon>
    </Tooltip>
  );
}
