"use client";

import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { Image, ImageProps } from "@mantine/core";
import { useTranslations } from "next-intl";

type FollowerTypeTextProps = {
  type: FollowerTypeEnum | undefined;
} & ImageProps;

export const FollowerTypeText = ({ type, ...props }: FollowerTypeTextProps) => {
  const t = useTranslations("protected.addFollowerForm");

  return (
    <>
      {type === FollowerTypeEnum.Tiktok && (
        <Image
          src="/tiktok.svg"
          alt={t("platforms.tiktok")}
          w={50}
          fit="contain"
          {...props}
        />
      )}
      {type === FollowerTypeEnum.Twitch && (
        <Image
          src="/twitch.svg"
          alt={t("platforms.twitch")}
          w={50}
          fit="contain"
          {...props}
        />
      )}
      {type === FollowerTypeEnum.Kick && (
        <Image
          src="/kick.svg"
          alt={t("platforms.kick")}
          w={50}
          fit="contain"
          {...props}
        />
      )}
      {type === FollowerTypeEnum.Youtube && (
        <Image
          src="/youtube.svg"
          alt={t("platforms.youtube")}
          w={50}
          fit="contain"
          {...props}
        />
      )}
      {type === FollowerTypeEnum.Afreecatv && (
        <Image
          src="/afreecatv.svg"
          alt={t("platforms.afreecatv")}
          w={50}
          fit="contain"
          {...props}
        />
      )}
      {type === FollowerTypeEnum.Pandalive && (
        <Image
          src="/pandalive.png"
          alt={t("platforms.pandalive")}
          w={50}
          fit="contain"
          {...props}
        />
      )}
    </>
  );
};
