import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ThemeIcon, ThemeIconProps } from "@mantine/core";

type FollowerTypeIconProps = {
  type: FollowerTypeEnum | undefined;
} & ThemeIconProps;

export const FollowerTypeIcon = ({ type, ...props }: FollowerTypeIconProps) => {
  const platform = streamingPlatforms.find(
    (p) => p.name.toLowerCase() === type?.toLowerCase(),
  );

  if (!platform) {
    return null;
  }

  return (
    <ThemeIcon color={platform.color} {...props}>
      <span
        style={{
          width: "90%",
          height: "90%",
          display: "block",
          backgroundColor: "currentColor",
          maskImage: `url(${platform.file})`,
          WebkitMaskImage: `url(${platform.file})`,
          maskSize: "contain",
          WebkitMaskSize: "contain",
          maskRepeat: "no-repeat",
          WebkitMaskRepeat: "no-repeat",
          maskPosition: "center",
          WebkitMaskPosition: "center",
        }}
      />
    </ThemeIcon>
  );
};
