"use client";

import { deleteRecording, hideRecording } from "@/app/actions/recording";
import { useUser } from "@/app/providers/user-provider";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Menu } from "@mantine/core";
import { IconDots, IconEyeOff, IconTrash } from "@tabler/icons-react";
import { useQueryClient } from "@tanstack/react-query";
import { useTranslations } from "next-intl";

export function RecordingMenu({ recording }: { recording: Recording }) {
  const user = useUser();
  const t = useTranslations("protected.common.recordings");
  const queryClient = useQueryClient();

  const isOwner = user?.id && recording.follower?.owner?.id === user.id;

  const handleDelete = async () => {
    if (!recording.documentId) return;
    const result = await deleteRecording(recording.documentId);
    if (result.success) {
      queryClient.invalidateQueries({
        queryKey: [
          "recordings",
          recording.follower?.username,
          recording.follower?.type,
        ],
      });
    }
  };

  const handleHide = async () => {
    if (!recording.documentId) return;
    const result = await hideRecording(recording.documentId);
    if (result.success) {
      queryClient.invalidateQueries({
        queryKey: [
          "recordings",
          recording.follower?.username,
          recording.follower?.type,
        ],
      });
    }
  };

  // Don't render if no owner actions available
  if (!isOwner) {
    return null;
  }

  return (
    <Menu shadow="md">
      <Menu.Target>
        <ActionIcon
          variant="filled"
          color="dark"
          size="md"
          onClick={(e) => e.preventDefault()}
        >
          <IconDots />
        </ActionIcon>
      </Menu.Target>
      <Menu.Dropdown>
        <Menu.Item leftSection={<IconEyeOff size={14} />} onClick={handleHide}>
          {t("hide")}
        </Menu.Item>
        <Menu.Item
          color="red"
          leftSection={<IconTrash size={14} />}
          onClick={handleDelete}
        >
          {t("delete")}
        </Menu.Item>
      </Menu.Dropdown>
    </Menu>
  );
}
