"use client";

import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { useTranslations } from "next-intl";
import { usePathname, useRouter } from "next/navigation";

type Props = {
  currentScope: string;
};

export default function ScopeFilter({ currentScope }: Props) {
  const router = useRouter();
  const pathname = usePathname();
  const t = useTranslations("protected.common");

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newScope = e.target.value;
    if (newScope === "all") {
      router.push(pathname);
    } else {
      router.push(`${pathname}?scope=${newScope}`);
    }
  };

  return (
    <div>
      <label>
        {t("scopeFilter.label")}{" "}
        <select value={currentScope} onChange={handleChange}>
          <option value={ScopeEnum.Following}>
            {t("scopeFilter.following")}
          </option>
          <option value={ScopeEnum.Discover}>
            {t("scopeFilter.discover")}
          </option>
          <option value="all">{t("scopeFilter.all")}</option>
        </select>
      </label>
    </div>
  );
}
