"use client";

import { Recording } from "@/lib/types/strapi-autogenerated";
import { Modal, Stack, Text, Title } from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import { useFormatter } from "next-intl";
import VideoEditor from "../protected/[type]/[username]/video/[id]/edit/video-editor";

interface VideoEditorModalProps {
  recording: Recording;
  opened: boolean;
  onClose: () => void;
}

export function VideoEditorModal({
  recording,
  opened,
  onClose,
}: VideoEditorModalProps) {
  const format = useFormatter();
  const isMobile = useMediaQuery("(max-width: 768px)");

  return (
    <Modal
      opened={opened}
      onClose={onClose}
      fullScreen={isMobile}
      size="xl"
      title={
        <Stack gap={2}>
          <Title order={4}>
            Edit Clip{" "}
            {format.dateTime(new Date(recording.createdAt || ""), {
              dateStyle: "medium",
              timeStyle: "short",
            })}
          </Title>
          <Text size="sm" c="dimmed">
            Trim and export a clip from{" "}
            {decodeURIComponent(recording.follower?.username || "")}
          </Text>
        </Stack>
      }
    >
      <VideoEditor recording={recording} />
    </Modal>
  );
}
