"use client";

import { Source } from "@/lib/types/strapi-autogenerated";
import { useMounted } from "@mantine/hooks";
import { useEffect, useRef, useState } from "react";
import videojs from "video.js";
import Player from "video.js/dist/types/player";
import "video.js/dist/video-js.css";
import { buildVideoRanges, combinePlaylistsFromSources } from "./player-utils";

function initThumbnailPreview(
  player: Player,
  sources: Source[],
  totalDuration: number
) {
  const seekBar = (
    player as unknown as {
      controlBar: { progressControl: { seekBar: { el: () => HTMLElement } } };
    }
  ).controlBar.progressControl.seekBar.el() as HTMLElement;

  const holder = document.createElement("div");
  holder.className = "vjs-thumbnail-holder";
  holder.innerHTML = `
    <img alt="preview" />
    <div class="vjs-thumbnail-time">0:00</div>
  `;
  seekBar.appendChild(holder);

  const img = holder.querySelector("img") as HTMLImageElement;
  const timeDisplay = holder.querySelector(
    ".vjs-thumbnail-time"
  ) as HTMLElement;

  const thumbWidth = 160;
  const thumbHeight = 284;

  const videoRanges = buildVideoRanges(sources);

  if (videoRanges.length > 0) {
    img.src = `${process.env.NEXT_PUBLIC_S3_URL}${videoRanges[0].path}thumbnails.jpg`;
  }

  seekBar.addEventListener("mousemove", (e) => {
    const rect = seekBar.getBoundingClientRect();
    const percent = Math.max(
      0,
      Math.min(1, (e.clientX - rect.left) / rect.width)
    );
    const time = percent * totalDuration;

    let currentVideo = videoRanges[0];
    let timeInVideo = time;

    for (const range of videoRanges) {
      if (time >= range.start && time < range.end) {
        currentVideo = range;
        timeInVideo = time - range.start;
        break;
      } else if (time >= range.end) {
        currentVideo = range;
        timeInVideo = range.end - range.start;
      }
    }

    if (!currentVideo) return;

    const newThumbnailUrl = `${process.env.NEXT_PUBLIC_S3_URL}${currentVideo.path}thumbnails.jpg`;
    if (!img.src.includes(currentVideo.path)) {
      img.src = newThumbnailUrl;
    }

    const thumbIndex = Math.floor(timeInVideo / currentVideo.interval);
    const col = thumbIndex % currentVideo.cols;
    const row = Math.floor(thumbIndex / currentVideo.cols);

    holder.style.left = `${e.clientX - rect.left}px`;
    img.style.objectFit = "none";
    img.style.objectPosition = `-${col * thumbWidth}px -${row * thumbHeight}px`;
    img.style.width = `${thumbWidth}px`;
    img.style.height = `${thumbHeight}px`;

    const mins = Math.floor(time / 60);
    const secs = Math.floor(time % 60);
    timeDisplay.textContent = `${mins}:${secs.toString().padStart(2, "0")}`;

    holder.classList.add("vjs-thumbnail-show");
  });

  seekBar.addEventListener("mouseleave", () => {
    holder.classList.remove("vjs-thumbnail-show");
  });
}

export function VideoPlayer({ sources }: { sources: Source[] }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const playerRef = useRef<Player | null>(null);
  const playlistUrlRef = useRef<string | null>(null);
  const mounted = useMounted();
  const [loading, setLoading] = useState(true);
  const [playerError, setPlayerError] = useState<string | null>(null);

  const totalDuration = sources.reduce((sum, s) => sum + (s.duration || 0), 0);

  // Derive validation error from props (not in effect)
  const validationError =
    !sources || sources.length === 0 ? "No sources available" : null;

  useEffect(() => {
    if (!mounted || validationError) return;

    const combinedPlaylist = combinePlaylistsFromSources(sources, "original");

    if (!combinedPlaylist || combinedPlaylist.length < 50) {
      return;
    }

    const blob = new Blob([combinedPlaylist], {
      type: "application/vnd.apple.mpegurl",
    });
    const playlistUrl = URL.createObjectURL(blob);
    playlistUrlRef.current = playlistUrl;

    if (videoRef.current && !playerRef.current) {
      const player = videojs(videoRef.current, {
        autoplay: true,
        muted: false,
        controls: true,
        responsive: true,
        controlBar: {
          pictureInPictureToggle: false,
        },
        html5: {
          vhs: {
            overrideNative: true,
          },
          nativeAudioTracks: false,
          nativeVideoTracks: false,
        },
      });

      player.src({
        src: playlistUrl,
        type: "application/x-mpegURL",
      });

      player.on("error", () => {
        console.error("Player error:", player.error());
        setPlayerError("Failed to load video");
        setLoading(false);
      });

      player.ready(() => {
        setLoading(false);

        if (sources[0]?.path) {
          const testImg = new Image();
          testImg.onload = () => {
            initThumbnailPreview(player, sources, totalDuration);
          };
          testImg.onerror = () => {
            console.log("No thumbnail sprite found");
          };
          testImg.src = `${process.env.NEXT_PUBLIC_S3_URL}${sources[0].path}thumbnails.jpg`;
        }
      });

      playerRef.current = player;
    }

    return () => {
      if (playerRef.current) {
        playerRef.current.dispose();
        playerRef.current = null;
      }
      if (playlistUrlRef.current) {
        URL.revokeObjectURL(playlistUrlRef.current);
        playlistUrlRef.current = null;
      }
    };
  }, [mounted, sources, totalDuration, validationError]);

  if (!mounted) return null;

  const error = validationError || playerError;

  if (error) {
    return <div style={{ color: "red", padding: 20 }}>Error: {error}</div>;
  }

  return (
    <div className="video-player-wrapper">
      {loading && <div style={{ padding: 20 }}>Loading video...</div>}

      <style jsx global>{`
        .video-player-wrapper {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100%;
          width: 100%;
          background: #000;
        }

        .video-player-wrapper [data-vjs-player] {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100%;
          width: 100%;
        }

        .video-player-wrapper .video-js {
          max-height: 100%;
          max-width: 100%;
          border-radius: 16px;
          overflow: hidden;
        }

        .video-player-wrapper .vjs-tech {
          object-fit: contain; /* Changed from cover - no cropping */
          border-radius: 16px;
        }

        /* Fullscreen fix */
        .video-player-wrapper .video-js.vjs-fullscreen {
          border-radius: 0;
        }

        .video-player-wrapper .video-js.vjs-fullscreen .vjs-tech {
          object-fit: contain;
          border-radius: 0;
        }

        .video-player-wrapper .video-js.vjs-fullscreen .vjs-control-bar {
          border-radius: 0;
        }

        /* Controls overlay on video */
        .video-player-wrapper .vjs-control-bar {
          border-radius: 0 0 16px 16px;
          background: linear-gradient(transparent, rgba(0, 0, 0, 0.7));
        }

        /* Big play button centered */
        .video-player-wrapper .vjs-big-play-button {
          border-radius: 50%;
        }

        .vjs-thumbnail-holder {
          position: absolute;
          bottom: 100%;
          display: none;
          pointer-events: none;
          transform: translateX(-50%);
          margin-bottom: 10px;
          border: 2px solid #fff;
          border-radius: 4px;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.5);
          overflow: hidden;
          background: #000;
          z-index: 100;
        }

        .vjs-thumbnail-holder.vjs-thumbnail-show {
          display: block;
        }

        .vjs-thumbnail-holder img {
          display: block;
          width: 160px;
          height: 284px;
          object-fit: none;
        }

        .vjs-thumbnail-time {
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          background: rgba(0, 0, 0, 0.7);
          color: #fff;
          font-size: 11px;
          text-align: center;
          padding: 2px 0;
        }

        .video-player-wrapper .video-js {
          font-size: 16px; /* Increase from 10px to make everything bigger */
        }

        /* Or target control bar specifically */
        .video-player-wrapper .vjs-control-bar {
          font-size: 18px;
        }

        /* Progress bar height */
        .video-player-wrapper .vjs-progress-holder {
          height: 0.6em; /* Bigger progress bar */
        }

        /* Keep progress bar big even without hover */
        .video-player-wrapper .vjs-progress-control:hover .vjs-progress-holder,
        .video-player-wrapper .vjs-progress-control .vjs-progress-holder {
          height: 0.6em;
        }

        /* Slider (the clickable area) */
        .video-player-wrapper .vjs-slider {
          height: 0.6em;
        }

        /* Play progress (the filled part) */
        .video-player-wrapper .vjs-play-progress,
        .video-player-wrapper .vjs-load-progress {
          height: 100%;
        }

        .video-js .vjs-play-progress:before {
          font-size: 1.4em;
        }
      `}</style>

      <div data-vjs-player style={{ display: loading ? "none" : "block" }}>
        <video
          ref={videoRef}
          className="video-js vjs-default-skin vjs-big-play-centered"
          playsInline
        />
      </div>
    </div>
  );
}
