import dayjs from "@/app/lib/dayjs";
import {
  ActionIcon,
  Anchor,
  Avatar,
  Box,
  Button,
  Group,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconClock, IconVideo, IconWorldSearch } from "@tabler/icons-react";
import {
  dehydrate,
  HydrationBoundary,
  InfiniteData,
  QueryClient,
} from "@tanstack/react-query";
import { getFormatter, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";

import { Follower } from "@/lib/types/strapi-autogenerated";

import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import FollowButton from "@/app/[locale]/(protected)/components/follow-button";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";

import UnfollowButton from "@/app/[locale]/(protected)/components/unfollow-button";
import OpenSocial from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import Image from "next/image";
import { fetchProfileRecordings, getFollower } from "./actions/actions";
import { AdminMenu } from "./components/admin-menu";
import ProfileRecordings from "./components/profile-recordings";
import { ProfileFilters, profileParamsCache } from "./lib/search-params";

interface PageProps {
  params: Promise<{
    username: string;
    type: string;
  }>;
  searchParams: Promise<ProfileFilters>;
}

export default async function Page({ params, searchParams }: PageProps) {
  const { type, username } = await params;
  const filters = await profileParamsCache.parse(searchParams);
  const t = await getTranslations("protected.profile");
  const format = await getFormatter();

  const follower = await getFollower({ username, type });

  if (!follower) {
    notFound();
  }

  const queryClient = new QueryClient();

  // Query key uses type/username - matches what modal will use
  await queryClient.prefetchInfiniteQuery({
    queryKey: ["profile-recordings", type, username, filters],
    queryFn: ({ pageParam }) =>
      fetchProfileRecordings(type, username, filters, pageParam),
    initialPageParam: 1,
  });

  const initialData = queryClient.getQueryData<
    InfiniteData<Awaited<ReturnType<typeof fetchProfileRecordings>>>
  >(["profile-recordings", type, username, filters]);

  const recordings = initialData?.pages?.[0]?.data ?? [];
  const isRecording = recordings.some((r) =>
    r.sources?.some((s) => s.state === "recording"),
  );
  const hasRecordings = recordings.length > 0;

  return (
    <section>
      <Group mb="xl">
        <Box pos="relative">
          <Avatar
            size={150}
            style={{
              ...(isRecording ? { border: "3px solid red" } : {}),
            }}
          >
            {follower.avatar?.url && (
              <Image
                src={generateAvatarUrl(follower.avatar?.url)}
                alt={"Avatar"}
                width={150}
                height={150}
              />
            )}
          </Avatar>

          {follower.type && (
            <FollowerTypeIcon
              pos="absolute"
              color="transparent"
              type={follower.type}
              top="50%"
              left="50%"
              size={90}
              style={{ transform: "translate(-50%, -50%)" }}
            />
          )}
        </Box>

        <Stack gap="xs">
          <Group>
            <Title order={2}>{follower.username}</Title>
            {follower.country && (
              <CountryFlag
                country={follower.country}
                countryCode={follower.countryCode}
                size={40}
              />
            )}
          </Group>

          <Group gap="xs">
            <OpenSocial follower={follower} />
            {follower.isFollowing ? (
              <UnfollowButton
                username={follower.username!}
                type={follower.type}
              />
            ) : (
              <FollowButton
                username={follower.username!}
                type={follower.type}
              />
            )}
            <AdminMenu follower={follower} />
          </Group>
          <div>
            <Text size="sm" c="dimmed" suppressHydrationWarning>
              {t("addedAgo", {
                time: format.relativeTime(new Date(follower.createdAt || "")),
              })}
            </Text>
            <Text size="sm" c="dimmed" suppressHydrationWarning>
              {t("lastCheckedAgo", {
                time: format.relativeTime(
                  new Date(follower.lastCheckedAt || ""),
                ),
              })}
            </Text>
          </div>
        </Stack>
      </Group>

      {!hasRecordings ? (
        <EmptyState follower={follower} />
      ) : (
        <HydrationBoundary state={dehydrate(queryClient)}>
          <ProfileRecordings />
        </HydrationBoundary>
      )}
    </section>
  );
}

async function EmptyState({ follower }: { follower: Follower }) {
  const t = await getTranslations("protected.profile");
  const isNewlyAdded = dayjs().diff(dayjs(follower.createdAt), "minute") < 5;

  if (isNewlyAdded) {
    return (
      <Stack align="center" justify="center" py={80} gap="lg">
        <ActionIcon variant="transparent" size={120} radius="xl" color="blue">
          <IconClock size={90} stroke={2} />
        </ActionIcon>
        <Stack align="center" gap={12}>
          <Title order={2} fw={600}>
            {t("emptyNewlyAdded.title", { username: follower.username })}
          </Title>
          <Text size="xl" c="dimmed" maw={450} ta="center">
            {t("emptyNewlyAdded.description")}
          </Text>
        </Stack>
      </Stack>
    );
  }

  return (
    <Stack align="center" justify="center" py={80} gap="lg">
      <ActionIcon variant="transparent" size={120} radius="xl" color="white">
        <IconVideo size={90} stroke={2} />
      </ActionIcon>
      <Stack align="center" gap={12}>
        <Title order={2} fw={600}>
          {t("emptyDefault.title")}
        </Title>
        <Text size="xl" c="dimmed" maw={450} ta="center">
          {t("emptyDefault.description", { username: follower.username })}
        </Text>
      </Stack>
      <Anchor href="/discover" underline="never">
        <Button
          size="lg"
          radius="md"
          leftSection={<IconWorldSearch size={20} />}
        >
          {t("discoverStreamers")}
        </Button>
      </Anchor>
    </Stack>
  );
}
