import { ScopeEnum, FollowRequestBodyTypeEnum } from "@/lib/types/strapi-autogenerated";
import api from "@/app/api";
import FollowButton from "../follow-button";
import UnfollowButton from "../unfollow-button";
import ScopeFilter from "../scope-filter";

type Props = {
  searchParams: Promise<{ scope?: string }>;
};

export default async function FollowingsPage({ searchParams }: Props) {
  const { scope: scopeParam } = await searchParams;
  const scope = scopeParam || "all";

  const response = await api.follower.getFollowers(
    scope === "all" ? { populate: "*" } : { scope: scope as ScopeEnum, populate: "*" }
  );

  const data = response.data?.data || [];

  return (
    <section>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
        <h2>Followers ({data.length})</h2>
        <ScopeFilter currentScope={scope} />
      </div>

      {data.length === 0 ? (
        <p>
          {scope === ScopeEnum.Following
            ? "You're not following anyone yet."
            : scope === ScopeEnum.Discover
            ? "No more accounts to discover."
            : "No followers found."}
        </p>
      ) : (
        <ul style={{ listStyle: "none", padding: 0 }}>
          {data.map((f) => (
            <li key={f.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
              <div>
                <strong>{f.username}</strong> <span>@{f.slug}</span>
                <br />
                <small>{f.totalRecordings} recordings</small>
              </div>
              {f.isFollowing ? (
                <UnfollowButton id={f.id!} />
              ) : (
                <FollowButton username={f.username!} slug={f.slug!} type={f.type as unknown as FollowRequestBodyTypeEnum} />
              )}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
