"use client";

import { followUser } from "@/app/actions/followers";
import { FollowRequestBody } from "@/lib/types/strapi-autogenerated";
import { Button } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconCheck } from "@tabler/icons-react";
import { useTransition } from "react";

export default function FollowButton({
  username,
  type,
  onSuccess,
}: FollowRequestBody & { onSuccess?: () => void }) {
  const [isPending, startTransition] = useTransition();

  const handleClick = () => {
    startTransition(async () => {
      const result = await followUser({ username, type });

      if (result.success) {
        notifications.show({
          title: "Followed!",
          message: `You are now following ${username}`,
          color: "green",
          icon: <IconCheck size={16} />,
        });
        onSuccess?.();
      }

      if (result.error) {
        notifications.show({
          title: "Error",
          message: result.error,
          color: "red",
        });
      }
    });
  };

  return (
    <Button color="red" onClick={handleClick} loading={isPending}>
      Follow
    </Button>
  );
}
