"use client";

import { useUser } from "@/app/providers/user-provider";
import {
  FollowerTypeEnum,
  Recording,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import { Anchor, Badge, Box, Button, CopyButton, Image } from "@mantine/core";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useRef, useState } from "react";
import { MiniPlayer } from "../[type]/[username]/live/[id]/_components/mini-player";
import { formatDuration } from "../[type]/[username]/live/[id]/_components/player-utils";
import { FollowerTypeIcon } from "./follower-type";
import { SOCIAL_URL_PATTERNS } from "./open-social";

interface Props {
  recording: Recording;
  username: string;
  type: FollowerTypeEnum;
}

export function ImageVideoPreview({ recording, type, username }: Props) {
  const user = useUser();
  const searchParams = useSearchParams();
  const [showVideo, setShowVideo] = useState(false);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);
  const router = useRouter();

  const href = `/${type}/${username}/live/${
    recording.documentId
  }?${searchParams.toString()}`;

  const sources = recording.sources;
  const totalDuration =
    sources?.reduce((sum, s) => sum + (s.duration || 0), 0) || 0;

  const isRecording = sources?.some(
    (s) => s.state === SourceStateEnum.Recording
  );

  const uri = sources?.length
    ? process.env.NEXT_PUBLIC_S3_URL! + sources[sources.length - 1].path
    : null;

  const handleMouseEnter = () => {
    if (!sources || sources.length === 0 || isRecording) return;
    timeoutRef.current = setTimeout(() => {
      setShowVideo(true);
    }, 300);
  };

  const handleMouseLeave = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      timeoutRef.current = null;
    }
    setShowVideo(false);
  };

  const handleDoubleClick = () => {
    router.push(href);
  };

  return (
    <div
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      style={{
        aspectRatio: "16/9",
        position: "relative",
        overflow: "hidden",
        borderRadius: "var(--mantine-radius-md)",
      }}
    >
      <Anchor
        component={Link}
        href={href}
        style={{
          pointerEvents: isRecording ? "none" : "auto",
          cursor: isRecording ? "not-allowed" : "pointer",
        }}
      >
        <Image
          alt=""
          radius="md"
          src={
            uri
              ? isRecording
                ? uri + "screenshot.jpg"
                : uri + "preview.jpg"
              : null
          }
          loading="lazy"
          fallbackSrc="https://placehold.co/180x280/black/white?text=Recording started"
          w="100%"
          h="100%"
          fit="cover"
          style={{
            objectPosition: "center center",
            display: showVideo ? "none" : "block",
            ...(isRecording && {
              border: "2px solid red",
              borderRadius: "var(--mantine-radius-md)",
            }),
          }}
        />
      </Anchor>

      {isRecording && (
        <Badge
          component="a"
          href={SOCIAL_URL_PATTERNS[type](username)}
          target="_blank"
          rel="noopener noreferrer"
          pos="absolute"
          top={8}
          left={8}
          radius="sm"
          color="red"
          variant="filled"
          size="sm"
          style={{ cursor: "pointer", zIndex: 10 }}
          leftSection={
            <Box
              w={8}
              h={8}
              bg="white"
              style={{ borderRadius: "50%", animation: "pulse 1s infinite" }}
            />
          }
        >
          REC {sources && sources?.length > 1 && `#${sources.length}`}
        </Badge>
      )}

      {showVideo && sources && (
        <div onClick={handleDoubleClick} style={{ cursor: "pointer" }}>
          <MiniPlayer sources={sources} />
        </div>
      )}

      <FollowerTypeIcon
        type={type}
        color="black"
        opacity={0.8}
        pos="absolute"
        top={10}
        right={8}
        style={{
          pointerEvents: "none",
        }}
      />

      {isRecording && user?.role?.type === "superadmin" ? (
        <CopyButton
          value={
            recording.sources
              ?.find((s) => s.state === "recording")
              ?.executionId?.toString() || ""
          }
        >
          {({ copied, copy }) => (
            <Button
              size="compact-xs"
              color={copied ? "gray" : "black"}
              style={{
                position: "absolute",
                bottom: 8,
                right: 8,
              }}
              onClick={copy}
            >
              {
                recording.sources?.find((s) => s.state === "recording")
                  ?.executionId
              }
            </Button>
          )}
        </CopyButton>
      ) : null}

      {totalDuration > 0 && !showVideo! && !isRecording && (
        <div
          style={{
            position: "absolute",
            bottom: 8,
            right: 8,
            backgroundColor: "rgba(0, 0, 0, 0.8)",
            color: "white",
            padding: "2px 6px",
            borderRadius: 4,
            fontSize: 12,
            fontWeight: 500,
            pointerEvents: "none",
          }}
        >
          {isRecording
            ? totalDuration > 0
              ? `+${formatDuration(totalDuration)}`
              : "LIVE"
            : totalDuration > 0
            ? formatDuration(totalDuration)
            : null}
        </div>
      )}
    </div>
  );
}
