// components/infinite-followers.tsx
"use client";

import { getFollowers } from "@/app/actions/followers";

import dayjs from "@/app/lib/dayjs";
import { SortOptions } from "@/lib/types/filtering";
import {
  BrowseFollowersResponse,
  ScopeEnum,
  SourceStateEnum,
  type FollowerWithMeta,
} from "@/lib/types/strapi-autogenerated";
import {
  ActionIcon,
  Anchor,
  Avatar,
  Box,
  Card,
  Checkbox,
  Divider,
  Flex,
  Grid,
  Group,
  Loader,
  Select,
  Stack,
  Text,
  Title,
  Tooltip,
  useMatches,
} from "@mantine/core";
import { useIntersection } from "@mantine/hooks";
import { IconWindowMaximize } from "@tabler/icons-react";
import Link from "next/link";
import { parseAsBoolean, parseAsStringEnum, useQueryState } from "nuqs";
import { useEffect, useState, useTransition } from "react";
import { ImageVideoPreview } from "../recordings/_components/image-video-preview";
import FollowButton from "./follow-button";
import UnfollowButton from "./unfollow-button";

const SORT_OPTIONS = [
  { value: SortOptions.UsernameAsc, label: "Username A-Z" },
  { value: SortOptions.UsernameDesc, label: "Username Z-A" },
  { value: SortOptions.createdAtDesc, label: "Newest first" },
  { value: SortOptions.createdAtAsc, label: "Oldest first" },
];

interface Props {
  title: string;
  initialData: FollowerWithMeta[];
  initialPagination: BrowseFollowersResponse["meta"];
  initialSort?: SortOptions;
  initialScope: ScopeEnum;
}

export default function InfiniteFollowers({
  title,
  initialData,
  initialPagination,
  initialSort,
  initialScope,
}: Props) {
  const cardPadding = useMatches({
    base: "sm",
    sm: "md",
    md: "lg",
  });

  const [data, setData] = useState(initialData);
  const [page, setPage] = useState(initialPagination?.pagination?.page ?? 1);
  const [hasMore, setHasMore] = useState(
    page < (initialPagination?.pagination?.pageCount ?? 1)
  );
  const [sort, setSort] = useQueryState(
    "sort",
    parseAsStringEnum<SortOptions>(Object.values(SortOptions)).withDefault(
      initialSort || SortOptions.createdAtDesc
    )
  );
  const [hasRecordings, setHasRecordings] = useQueryState(
    "hasRecordings",
    parseAsBoolean.withDefault(true)
  );
  const [isPending, startTransition] = useTransition();

  const { ref, entry } = useIntersection({
    threshold: 0.5,
  });

  const update = (object = {}) => {
    console.log(sort, object);
    startTransition(async () => {
      const result = await getFollowers({
        scope: initialScope,
        page: 1,
        sort,
        hasRecordings,
        ...object,
      });
      setData(result.data);
      setPage(1);
      setHasMore(1 < (result.meta?.pagination?.pageCount ?? 1));
    });
  };

  const handleSortChange = (sort: string | null) => {
    if (!sort) return;
    setSort(sort as unknown as SortOptions);
    update({ sort });
  };

  const handleHasRecordingsChange = (hasRecordings: boolean | null) => {
    setHasRecordings(hasRecordings);
    update({ hasRecordings });
  };

  const handleFollowed = (id: number) => {
    setData((prev) => prev.filter((f) => f.id !== id));
  };

  useEffect(() => {
    if (entry?.isIntersecting && hasMore && !isPending) {
      startTransition(async () => {
        const nextPage = page + 1;
        const result = await getFollowers({
          scope: initialScope,
          page: nextPage,
          sort,
          hasRecordings,
        });

        setData((prev) => {
          const existingIds = new Set(prev.map((f) => f.id));
          const newItems = result.data.filter((f) => !existingIds.has(f.id));
          return [...prev, ...newItems];
        });
        setPage(nextPage);
        setHasMore(nextPage < (result.meta?.pagination?.pageCount ?? 1));
      });
    }
  }, [
    entry?.isIntersecting,
    hasMore,
    hasRecordings,
    initialScope,
    isPending,
    page,
    sort,
  ]);

  return (
    <Stack gap="sm">
      <Group justify="space-between">
        <Title order={1} size="lg">
          {title} ({initialPagination?.pagination?.total || 0})
        </Title>

        <Group>
          {initialScope === ScopeEnum.Discover ? (
            <Checkbox
              label="Show only streamers with recordings"
              checked={hasRecordings}
              onChange={(event) =>
                handleHasRecordingsChange(event.currentTarget.checked)
              }
            />
          ) : null}
          <Select
            key={sort}
            size="sm"
            w={180}
            value={sort}
            onChange={handleSortChange}
            data={SORT_OPTIONS}
            disabled={isPending}
          />
        </Group>
      </Group>
      <Divider />
      <Stack gap="md">
        {data.map((follower) => (
          <Card
            key={follower.documentId}
            shadow="sm"
            padding={cardPadding}
            radius="md"
            bg="black"
            withBorder
          >
            <Grid justify="center" align="center">
              <Grid.Col span="content">
                <Anchor
                  component={Link}
                  href={`/${follower?.type}/${follower?.username}`}
                >
                  <Avatar
                    size="lg"
                    src={follower.avatar?.url}
                    styles={{
                      image: {
                        transform: "scale(2)",
                        objectFit: "cover",
                      },
                    }}
                  />
                </Anchor>
              </Grid.Col>
              <Grid.Col span="auto">
                <Anchor
                  component={Link}
                  href={`/${follower?.type}/${follower?.username}`}
                  size="md"
                  truncate
                  maw={120}
                >
                  {follower.username}
                </Anchor>
                <Text size="xs">{follower.totalRecordings} recordings</Text>

                <Text size="xs">
                  added {dayjs(follower.createdAt).fromNow()}
                </Text>
              </Grid.Col>
              <Grid.Col span={4}>
                <Flex gap="xs" justify="right" align="center">
                  <Tooltip label="Go to tiktok">
                    <ActionIcon
                      size="lg"
                      component={Link}
                      href={`https://www.tiktok.com/@${follower.username}/live`}
                      target="_blank"
                    >
                      <IconWindowMaximize size={24} />
                    </ActionIcon>
                  </Tooltip>
                  {follower.isFollowing ? (
                    <>
                      <UnfollowButton
                        documentId={follower.documentId!}
                        onSuccess={() => handleFollowed(follower.id!)}
                      />
                    </>
                  ) : (
                    <FollowButton
                      username={follower.username!}
                      type={follower.type}
                      onSuccess={() => handleFollowed(follower.id!)}
                    />
                  )}
                </Flex>
              </Grid.Col>
            </Grid>
            {follower.recordings && follower.recordings?.length > 0 ? (
              <Box mt="sm">
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "repeat(auto-fill, 160px)",
                    gridAutoRows: "306px",
                    gap: "1.4em",
                    maxHeight: 306,
                    overflow: "hidden",
                  }}
                >
                  {follower.recordings?.map((rec) => {
                    const isRecording = rec.sources?.some(
                      (s) => s.state === SourceStateEnum.Recording
                    );

                    return (
                      <Stack key={rec.documentId} gap="4">
                        <ImageVideoPreview
                          href={`/${follower.type}/${follower.username}/live/${rec.documentId}`}
                          w={160}
                          h={284}
                          sources={rec.sources}
                        />
                        <div>
                          <Text size="xs">
                            {isRecording ? "recording since" : "recorded"}{" "}
                            {dayjs(rec.createdAt).fromNow()}
                          </Text>
                        </div>
                      </Stack>
                    );
                  })}
                </div>
              </Box>
            ) : null}
          </Card>
        ))}
      </Stack>
      {/* Sentinel element */}
      <div ref={ref} style={{ height: 1 }} />

      {isPending && <Loader size="sm" style={{ alignSelf: "center" }} />}

      {!hasMore && data.length > 0 && (
        <p style={{ textAlign: "center", color: "gray" }}>No more to load</p>
      )}
    </Stack>
  );
}
