"use client";

import { Follower } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Tooltip } from "@mantine/core";
import { IconWindowMaximize } from "@tabler/icons-react";
import Link from "next/link";

export default function OpenSocial({ follower }: { follower: Follower }) {
  return (
    <Tooltip label="Go to tiktok">
      <ActionIcon
        size="lg"
        component={Link}
        href={`https://www.tiktok.com/@${follower.username}/live`}
        target="_blank"
      >
        <IconWindowMaximize size={24} />
      </ActionIcon>
    </Tooltip>
  );
}
