"use client";

import { Follower, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Tooltip } from "@mantine/core";
import { IconWindowMaximize } from "@tabler/icons-react";
import Link from "next/link";

export const SOCIAL_URL_PATTERNS: Record<
  FollowerTypeEnum,
  (username: string) => string
> = {
  [FollowerTypeEnum.Tiktok]: (username) =>
    `https://www.tiktok.com/@${username}/live`,
  [FollowerTypeEnum.Twitch]: (username) => `https://www.twitch.tv/${username}`,
};

export default function OpenSocial({ follower }: { follower: Follower }) {
  const href = SOCIAL_URL_PATTERNS[follower.type](follower.username);

  return (
    <Tooltip label={`Go to ${follower.type}`}>
      <ActionIcon size="lg" component={Link} href={href} target="_blank">
        <IconWindowMaximize size={24} />
      </ActionIcon>
    </Tooltip>
  );
}
