"use client";

import { Follower, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Tooltip } from "@mantine/core";
import { IconWindowMaximize } from "@tabler/icons-react";
import Link from "next/link";

export default function OpenSocial({ follower }: { follower: Follower }) {
  const type = follower.type;

  const href =
    type === FollowerTypeEnum.Tiktok
      ? `https://www.tiktok.com/@${follower.username}/live`
      : `https://www.twitch.tv/${follower.username}`;

  return (
    <Tooltip label={`Go to ${type}`}>
      <ActionIcon size="lg" component={Link} href={href} target="_blank">
        <IconWindowMaximize size={24} />
      </ActionIcon>
    </Tooltip>
  );
}
