import InfiniteRecordings from "@/app/(protected)/_components/infinity-recordings";
import api from "@/lib/api";
import { SortOptions } from "@/lib/types/filtering";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import {
  ActionIcon,
  Anchor,
  Button,
  deepMerge,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconVideo, IconWorldSearch } from "@tabler/icons-react";

export const followingDefaultOptions = {
  scope: ScopeEnum.Following,
  filters: {
    sources: {
      state: {
        $eq: ["done"],
      },
    },
  },
  populate: {
    sources: {
      fields: ["*"],
      filters: {
        state: {
          $eq: "done",
        },
      },
      populate: ["videoSmall", "videoOriginal"], // we ask for original because sometime small is null while encoding for mini-player
    },
    follower: {
      fields: ["username", "type"],
      populate: {
        avatar: {
          fields: ["url"],
        },
      },
    },
  },
};

export default async function FollowingsPage() {
  const fetchAction = async (
    options: Parameters<typeof api.recording.browseRecordings>[0]
  ) => {
    "use server";
    const response = await api.recording.browseRecordings(
      deepMerge(followingDefaultOptions, {
        ...options,
        "pagination[pageSize]": 10,
      }) // we add pagination[pageSize] here because default options is shared with the model
    );
    return response.data;
  };

  const { data, meta } = await fetchAction({
    "pagination[page]": 1,
    sort: SortOptions.createdAtDesc,
  });

  return (
    <section>
      {data?.length === 0 ? (
        <Stack align="center" justify="center" py={80} gap="lg">
          <ActionIcon
            variant="transparent"
            size={120}
            radius="xl"
            color="white"
          >
            <IconVideo size={90} stroke={2} />
          </ActionIcon>
          <Stack align="center" gap={12}>
            <Title order={2} fw={600}>
              No recordings yet
            </Title>
            <Text size="xl" c="dimmed" maw={450} ta="center">
              Follow streamers to see their recordings here
            </Text>
          </Stack>
          <Anchor href="/discover" underline="never">
            <Button
              size="lg"
              radius="md"
              leftSection={<IconWorldSearch size={20} />}
            >
              Discover Streamers
            </Button>
          </Anchor>
        </Stack>
      ) : (
        <InfiniteRecordings
          initialData={data}
          initialPagination={meta}
          initialSort={SortOptions.createdAtDesc}
          fetchAction={fetchAction}
        />
      )}
    </section>
  );
}
