import InfiniteFollowers from "@/app/(protected)/_components/infinite-followers";
import { getFollowers } from "@/app/actions/followers";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";

export default async function FollowingsPage() {
  const response = await getFollowers(ScopeEnum.Following, 1);

  const data = response.data || [];
  const meta = response.meta;

  return (
    <section>
      {data.length === 0 ? (
        <p>You are not following anyone yet.</p>
      ) : (
        <InfiniteFollowers
          title="Followers"
          initialData={data}
          initialPagination={meta}
          initialSort="username:asc"
        />
      )}
    </section>
  );
}
