import { Api } from "@/lib/types/strapi-autogenerated";
import qs from "qs";

const publicApi = new Api({
  baseURL: (process.env.STRAPI_URL || "http://localhost:1337") + "/api",
  timeout: 30000,
  paramsSerializer: {
    serialize: (params) => qs.stringify(params, { encodeValuesOnly: true }),
  },
  securityWorker: async () => {
    return {
      headers: {
        Authorization: `Bearer ${process.env.STRAPI_TOKEN}`,
      },
    };
  },
});

publicApi.instance.interceptors.response.use(
  (response) => response,
  (error) => {
    if (
      error.code === "ECONNRESET" &&
      error.config &&
      !error.config.__retried
    ) {
      error.config.__retried = true;
      return publicApi.instance.request(error.config);
    }
    const status = error.response?.status;
    if (status && status !== 404) {
      console.error(`[API] ${status} ${error.config?.method?.toUpperCase()} ${error.config?.url}`);
    }
    return Promise.reject(new Error(`API ${status || error.code}: ${error.config?.url}`));
  }
);

export default publicApi;
