export const dynamic = "force-dynamic";

import { Api } from "@/lib/types/strapi-autogenerated";
import qs from "qs";

const publicApi = new Api({
  baseURL:
    (process.env.NEXT_PUBLIC_STRAPI_URL || "http://localhost:1337") + "/api",
  paramsSerializer: {
    serialize: (params) => qs.stringify(params, { encodeValuesOnly: true }),
  },
  securityWorker: async () => {
    return {
      headers: {
        Authorization: `Bearer ${process.env.NEXT_PUBLIC_STRAPI_TOKEN}`,
      },
    };
  },
});

publicApi.instance.interceptors.request.use((config) => {
  //console.log("REQUEST URL:", config.baseURL + ":" + config.url);
  //console.log("PARAMS:", JSON.stringify(config.params));
  // console.log("FULL URL:", api.instance.getUri(config));
  return config;
});

export default publicApi;
