import { Api } from "@/lib/types/strapi-autogenerated";
import qs from "qs";

import http from "http";
import https from "https";

const httpAgent = new http.Agent({ keepAlive: true, maxSockets: 100 });
const httpsAgent = new https.Agent({ keepAlive: true, maxSockets: 100 });

const publicApi = new Api({
  baseURL: (process.env.STRAPI_URL || "http://localhost:1337") + "/api",
  timeout: 10000,
  httpAgent,
  httpsAgent,
  paramsSerializer: {
    serialize: (params) => qs.stringify(params, { encodeValuesOnly: true }),
  },
  securityWorker: async () => {
    return {
      headers: {
        Authorization: `Bearer ${process.env.STRAPI_TOKEN}`,
      },
    };
  },
});

publicApi.instance.interceptors.response.use(
  (response) => response,
  (error) => {
    if (
      error.code === "ECONNRESET" &&
      error.config &&
      !error.config.__retried
    ) {
      error.config.__retried = true;
      return publicApi.instance.request(error.config);
    }
    const status = error.response?.status;
    if (status && status !== 404) {
      console.error(`[API] ${status} ${error.config?.method?.toUpperCase()} ${error.config?.url}`);
    }
    error.request = undefined;
    error.config = undefined;
    return Promise.reject(error);
  }
);

export default publicApi;
