// _components/video-modal-content.tsx
"use client";

import { Source } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Flex, Modal } from "@mantine/core";
import { IconX } from "@tabler/icons-react";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { PlayBack } from "./playback";
import { VideoPlayer } from "./video-player";

interface Props {
  initialId: string;
  username: string;
  platform: string;
  initialSources: Source[];
  initialPrevId: string | null;
  initialNextId: string | null;
  onLoadVideo: (id: string) => Promise<{
    sources: Source[];
    prevId: string | null;
    nextId: string | null;
  }>;
}

export function VideoModal({
  initialId,
  username,
  platform,
  initialSources,
  initialPrevId,
  initialNextId,
  onLoadVideo,
}: Props) {
  const router = useRouter();
  const [currentId, setCurrentId] = useState(initialId);
  const [sources, setSources] = useState(initialSources);
  const [prevId, setPrevId] = useState(initialPrevId);
  const [nextId, setNextId] = useState(initialNextId);
  const [loading, setLoading] = useState(false);

  const basePath = `/${platform}/${username}/live`;

  useEffect(() => {
    window.history.replaceState({}, "", `${basePath}/${currentId}`);
  }, [currentId, basePath]);

  const loadVideo = useCallback(
    async (id: string) => {
      setLoading(true);
      try {
        const data = await onLoadVideo(id);

        setSources(data.sources);
        setPrevId(data.prevId);
        setNextId(data.nextId);
        setCurrentId(id);
      } catch (err) {
        console.error("Failed to load video", err);
      }
      setLoading(false);
    },
    [onLoadVideo]
  );

  return (
    <Modal
      opened={true}
      onClose={() => router.back()}
      fullScreen
      withCloseButton={false}
      styles={{
        body: { height: "100%", padding: 0 },
      }}
    >
      <Flex h="100%" justify="center" align="center" pos="relative">
        <ActionIcon
          variant="subtle"
          color="white"
          size={60}
          radius="xl"
          onClick={() => router.back()}
          pos="absolute"
          top={20}
          right={20}
          style={{ zIndex: 10 }}
        >
          <IconX size={32} />
        </ActionIcon>

        <PlayBack
          prevId={prevId}
          nextId={nextId}
          basePath={`/${platform}/${username}/live`}
          onPrev={() => loadVideo(prevId!)}
          onNext={() => loadVideo(nextId!)}
          loading={loading}
        />

        <VideoPlayer sources={sources} key={currentId} />
      </Flex>
    </Modal>
  );
}
