"use client";

import { useActionState, startTransition } from "react";
import { getFollowers, FollowersState } from "@/app/actions/followers";
import { ScopeEnum, FollowRequestBodyTypeEnum } from "@/lib/types/strapi-autogenerated";
import FollowButton from "./follow-button";
import UnfollowButton from "./unfollow-button";

type Props = {
  initialState: FollowersState;
};

export default function Followings({ initialState }: Props) {
  const [state, formAction, pending] = useActionState(getFollowers, initialState);

  const scope = state?.scope || initialState.scope;
  const followers = state?.data?.data || [];

  const refresh = () => {
    console.log("Followings: refresh called, scope=", scope);
    const formData = new FormData();
    formData.set("scope", scope);
    startTransition(() => {
      console.log("Followings: inside startTransition, calling formAction");
      formAction(formData);
    });
  };

  return (
    <section>
      <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
        <h2>Followers ({followers.length})</h2>
        <form action={formAction}>
          <select
            key={scope}
            name="scope"
            defaultValue={scope}
            onChange={(e) => e.currentTarget.form?.requestSubmit()}
          >
            <option value={ScopeEnum.Following}>Following</option>
            <option value={ScopeEnum.Discover}>Discover</option>
            <option value="all">All</option>
          </select>
          {pending && <span> Loading...</span>}
        </form>
      </header>

      {followers.length === 0 ? (
        <p>
          {scope === ScopeEnum.Following
            ? "You're not following anyone yet."
            : scope === ScopeEnum.Discover
            ? "No more accounts to discover."
            : "No followers found."}
        </p>
      ) : (
        <ul style={{ listStyle: "none", padding: 0 }}>
          {followers.map((f) => (
            <li key={f.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
              <div>
                <strong>{f.username}</strong> <span>@{f.slug}</span>
                <br />
                <small>{f.totalRecordings} recordings</small>
              </div>
              {f.isFollowing ? (
                <UnfollowButton id={f.id!} onSuccess={refresh} />
              ) : (
                <FollowButton username={f.username!} slug={f.slug!} type={f.type as unknown as FollowRequestBodyTypeEnum} onSuccess={refresh} />
              )}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
