"use client";

import { useActionState } from "react";
import { getFollowers, FollowersState } from "@/app/actions/followers";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import FollowButton from "./follow-button";
import UnfollowButton from "./unfollow-button";

type Props = {
  initialState: FollowersState;
};

export default function Followings({ initialState }: Props) {
  const [state, formAction, pending] = useActionState(getFollowers, initialState);

  const followers = state?.data?.data || [];

  return (
    <section>
      <header>
        <h2>Followers ({followers.length})</h2>
        <form action={formAction}>
          <select
            name="scope"
            defaultValue={state?.scope || ScopeEnum.Following}
            onChange={(e) => e.currentTarget.form?.requestSubmit()}
          >
            <option value={ScopeEnum.Following}>Following</option>
            <option value={ScopeEnum.Discover}>Discover</option>
            <option value="all">All</option>
          </select>
          {pending && <span>Loading...</span>}
        </form>
      </header>

      {followers.length === 0 ? (
        <p>
          {state?.scope === ScopeEnum.Following
            ? "You're not following anyone yet."
            : state?.scope === ScopeEnum.Discover
            ? "No more accounts to discover."
            : "No followers found."}
        </p>
      ) : (
        <ul>
          {followers.map((f) => (
            <li key={f.id}>
              <div>
                <strong>{f.username}</strong> <span>@{f.slug}</span>
                <br />
                <small>{f.totalRecordings} recordings</small>
              </div>
              {f.isFollowing ? (
                <UnfollowButton id={f.id!} />
              ) : (
                <FollowButton username={f.username} slug={f.slug} type={f.type} />
              )}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
