"use client";

import { followUser } from "@/app/actions/followers";
import { FollowRequest } from "@/lib/types/strapi-autogenerated";

export default function FollowButton(data: FollowRequest) {
  async function handleClick() {
    await followUser(data);
  }

  return (
    <button
      onClick={handleClick}
      style={{
        color: "#0066cc",
        background: "none",
        border: "1px solid #0066cc",
        padding: "4px 12px",
        borderRadius: 4,
        cursor: "pointer",
      }}
    >
      Follow
    </button>
  );
}
