"use client";

import { followUser } from "@/app/actions/followers";
import { FollowRequestBody } from "@/lib/types/strapi-autogenerated";

export default function FollowButton(data: FollowRequestBody) {
  async function handleClick() {
    await followUser(data);
  }

  return (
    <button type="button" onClick={handleClick}>
      Follow
    </button>
  );
}
