import { logout } from "@/app/actions/auth";
import { getToken } from "@/lib/token";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { redirect } from "next/navigation";
import api from "../api";
import AddFollowerForm from "./add-follower-form";
import Followings from "./followings";
import Recordings from "./recordings";

export default async function DashboardPage() {
  const token = await getToken();

  if (!token) {
    redirect("/login");
  }

  const user =
    await api.usersPermissionsUsersRoles.getUsersPermissionsUsersRoles();

  const defaultScope = ScopeEnum.Following;

  const [followersResponse, recordingsResponse] = await Promise.all([
    api.follower.getFollowers({ scope: defaultScope, populate: "*" }),
    api.recording.getRecordings({ scope: defaultScope, populate: "*" }),
  ]);

  return (
    <div>
      <header>
        <h1>Dashboard</h1>
        <div>
          <span>Hi, {user?.data?.username}</span>
          <form action={logout}>
            <button type="submit">Logout</button>
          </form>
        </div>
      </header>

      <AddFollowerForm />

      <Followings
        initialState={{
          scope: defaultScope,
          data: followersResponse.data,
        }}
      />

      <Recordings
        initialState={{
          scope: defaultScope,
          data: recordingsResponse.data,
        }}
      />
    </div>
  );
}
