"use client";

import { useRouter } from "next/navigation";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";

type Props = {
  currentScope: string;
};

export default function ScopeFilter({ currentScope }: Props) {
  const router = useRouter();

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newScope = e.target.value;
    router.push(`/dashboard?scope=${newScope}`);
  };

  return (
    <div>
      <label>
        Filter:{" "}
        <select value={currentScope} onChange={handleChange}>
          <option value={ScopeEnum.Following}>Following</option>
          <option value={ScopeEnum.Discover}>Discover</option>
          <option value="all">All</option>
        </select>
      </label>
    </div>
  );
}
